// Code generated by warmup; DO NOT EDIT.

package intent

import (
	"github.com/BetaGoRobot/go_utils/reflecting"
)

func init() {
	reflecting.GetFunctionName(AnalyzeMessage) // from /mnt/RapidPool/workspace/BetaGo_v2/internal/application/lark/intent/recognizer.go:86
}
