// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"github.com/BetaGoRobot/BetaGo-Redefine/internal/infrastructure/db/model"
)

func newAgentStep(db *gorm.DB, opts ...gen.DOOption) agentStep {
	_agentStep := agentStep{}

	_agentStep.agentStepDo.IWithDO = gen.WithDOFunc[IAgentStepDo](_agentStep.agentStepDo.withDO)

	_agentStep.agentStepDo.UseDB(db, opts...)
	_agentStep.agentStepDo.UseModel(&model.AgentStep{})

	tableName := _agentStep.agentStepDo.TableName()
	_agentStep.ALL = field.NewAsterisk(tableName)
	_agentStep.ID = field.NewString(tableName, "id")
	_agentStep.RunID = field.NewString(tableName, "run_id")
	_agentStep.Index = field.NewInt32(tableName, "index")
	_agentStep.Kind = field.NewString(tableName, "kind")
	_agentStep.Status = field.NewString(tableName, "status")
	_agentStep.CapabilityName = field.NewString(tableName, "capability_name")
	_agentStep.InputJSON = field.NewString(tableName, "input_json")
	_agentStep.OutputJSON = field.NewString(tableName, "output_json")
	_agentStep.ErrorText = field.NewString(tableName, "error_text")
	_agentStep.ExternalRef = field.NewString(tableName, "external_ref")
	_agentStep.StartedAt = field.NewTime(tableName, "started_at")
	_agentStep.FinishedAt = field.NewTime(tableName, "finished_at")
	_agentStep.CreatedAt = field.NewTime(tableName, "created_at")

	_agentStep.fillFieldMap()

	return _agentStep
}

type agentStep struct {
	agentStepDo agentStepDo

	ALL            field.Asterisk
	ID             field.String
	RunID          field.String
	Index          field.Int32
	Kind           field.String
	Status         field.String
	CapabilityName field.String
	InputJSON      field.String
	OutputJSON     field.String
	ErrorText      field.String
	ExternalRef    field.String
	StartedAt      field.Time
	FinishedAt     field.Time
	CreatedAt      field.Time

	fieldMap map[string]field.Expr
}

func (a agentStep) Table(newTableName string) *agentStep {
	a.agentStepDo.UseTable(newTableName)
	return a.updateTableName(newTableName)
}

func (a agentStep) As(alias string) *agentStep {
	a.agentStepDo.DO = *(a.agentStepDo.As(alias).(*gen.DO))
	return a.updateTableName(alias)
}

func (a *agentStep) updateTableName(table string) *agentStep {
	a.ALL = field.NewAsterisk(table)
	a.ID = field.NewString(table, "id")
	a.RunID = field.NewString(table, "run_id")
	a.Index = field.NewInt32(table, "index")
	a.Kind = field.NewString(table, "kind")
	a.Status = field.NewString(table, "status")
	a.CapabilityName = field.NewString(table, "capability_name")
	a.InputJSON = field.NewString(table, "input_json")
	a.OutputJSON = field.NewString(table, "output_json")
	a.ErrorText = field.NewString(table, "error_text")
	a.ExternalRef = field.NewString(table, "external_ref")
	a.StartedAt = field.NewTime(table, "started_at")
	a.FinishedAt = field.NewTime(table, "finished_at")
	a.CreatedAt = field.NewTime(table, "created_at")

	a.fillFieldMap()

	return a
}

func (a *agentStep) WithContext(ctx context.Context) IAgentStepDo {
	return a.agentStepDo.WithContext(ctx)
}

func (a agentStep) TableName() string { return a.agentStepDo.TableName() }

func (a agentStep) Alias() string { return a.agentStepDo.Alias() }

func (a agentStep) Columns(cols ...field.Expr) gen.Columns { return a.agentStepDo.Columns(cols...) }

func (a *agentStep) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := a.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (a *agentStep) fillFieldMap() {
	a.fieldMap = make(map[string]field.Expr, 13)
	a.fieldMap["id"] = a.ID
	a.fieldMap["run_id"] = a.RunID
	a.fieldMap["index"] = a.Index
	a.fieldMap["kind"] = a.Kind
	a.fieldMap["status"] = a.Status
	a.fieldMap["capability_name"] = a.CapabilityName
	a.fieldMap["input_json"] = a.InputJSON
	a.fieldMap["output_json"] = a.OutputJSON
	a.fieldMap["error_text"] = a.ErrorText
	a.fieldMap["external_ref"] = a.ExternalRef
	a.fieldMap["started_at"] = a.StartedAt
	a.fieldMap["finished_at"] = a.FinishedAt
	a.fieldMap["created_at"] = a.CreatedAt
}

func (a agentStep) clone(db *gorm.DB) agentStep {
	a.agentStepDo.ReplaceConnPool(db.Statement.ConnPool)
	return a
}

func (a agentStep) replaceDB(db *gorm.DB) agentStep {
	a.agentStepDo.ReplaceDB(db)
	return a
}

type agentStepDo struct {
	gen.GenericsDo[IAgentStepDo, *model.AgentStep]
}
type IAgentStepDo interface {
	gen.IGenericsDo[IAgentStepDo, *model.AgentStep]
}

func (a *agentStepDo) withDO(do gen.Dao) IAgentStepDo {
	_r := &agentStepDo{}
	_r.DO = *do.(*gen.DO)
	_r.IWithDO = gen.WithDOFunc[IAgentStepDo](a.withDO)
	return _r
}
