// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"github.com/BetaGoRobot/BetaGo-Redefine/internal/infrastructure/db/model"
)

func newAgentCardSurface(db *gorm.DB, opts ...gen.DOOption) agentCardSurface {
	_agentCardSurface := agentCardSurface{}

	_agentCardSurface.agentCardSurfaceDo.IWithDO = gen.WithDOFunc[IAgentCardSurfaceDo](_agentCardSurface.agentCardSurfaceDo.withDO)

	_agentCardSurface.agentCardSurfaceDo.UseDB(db, opts...)
	_agentCardSurface.agentCardSurfaceDo.UseModel(&model.AgentCardSurface{})

	tableName := _agentCardSurface.agentCardSurfaceDo.TableName()
	_agentCardSurface.ALL = field.NewAsterisk(tableName)
	_agentCardSurface.ID = field.NewString(tableName, "id")
	_agentCardSurface.RunID = field.NewString(tableName, "run_id")
	_agentCardSurface.WaitStepID = field.NewString(tableName, "wait_step_id")
	_agentCardSurface.InteractionID = field.NewString(tableName, "interaction_id")
	_agentCardSurface.ChatID = field.NewString(tableName, "chat_id")
	_agentCardSurface.ReplyToMessageID = field.NewString(tableName, "reply_to_message_id")
	_agentCardSurface.MessageID = field.NewString(tableName, "message_id")
	_agentCardSurface.SpecVersion = field.NewString(tableName, "spec_version")
	_agentCardSurface.SpecJSON = field.NewString(tableName, "spec_json")
	_agentCardSurface.CompiledJSONRedacted = field.NewString(tableName, "compiled_json_redacted")
	_agentCardSurface.Status = field.NewString(tableName, "status")
	_agentCardSurface.Revision = field.NewInt64(tableName, "revision")
	_agentCardSurface.ExpectedActorOpenID = field.NewString(tableName, "expected_actor_open_id")
	_agentCardSurface.InteractionKind = field.NewString(tableName, "interaction_kind")
	_agentCardSurface.ExpiresAt = field.NewTime(tableName, "expires_at")
	_agentCardSurface.SubmittedAt = field.NewTime(tableName, "submitted_at")
	_agentCardSurface.ProcessingAt = field.NewTime(tableName, "processing_at")
	_agentCardSurface.ResolvedAt = field.NewTime(tableName, "resolved_at")
	_agentCardSurface.CancelledAt = field.NewTime(tableName, "cancelled_at")
	_agentCardSurface.FailedAt = field.NewTime(tableName, "failed_at")
	_agentCardSurface.LastActionID = field.NewString(tableName, "last_action_id")
	_agentCardSurface.LastSourceRef = field.NewString(tableName, "last_source_ref")
	_agentCardSurface.PatchStatus = field.NewString(tableName, "patch_status")
	_agentCardSurface.PatchAttemptCount = field.NewInt32(tableName, "patch_attempt_count")
	_agentCardSurface.NextPatchAt = field.NewTime(tableName, "next_patch_at")
	_agentCardSurface.PatchWorkerID = field.NewString(tableName, "patch_worker_id")
	_agentCardSurface.PatchLeaseExpiresAt = field.NewTime(tableName, "patch_lease_expires_at")
	_agentCardSurface.LastError = field.NewString(tableName, "last_error")
	_agentCardSurface.CreatedAt = field.NewTime(tableName, "created_at")
	_agentCardSurface.UpdatedAt = field.NewTime(tableName, "updated_at")
	_agentCardSurface.TenantID = field.NewString(tableName, "tenant_id")

	_agentCardSurface.fillFieldMap()

	return _agentCardSurface
}

type agentCardSurface struct {
	agentCardSurfaceDo agentCardSurfaceDo

	ALL                  field.Asterisk
	ID                   field.String
	RunID                field.String
	WaitStepID           field.String
	InteractionID        field.String
	ChatID               field.String
	ReplyToMessageID     field.String
	MessageID            field.String
	SpecVersion          field.String
	SpecJSON             field.String
	CompiledJSONRedacted field.String
	Status               field.String
	Revision             field.Int64
	ExpectedActorOpenID  field.String
	InteractionKind      field.String
	ExpiresAt            field.Time
	SubmittedAt          field.Time
	ProcessingAt         field.Time
	ResolvedAt           field.Time
	CancelledAt          field.Time
	FailedAt             field.Time
	LastActionID         field.String
	LastSourceRef        field.String
	PatchStatus          field.String
	PatchAttemptCount    field.Int32
	NextPatchAt          field.Time
	PatchWorkerID        field.String
	PatchLeaseExpiresAt  field.Time
	LastError            field.String
	CreatedAt            field.Time
	UpdatedAt            field.Time
	TenantID             field.String

	fieldMap map[string]field.Expr
}

func (a agentCardSurface) Table(newTableName string) *agentCardSurface {
	a.agentCardSurfaceDo.UseTable(newTableName)
	return a.updateTableName(newTableName)
}

func (a agentCardSurface) As(alias string) *agentCardSurface {
	a.agentCardSurfaceDo.DO = *(a.agentCardSurfaceDo.As(alias).(*gen.DO))
	return a.updateTableName(alias)
}

func (a *agentCardSurface) updateTableName(table string) *agentCardSurface {
	a.ALL = field.NewAsterisk(table)
	a.ID = field.NewString(table, "id")
	a.RunID = field.NewString(table, "run_id")
	a.WaitStepID = field.NewString(table, "wait_step_id")
	a.InteractionID = field.NewString(table, "interaction_id")
	a.ChatID = field.NewString(table, "chat_id")
	a.ReplyToMessageID = field.NewString(table, "reply_to_message_id")
	a.MessageID = field.NewString(table, "message_id")
	a.SpecVersion = field.NewString(table, "spec_version")
	a.SpecJSON = field.NewString(table, "spec_json")
	a.CompiledJSONRedacted = field.NewString(table, "compiled_json_redacted")
	a.Status = field.NewString(table, "status")
	a.Revision = field.NewInt64(table, "revision")
	a.ExpectedActorOpenID = field.NewString(table, "expected_actor_open_id")
	a.InteractionKind = field.NewString(table, "interaction_kind")
	a.ExpiresAt = field.NewTime(table, "expires_at")
	a.SubmittedAt = field.NewTime(table, "submitted_at")
	a.ProcessingAt = field.NewTime(table, "processing_at")
	a.ResolvedAt = field.NewTime(table, "resolved_at")
	a.CancelledAt = field.NewTime(table, "cancelled_at")
	a.FailedAt = field.NewTime(table, "failed_at")
	a.LastActionID = field.NewString(table, "last_action_id")
	a.LastSourceRef = field.NewString(table, "last_source_ref")
	a.PatchStatus = field.NewString(table, "patch_status")
	a.PatchAttemptCount = field.NewInt32(table, "patch_attempt_count")
	a.NextPatchAt = field.NewTime(table, "next_patch_at")
	a.PatchWorkerID = field.NewString(table, "patch_worker_id")
	a.PatchLeaseExpiresAt = field.NewTime(table, "patch_lease_expires_at")
	a.LastError = field.NewString(table, "last_error")
	a.CreatedAt = field.NewTime(table, "created_at")
	a.UpdatedAt = field.NewTime(table, "updated_at")
	a.TenantID = field.NewString(table, "tenant_id")

	a.fillFieldMap()

	return a
}

func (a *agentCardSurface) WithContext(ctx context.Context) IAgentCardSurfaceDo {
	return a.agentCardSurfaceDo.WithContext(ctx)
}

func (a agentCardSurface) TableName() string { return a.agentCardSurfaceDo.TableName() }

func (a agentCardSurface) Alias() string { return a.agentCardSurfaceDo.Alias() }

func (a agentCardSurface) Columns(cols ...field.Expr) gen.Columns {
	return a.agentCardSurfaceDo.Columns(cols...)
}

func (a *agentCardSurface) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := a.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (a *agentCardSurface) fillFieldMap() {
	a.fieldMap = make(map[string]field.Expr, 31)
	a.fieldMap["id"] = a.ID
	a.fieldMap["run_id"] = a.RunID
	a.fieldMap["wait_step_id"] = a.WaitStepID
	a.fieldMap["interaction_id"] = a.InteractionID
	a.fieldMap["chat_id"] = a.ChatID
	a.fieldMap["reply_to_message_id"] = a.ReplyToMessageID
	a.fieldMap["message_id"] = a.MessageID
	a.fieldMap["spec_version"] = a.SpecVersion
	a.fieldMap["spec_json"] = a.SpecJSON
	a.fieldMap["compiled_json_redacted"] = a.CompiledJSONRedacted
	a.fieldMap["status"] = a.Status
	a.fieldMap["revision"] = a.Revision
	a.fieldMap["expected_actor_open_id"] = a.ExpectedActorOpenID
	a.fieldMap["interaction_kind"] = a.InteractionKind
	a.fieldMap["expires_at"] = a.ExpiresAt
	a.fieldMap["submitted_at"] = a.SubmittedAt
	a.fieldMap["processing_at"] = a.ProcessingAt
	a.fieldMap["resolved_at"] = a.ResolvedAt
	a.fieldMap["cancelled_at"] = a.CancelledAt
	a.fieldMap["failed_at"] = a.FailedAt
	a.fieldMap["last_action_id"] = a.LastActionID
	a.fieldMap["last_source_ref"] = a.LastSourceRef
	a.fieldMap["patch_status"] = a.PatchStatus
	a.fieldMap["patch_attempt_count"] = a.PatchAttemptCount
	a.fieldMap["next_patch_at"] = a.NextPatchAt
	a.fieldMap["patch_worker_id"] = a.PatchWorkerID
	a.fieldMap["patch_lease_expires_at"] = a.PatchLeaseExpiresAt
	a.fieldMap["last_error"] = a.LastError
	a.fieldMap["created_at"] = a.CreatedAt
	a.fieldMap["updated_at"] = a.UpdatedAt
	a.fieldMap["tenant_id"] = a.TenantID
}

func (a agentCardSurface) clone(db *gorm.DB) agentCardSurface {
	a.agentCardSurfaceDo.ReplaceConnPool(db.Statement.ConnPool)
	return a
}

func (a agentCardSurface) replaceDB(db *gorm.DB) agentCardSurface {
	a.agentCardSurfaceDo.ReplaceDB(db)
	return a
}

type agentCardSurfaceDo struct {
	gen.GenericsDo[IAgentCardSurfaceDo, *model.AgentCardSurface]
}
type IAgentCardSurfaceDo interface {
	gen.IGenericsDo[IAgentCardSurfaceDo, *model.AgentCardSurface]
}

func (a *agentCardSurfaceDo) withDO(do gen.Dao) IAgentCardSurfaceDo {
	_r := &agentCardSurfaceDo{}
	_r.DO = *do.(*gen.DO)
	_r.IWithDO = gen.WithDOFunc[IAgentCardSurfaceDo](a.withDO)
	return _r
}
