// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"github.com/BetaGoRobot/BetaGo-Redefine/internal/infrastructure/db/model"
)

func newAgentRun(db *gorm.DB, opts ...gen.DOOption) agentRun {
	_agentRun := agentRun{}

	_agentRun.agentRunDo.IWithDO = gen.WithDOFunc[IAgentRunDo](_agentRun.agentRunDo.withDO)

	_agentRun.agentRunDo.UseDB(db, opts...)
	_agentRun.agentRunDo.UseModel(&model.AgentRun{})

	tableName := _agentRun.agentRunDo.TableName()
	_agentRun.ALL = field.NewAsterisk(tableName)
	_agentRun.ID = field.NewString(tableName, "id")
	_agentRun.SessionID = field.NewString(tableName, "session_id")
	_agentRun.TriggerType = field.NewString(tableName, "trigger_type")
	_agentRun.TriggerMessageID = field.NewString(tableName, "trigger_message_id")
	_agentRun.TriggerEventID = field.NewString(tableName, "trigger_event_id")
	_agentRun.ActorOpenID = field.NewString(tableName, "actor_open_id")
	_agentRun.ParentRunID = field.NewString(tableName, "parent_run_id")
	_agentRun.Status = field.NewString(tableName, "status")
	_agentRun.Goal = field.NewString(tableName, "goal")
	_agentRun.InputText = field.NewString(tableName, "input_text")
	_agentRun.CurrentStepIndex = field.NewInt32(tableName, "current_step_index")
	_agentRun.WaitingReason = field.NewString(tableName, "waiting_reason")
	_agentRun.WaitingToken = field.NewString(tableName, "waiting_token")
	_agentRun.LastResponseID = field.NewString(tableName, "last_response_id")
	_agentRun.ResultSummary = field.NewString(tableName, "result_summary")
	_agentRun.ErrorText = field.NewString(tableName, "error_text")
	_agentRun.Revision = field.NewInt64(tableName, "revision")
	_agentRun.StartedAt = field.NewTime(tableName, "started_at")
	_agentRun.FinishedAt = field.NewTime(tableName, "finished_at")
	_agentRun.CreatedAt = field.NewTime(tableName, "created_at")
	_agentRun.UpdatedAt = field.NewTime(tableName, "updated_at")

	_agentRun.fillFieldMap()

	return _agentRun
}

type agentRun struct {
	agentRunDo agentRunDo

	ALL              field.Asterisk
	ID               field.String
	SessionID        field.String
	TriggerType      field.String
	TriggerMessageID field.String
	TriggerEventID   field.String
	ActorOpenID      field.String
	ParentRunID      field.String
	Status           field.String
	Goal             field.String
	InputText        field.String
	CurrentStepIndex field.Int32
	WaitingReason    field.String
	WaitingToken     field.String
	LastResponseID   field.String
	ResultSummary    field.String
	ErrorText        field.String
	Revision         field.Int64
	StartedAt        field.Time
	FinishedAt       field.Time
	CreatedAt        field.Time
	UpdatedAt        field.Time

	fieldMap map[string]field.Expr
}

func (a agentRun) Table(newTableName string) *agentRun {
	a.agentRunDo.UseTable(newTableName)
	return a.updateTableName(newTableName)
}

func (a agentRun) As(alias string) *agentRun {
	a.agentRunDo.DO = *(a.agentRunDo.As(alias).(*gen.DO))
	return a.updateTableName(alias)
}

func (a *agentRun) updateTableName(table string) *agentRun {
	a.ALL = field.NewAsterisk(table)
	a.ID = field.NewString(table, "id")
	a.SessionID = field.NewString(table, "session_id")
	a.TriggerType = field.NewString(table, "trigger_type")
	a.TriggerMessageID = field.NewString(table, "trigger_message_id")
	a.TriggerEventID = field.NewString(table, "trigger_event_id")
	a.ActorOpenID = field.NewString(table, "actor_open_id")
	a.ParentRunID = field.NewString(table, "parent_run_id")
	a.Status = field.NewString(table, "status")
	a.Goal = field.NewString(table, "goal")
	a.InputText = field.NewString(table, "input_text")
	a.CurrentStepIndex = field.NewInt32(table, "current_step_index")
	a.WaitingReason = field.NewString(table, "waiting_reason")
	a.WaitingToken = field.NewString(table, "waiting_token")
	a.LastResponseID = field.NewString(table, "last_response_id")
	a.ResultSummary = field.NewString(table, "result_summary")
	a.ErrorText = field.NewString(table, "error_text")
	a.Revision = field.NewInt64(table, "revision")
	a.StartedAt = field.NewTime(table, "started_at")
	a.FinishedAt = field.NewTime(table, "finished_at")
	a.CreatedAt = field.NewTime(table, "created_at")
	a.UpdatedAt = field.NewTime(table, "updated_at")

	a.fillFieldMap()

	return a
}

func (a *agentRun) WithContext(ctx context.Context) IAgentRunDo { return a.agentRunDo.WithContext(ctx) }

func (a agentRun) TableName() string { return a.agentRunDo.TableName() }

func (a agentRun) Alias() string { return a.agentRunDo.Alias() }

func (a agentRun) Columns(cols ...field.Expr) gen.Columns { return a.agentRunDo.Columns(cols...) }

func (a *agentRun) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := a.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (a *agentRun) fillFieldMap() {
	a.fieldMap = make(map[string]field.Expr, 21)
	a.fieldMap["id"] = a.ID
	a.fieldMap["session_id"] = a.SessionID
	a.fieldMap["trigger_type"] = a.TriggerType
	a.fieldMap["trigger_message_id"] = a.TriggerMessageID
	a.fieldMap["trigger_event_id"] = a.TriggerEventID
	a.fieldMap["actor_open_id"] = a.ActorOpenID
	a.fieldMap["parent_run_id"] = a.ParentRunID
	a.fieldMap["status"] = a.Status
	a.fieldMap["goal"] = a.Goal
	a.fieldMap["input_text"] = a.InputText
	a.fieldMap["current_step_index"] = a.CurrentStepIndex
	a.fieldMap["waiting_reason"] = a.WaitingReason
	a.fieldMap["waiting_token"] = a.WaitingToken
	a.fieldMap["last_response_id"] = a.LastResponseID
	a.fieldMap["result_summary"] = a.ResultSummary
	a.fieldMap["error_text"] = a.ErrorText
	a.fieldMap["revision"] = a.Revision
	a.fieldMap["started_at"] = a.StartedAt
	a.fieldMap["finished_at"] = a.FinishedAt
	a.fieldMap["created_at"] = a.CreatedAt
	a.fieldMap["updated_at"] = a.UpdatedAt
}

func (a agentRun) clone(db *gorm.DB) agentRun {
	a.agentRunDo.ReplaceConnPool(db.Statement.ConnPool)
	return a
}

func (a agentRun) replaceDB(db *gorm.DB) agentRun {
	a.agentRunDo.ReplaceDB(db)
	return a
}

type agentRunDo struct {
	gen.GenericsDo[IAgentRunDo, *model.AgentRun]
}
type IAgentRunDo interface {
	gen.IGenericsDo[IAgentRunDo, *model.AgentRun]
}

func (a *agentRunDo) withDO(do gen.Dao) IAgentRunDo {
	_r := &agentRunDo{}
	_r.DO = *do.(*gen.DO)
	_r.IWithDO = gen.WithDOFunc[IAgentRunDo](a.withDO)
	return _r
}
