// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"github.com/BetaGoRobot/BetaGo-Redefine/internal/infrastructure/db/model"
)

func newAgentProjectionOutbox(db *gorm.DB, opts ...gen.DOOption) agentProjectionOutbox {
	_agentProjectionOutbox := agentProjectionOutbox{}

	_agentProjectionOutbox.agentProjectionOutboxDo.IWithDO = gen.WithDOFunc[IAgentProjectionOutboxDo](_agentProjectionOutbox.agentProjectionOutboxDo.withDO)

	_agentProjectionOutbox.agentProjectionOutboxDo.UseDB(db, opts...)
	_agentProjectionOutbox.agentProjectionOutboxDo.UseModel(&model.AgentProjectionOutbox{})

	tableName := _agentProjectionOutbox.agentProjectionOutboxDo.TableName()
	_agentProjectionOutbox.ALL = field.NewAsterisk(tableName)
	_agentProjectionOutbox.ID = field.NewString(tableName, "id")
	_agentProjectionOutbox.StepID = field.NewString(tableName, "step_id")
	_agentProjectionOutbox.IndexAlias = field.NewString(tableName, "index_alias")
	_agentProjectionOutbox.DocumentID = field.NewString(tableName, "document_id")
	_agentProjectionOutbox.PayloadJSON = field.NewString(tableName, "payload_json")
	_agentProjectionOutbox.Status = field.NewString(tableName, "status")
	_agentProjectionOutbox.AttemptCount = field.NewInt32(tableName, "attempt_count")
	_agentProjectionOutbox.NextAttemptAt = field.NewTime(tableName, "next_attempt_at")
	_agentProjectionOutbox.WorkerID = field.NewString(tableName, "worker_id")
	_agentProjectionOutbox.LeaseExpiresAt = field.NewTime(tableName, "lease_expires_at")
	_agentProjectionOutbox.LastError = field.NewString(tableName, "last_error")
	_agentProjectionOutbox.CreatedAt = field.NewTime(tableName, "created_at")
	_agentProjectionOutbox.UpdatedAt = field.NewTime(tableName, "updated_at")
	_agentProjectionOutbox.TenantID = field.NewString(tableName, "tenant_id")

	_agentProjectionOutbox.fillFieldMap()

	return _agentProjectionOutbox
}

type agentProjectionOutbox struct {
	agentProjectionOutboxDo agentProjectionOutboxDo

	ALL            field.Asterisk
	ID             field.String
	StepID         field.String
	IndexAlias     field.String
	DocumentID     field.String
	PayloadJSON    field.String
	Status         field.String
	AttemptCount   field.Int32
	NextAttemptAt  field.Time
	WorkerID       field.String
	LeaseExpiresAt field.Time
	LastError      field.String
	CreatedAt      field.Time
	UpdatedAt      field.Time
	TenantID       field.String

	fieldMap map[string]field.Expr
}

func (a agentProjectionOutbox) Table(newTableName string) *agentProjectionOutbox {
	a.agentProjectionOutboxDo.UseTable(newTableName)
	return a.updateTableName(newTableName)
}

func (a agentProjectionOutbox) As(alias string) *agentProjectionOutbox {
	a.agentProjectionOutboxDo.DO = *(a.agentProjectionOutboxDo.As(alias).(*gen.DO))
	return a.updateTableName(alias)
}

func (a *agentProjectionOutbox) updateTableName(table string) *agentProjectionOutbox {
	a.ALL = field.NewAsterisk(table)
	a.ID = field.NewString(table, "id")
	a.StepID = field.NewString(table, "step_id")
	a.IndexAlias = field.NewString(table, "index_alias")
	a.DocumentID = field.NewString(table, "document_id")
	a.PayloadJSON = field.NewString(table, "payload_json")
	a.Status = field.NewString(table, "status")
	a.AttemptCount = field.NewInt32(table, "attempt_count")
	a.NextAttemptAt = field.NewTime(table, "next_attempt_at")
	a.WorkerID = field.NewString(table, "worker_id")
	a.LeaseExpiresAt = field.NewTime(table, "lease_expires_at")
	a.LastError = field.NewString(table, "last_error")
	a.CreatedAt = field.NewTime(table, "created_at")
	a.UpdatedAt = field.NewTime(table, "updated_at")
	a.TenantID = field.NewString(table, "tenant_id")

	a.fillFieldMap()

	return a
}

func (a *agentProjectionOutbox) WithContext(ctx context.Context) IAgentProjectionOutboxDo {
	return a.agentProjectionOutboxDo.WithContext(ctx)
}

func (a agentProjectionOutbox) TableName() string { return a.agentProjectionOutboxDo.TableName() }

func (a agentProjectionOutbox) Alias() string { return a.agentProjectionOutboxDo.Alias() }

func (a agentProjectionOutbox) Columns(cols ...field.Expr) gen.Columns {
	return a.agentProjectionOutboxDo.Columns(cols...)
}

func (a *agentProjectionOutbox) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := a.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (a *agentProjectionOutbox) fillFieldMap() {
	a.fieldMap = make(map[string]field.Expr, 14)
	a.fieldMap["id"] = a.ID
	a.fieldMap["step_id"] = a.StepID
	a.fieldMap["index_alias"] = a.IndexAlias
	a.fieldMap["document_id"] = a.DocumentID
	a.fieldMap["payload_json"] = a.PayloadJSON
	a.fieldMap["status"] = a.Status
	a.fieldMap["attempt_count"] = a.AttemptCount
	a.fieldMap["next_attempt_at"] = a.NextAttemptAt
	a.fieldMap["worker_id"] = a.WorkerID
	a.fieldMap["lease_expires_at"] = a.LeaseExpiresAt
	a.fieldMap["last_error"] = a.LastError
	a.fieldMap["created_at"] = a.CreatedAt
	a.fieldMap["updated_at"] = a.UpdatedAt
	a.fieldMap["tenant_id"] = a.TenantID
}

func (a agentProjectionOutbox) clone(db *gorm.DB) agentProjectionOutbox {
	a.agentProjectionOutboxDo.ReplaceConnPool(db.Statement.ConnPool)
	return a
}

func (a agentProjectionOutbox) replaceDB(db *gorm.DB) agentProjectionOutbox {
	a.agentProjectionOutboxDo.ReplaceDB(db)
	return a
}

type agentProjectionOutboxDo struct {
	gen.GenericsDo[IAgentProjectionOutboxDo, *model.AgentProjectionOutbox]
}
type IAgentProjectionOutboxDo interface {
	gen.IGenericsDo[IAgentProjectionOutboxDo, *model.AgentProjectionOutbox]
}

func (a *agentProjectionOutboxDo) withDO(do gen.Dao) IAgentProjectionOutboxDo {
	_r := &agentProjectionOutboxDo{}
	_r.DO = *do.(*gen.DO)
	_r.IWithDO = gen.WithDOFunc[IAgentProjectionOutboxDo](a.withDO)
	return _r
}
