// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"github.com/BetaGoRobot/BetaGo-Redefine/internal/infrastructure/db/model"
)

func newAgentSession(db *gorm.DB, opts ...gen.DOOption) agentSession {
	_agentSession := agentSession{}

	_agentSession.agentSessionDo.IWithDO = gen.WithDOFunc[IAgentSessionDo](_agentSession.agentSessionDo.withDO)

	_agentSession.agentSessionDo.UseDB(db, opts...)
	_agentSession.agentSessionDo.UseModel(&model.AgentSession{})

	tableName := _agentSession.agentSessionDo.TableName()
	_agentSession.ALL = field.NewAsterisk(tableName)
	_agentSession.ID = field.NewString(tableName, "id")
	_agentSession.AppID = field.NewString(tableName, "app_id")
	_agentSession.BotOpenID = field.NewString(tableName, "bot_open_id")
	_agentSession.ChatID = field.NewString(tableName, "chat_id")
	_agentSession.ScopeType = field.NewString(tableName, "scope_type")
	_agentSession.ScopeID = field.NewString(tableName, "scope_id")
	_agentSession.Status = field.NewString(tableName, "status")
	_agentSession.ActiveRunID = field.NewString(tableName, "active_run_id")
	_agentSession.LastMessageID = field.NewString(tableName, "last_message_id")
	_agentSession.LastActorOpenID = field.NewString(tableName, "last_actor_open_id")
	_agentSession.MemoryVersion = field.NewInt64(tableName, "memory_version")
	_agentSession.CreatedAt = field.NewTime(tableName, "created_at")
	_agentSession.UpdatedAt = field.NewTime(tableName, "updated_at")

	_agentSession.fillFieldMap()

	return _agentSession
}

type agentSession struct {
	agentSessionDo agentSessionDo

	ALL             field.Asterisk
	ID              field.String
	AppID           field.String
	BotOpenID       field.String
	ChatID          field.String
	ScopeType       field.String
	ScopeID         field.String
	Status          field.String
	ActiveRunID     field.String
	LastMessageID   field.String
	LastActorOpenID field.String
	MemoryVersion   field.Int64
	CreatedAt       field.Time
	UpdatedAt       field.Time

	fieldMap map[string]field.Expr
}

func (a agentSession) Table(newTableName string) *agentSession {
	a.agentSessionDo.UseTable(newTableName)
	return a.updateTableName(newTableName)
}

func (a agentSession) As(alias string) *agentSession {
	a.agentSessionDo.DO = *(a.agentSessionDo.As(alias).(*gen.DO))
	return a.updateTableName(alias)
}

func (a *agentSession) updateTableName(table string) *agentSession {
	a.ALL = field.NewAsterisk(table)
	a.ID = field.NewString(table, "id")
	a.AppID = field.NewString(table, "app_id")
	a.BotOpenID = field.NewString(table, "bot_open_id")
	a.ChatID = field.NewString(table, "chat_id")
	a.ScopeType = field.NewString(table, "scope_type")
	a.ScopeID = field.NewString(table, "scope_id")
	a.Status = field.NewString(table, "status")
	a.ActiveRunID = field.NewString(table, "active_run_id")
	a.LastMessageID = field.NewString(table, "last_message_id")
	a.LastActorOpenID = field.NewString(table, "last_actor_open_id")
	a.MemoryVersion = field.NewInt64(table, "memory_version")
	a.CreatedAt = field.NewTime(table, "created_at")
	a.UpdatedAt = field.NewTime(table, "updated_at")

	a.fillFieldMap()

	return a
}

func (a *agentSession) WithContext(ctx context.Context) IAgentSessionDo {
	return a.agentSessionDo.WithContext(ctx)
}

func (a agentSession) TableName() string { return a.agentSessionDo.TableName() }

func (a agentSession) Alias() string { return a.agentSessionDo.Alias() }

func (a agentSession) Columns(cols ...field.Expr) gen.Columns {
	return a.agentSessionDo.Columns(cols...)
}

func (a *agentSession) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := a.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (a *agentSession) fillFieldMap() {
	a.fieldMap = make(map[string]field.Expr, 13)
	a.fieldMap["id"] = a.ID
	a.fieldMap["app_id"] = a.AppID
	a.fieldMap["bot_open_id"] = a.BotOpenID
	a.fieldMap["chat_id"] = a.ChatID
	a.fieldMap["scope_type"] = a.ScopeType
	a.fieldMap["scope_id"] = a.ScopeID
	a.fieldMap["status"] = a.Status
	a.fieldMap["active_run_id"] = a.ActiveRunID
	a.fieldMap["last_message_id"] = a.LastMessageID
	a.fieldMap["last_actor_open_id"] = a.LastActorOpenID
	a.fieldMap["memory_version"] = a.MemoryVersion
	a.fieldMap["created_at"] = a.CreatedAt
	a.fieldMap["updated_at"] = a.UpdatedAt
}

func (a agentSession) clone(db *gorm.DB) agentSession {
	a.agentSessionDo.ReplaceConnPool(db.Statement.ConnPool)
	return a
}

func (a agentSession) replaceDB(db *gorm.DB) agentSession {
	a.agentSessionDo.ReplaceDB(db)
	return a
}

type agentSessionDo struct {
	gen.GenericsDo[IAgentSessionDo, *model.AgentSession]
}
type IAgentSessionDo interface {
	gen.IGenericsDo[IAgentSessionDo, *model.AgentSession]
}

func (a *agentSessionDo) withDO(do gen.Dao) IAgentSessionDo {
	_r := &agentSessionDo{}
	_r.DO = *do.(*gen.DO)
	_r.IWithDO = gen.WithDOFunc[IAgentSessionDo](a.withDO)
	return _r
}
