// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"github.com/BetaGoRobot/BetaGo-Redefine/internal/infrastructure/db/model"
)

func newAgentCapabilityExecution(db *gorm.DB, opts ...gen.DOOption) agentCapabilityExecution {
	_agentCapabilityExecution := agentCapabilityExecution{}

	_agentCapabilityExecution.agentCapabilityExecutionDo.IWithDO = gen.WithDOFunc[IAgentCapabilityExecutionDo](_agentCapabilityExecution.agentCapabilityExecutionDo.withDO)

	_agentCapabilityExecution.agentCapabilityExecutionDo.UseDB(db, opts...)
	_agentCapabilityExecution.agentCapabilityExecutionDo.UseModel(&model.AgentCapabilityExecution{})

	tableName := _agentCapabilityExecution.agentCapabilityExecutionDo.TableName()
	_agentCapabilityExecution.ALL = field.NewAsterisk(tableName)
	_agentCapabilityExecution.IdempotencyKey = field.NewString(tableName, "idempotency_key")
	_agentCapabilityExecution.RunID = field.NewString(tableName, "run_id")
	_agentCapabilityExecution.StepID = field.NewString(tableName, "step_id")
	_agentCapabilityExecution.CapabilityName = field.NewString(tableName, "capability_name")
	_agentCapabilityExecution.Status = field.NewString(tableName, "status")
	_agentCapabilityExecution.InputJSON = field.NewString(tableName, "input_json")
	_agentCapabilityExecution.OutputJSON = field.NewString(tableName, "output_json")
	_agentCapabilityExecution.ErrorText = field.NewString(tableName, "error_text")
	_agentCapabilityExecution.StartedAt = field.NewTime(tableName, "started_at")
	_agentCapabilityExecution.FinishedAt = field.NewTime(tableName, "finished_at")
	_agentCapabilityExecution.CreatedAt = field.NewTime(tableName, "created_at")
	_agentCapabilityExecution.UpdatedAt = field.NewTime(tableName, "updated_at")

	_agentCapabilityExecution.fillFieldMap()

	return _agentCapabilityExecution
}

type agentCapabilityExecution struct {
	agentCapabilityExecutionDo agentCapabilityExecutionDo

	ALL            field.Asterisk
	IdempotencyKey field.String
	RunID          field.String
	StepID         field.String
	CapabilityName field.String
	Status         field.String
	InputJSON      field.String
	OutputJSON     field.String
	ErrorText      field.String
	StartedAt      field.Time
	FinishedAt     field.Time
	CreatedAt      field.Time
	UpdatedAt      field.Time

	fieldMap map[string]field.Expr
}

func (a agentCapabilityExecution) Table(newTableName string) *agentCapabilityExecution {
	a.agentCapabilityExecutionDo.UseTable(newTableName)
	return a.updateTableName(newTableName)
}

func (a agentCapabilityExecution) As(alias string) *agentCapabilityExecution {
	a.agentCapabilityExecutionDo.DO = *(a.agentCapabilityExecutionDo.As(alias).(*gen.DO))
	return a.updateTableName(alias)
}

func (a *agentCapabilityExecution) updateTableName(table string) *agentCapabilityExecution {
	a.ALL = field.NewAsterisk(table)
	a.IdempotencyKey = field.NewString(table, "idempotency_key")
	a.RunID = field.NewString(table, "run_id")
	a.StepID = field.NewString(table, "step_id")
	a.CapabilityName = field.NewString(table, "capability_name")
	a.Status = field.NewString(table, "status")
	a.InputJSON = field.NewString(table, "input_json")
	a.OutputJSON = field.NewString(table, "output_json")
	a.ErrorText = field.NewString(table, "error_text")
	a.StartedAt = field.NewTime(table, "started_at")
	a.FinishedAt = field.NewTime(table, "finished_at")
	a.CreatedAt = field.NewTime(table, "created_at")
	a.UpdatedAt = field.NewTime(table, "updated_at")

	a.fillFieldMap()

	return a
}

func (a *agentCapabilityExecution) WithContext(ctx context.Context) IAgentCapabilityExecutionDo {
	return a.agentCapabilityExecutionDo.WithContext(ctx)
}

func (a agentCapabilityExecution) TableName() string { return a.agentCapabilityExecutionDo.TableName() }

func (a agentCapabilityExecution) Alias() string { return a.agentCapabilityExecutionDo.Alias() }

func (a agentCapabilityExecution) Columns(cols ...field.Expr) gen.Columns {
	return a.agentCapabilityExecutionDo.Columns(cols...)
}

func (a *agentCapabilityExecution) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := a.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (a *agentCapabilityExecution) fillFieldMap() {
	a.fieldMap = make(map[string]field.Expr, 12)
	a.fieldMap["idempotency_key"] = a.IdempotencyKey
	a.fieldMap["run_id"] = a.RunID
	a.fieldMap["step_id"] = a.StepID
	a.fieldMap["capability_name"] = a.CapabilityName
	a.fieldMap["status"] = a.Status
	a.fieldMap["input_json"] = a.InputJSON
	a.fieldMap["output_json"] = a.OutputJSON
	a.fieldMap["error_text"] = a.ErrorText
	a.fieldMap["started_at"] = a.StartedAt
	a.fieldMap["finished_at"] = a.FinishedAt
	a.fieldMap["created_at"] = a.CreatedAt
	a.fieldMap["updated_at"] = a.UpdatedAt
}

func (a agentCapabilityExecution) clone(db *gorm.DB) agentCapabilityExecution {
	a.agentCapabilityExecutionDo.ReplaceConnPool(db.Statement.ConnPool)
	return a
}

func (a agentCapabilityExecution) replaceDB(db *gorm.DB) agentCapabilityExecution {
	a.agentCapabilityExecutionDo.ReplaceDB(db)
	return a
}

type agentCapabilityExecutionDo struct {
	gen.GenericsDo[IAgentCapabilityExecutionDo, *model.AgentCapabilityExecution]
}
type IAgentCapabilityExecutionDo interface {
	gen.IGenericsDo[IAgentCapabilityExecutionDo, *model.AgentCapabilityExecution]
}

func (a *agentCapabilityExecutionDo) withDO(do gen.Dao) IAgentCapabilityExecutionDo {
	_r := &agentCapabilityExecutionDo{}
	_r.DO = *do.(*gen.DO)
	_r.IWithDO = gen.WithDOFunc[IAgentCapabilityExecutionDo](a.withDO)
	return _r
}
