// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"github.com/BetaGoRobot/BetaGo-Redefine/internal/infrastructure/db/model"
)

func newAlertList(db *gorm.DB, opts ...gen.DOOption) alertList {
	_alertList := alertList{}

	_alertList.alertListDo.IWithDO = gen.WithDOFunc[IAlertListDo](_alertList.alertListDo.withDO)

	_alertList.alertListDo.UseDB(db, opts...)
	_alertList.alertListDo.UseModel(&model.AlertList{})

	tableName := _alertList.alertListDo.TableName()
	_alertList.ALL = field.NewAsterisk(tableName)
	_alertList.EmailAddress = field.NewString(tableName, "email_address")

	_alertList.fillFieldMap()

	return _alertList
}

type alertList struct {
	alertListDo alertListDo

	ALL          field.Asterisk
	EmailAddress field.String

	fieldMap map[string]field.Expr
}

func (a alertList) Table(newTableName string) *alertList {
	a.alertListDo.UseTable(newTableName)
	return a.updateTableName(newTableName)
}

func (a alertList) As(alias string) *alertList {
	a.alertListDo.DO = *(a.alertListDo.As(alias).(*gen.DO))
	return a.updateTableName(alias)
}

func (a *alertList) updateTableName(table string) *alertList {
	a.ALL = field.NewAsterisk(table)
	a.EmailAddress = field.NewString(table, "email_address")

	a.fillFieldMap()

	return a
}

func (a *alertList) WithContext(ctx context.Context) IAlertListDo {
	return a.alertListDo.WithContext(ctx)
}

func (a alertList) TableName() string { return a.alertListDo.TableName() }

func (a alertList) Alias() string { return a.alertListDo.Alias() }

func (a alertList) Columns(cols ...field.Expr) gen.Columns { return a.alertListDo.Columns(cols...) }

func (a *alertList) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := a.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (a *alertList) fillFieldMap() {
	a.fieldMap = make(map[string]field.Expr, 1)
	a.fieldMap["email_address"] = a.EmailAddress
}

func (a alertList) clone(db *gorm.DB) alertList {
	a.alertListDo.ReplaceConnPool(db.Statement.ConnPool)
	return a
}

func (a alertList) replaceDB(db *gorm.DB) alertList {
	a.alertListDo.ReplaceDB(db)
	return a
}

type alertListDo struct {
	gen.GenericsDo[IAlertListDo, *model.AlertList]
}
type IAlertListDo interface {
	gen.IGenericsDo[IAlertListDo, *model.AlertList]
}

func (a *alertListDo) withDO(do gen.Dao) IAlertListDo {
	_r := &alertListDo{}
	_r.DO = *do.(*gen.DO)
	_r.IWithDO = gen.WithDOFunc[IAlertListDo](a.withDO)
	return _r
}
