// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"github.com/BetaGoRobot/BetaGo-Redefine/internal/infrastructure/db/model"
)

func newCardActionRecordLog(db *gorm.DB, opts ...gen.DOOption) cardActionRecordLog {
	_cardActionRecordLog := cardActionRecordLog{}

	_cardActionRecordLog.cardActionRecordLogDo.IWithDO = gen.WithDOFunc[ICardActionRecordLogDo](_cardActionRecordLog.cardActionRecordLogDo.withDO)

	_cardActionRecordLog.cardActionRecordLogDo.UseDB(db, opts...)
	_cardActionRecordLog.cardActionRecordLogDo.UseModel(&model.CardActionRecordLog{})

	tableName := _cardActionRecordLog.cardActionRecordLogDo.TableName()
	_cardActionRecordLog.ALL = field.NewAsterisk(tableName)
	_cardActionRecordLog.UserID = field.NewString(tableName, "user_id")
	_cardActionRecordLog.UserName = field.NewString(tableName, "user_name")
	_cardActionRecordLog.EventSrc = field.NewString(tableName, "event_src")

	_cardActionRecordLog.fillFieldMap()

	return _cardActionRecordLog
}

type cardActionRecordLog struct {
	cardActionRecordLogDo cardActionRecordLogDo

	ALL      field.Asterisk
	UserID   field.String
	UserName field.String
	EventSrc field.String

	fieldMap map[string]field.Expr
}

func (c cardActionRecordLog) Table(newTableName string) *cardActionRecordLog {
	c.cardActionRecordLogDo.UseTable(newTableName)
	return c.updateTableName(newTableName)
}

func (c cardActionRecordLog) As(alias string) *cardActionRecordLog {
	c.cardActionRecordLogDo.DO = *(c.cardActionRecordLogDo.As(alias).(*gen.DO))
	return c.updateTableName(alias)
}

func (c *cardActionRecordLog) updateTableName(table string) *cardActionRecordLog {
	c.ALL = field.NewAsterisk(table)
	c.UserID = field.NewString(table, "user_id")
	c.UserName = field.NewString(table, "user_name")
	c.EventSrc = field.NewString(table, "event_src")

	c.fillFieldMap()

	return c
}

func (c *cardActionRecordLog) WithContext(ctx context.Context) ICardActionRecordLogDo {
	return c.cardActionRecordLogDo.WithContext(ctx)
}

func (c cardActionRecordLog) TableName() string { return c.cardActionRecordLogDo.TableName() }

func (c cardActionRecordLog) Alias() string { return c.cardActionRecordLogDo.Alias() }

func (c cardActionRecordLog) Columns(cols ...field.Expr) gen.Columns {
	return c.cardActionRecordLogDo.Columns(cols...)
}

func (c *cardActionRecordLog) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := c.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (c *cardActionRecordLog) fillFieldMap() {
	c.fieldMap = make(map[string]field.Expr, 3)
	c.fieldMap["user_id"] = c.UserID
	c.fieldMap["user_name"] = c.UserName
	c.fieldMap["event_src"] = c.EventSrc
}

func (c cardActionRecordLog) clone(db *gorm.DB) cardActionRecordLog {
	c.cardActionRecordLogDo.ReplaceConnPool(db.Statement.ConnPool)
	return c
}

func (c cardActionRecordLog) replaceDB(db *gorm.DB) cardActionRecordLog {
	c.cardActionRecordLogDo.ReplaceDB(db)
	return c
}

type cardActionRecordLogDo struct {
	gen.GenericsDo[ICardActionRecordLogDo, *model.CardActionRecordLog]
}
type ICardActionRecordLogDo interface {
	gen.IGenericsDo[ICardActionRecordLogDo, *model.CardActionRecordLog]
}

func (c *cardActionRecordLogDo) withDO(do gen.Dao) ICardActionRecordLogDo {
	_r := &cardActionRecordLogDo{}
	_r.DO = *do.(*gen.DO)
	_r.IWithDO = gen.WithDOFunc[ICardActionRecordLogDo](c.withDO)
	return _r
}
