// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"github.com/BetaGoRobot/BetaGo-Redefine/internal/infrastructure/db/model"
)

func newChannelLogExt(db *gorm.DB, opts ...gen.DOOption) channelLogExt {
	_channelLogExt := channelLogExt{}

	_channelLogExt.channelLogExtDo.IWithDO = gen.WithDOFunc[IChannelLogExtDo](_channelLogExt.channelLogExtDo.withDO)

	_channelLogExt.channelLogExtDo.UseDB(db, opts...)
	_channelLogExt.channelLogExtDo.UseModel(&model.ChannelLogExt{})

	tableName := _channelLogExt.channelLogExtDo.TableName()
	_channelLogExt.ALL = field.NewAsterisk(tableName)
	_channelLogExt.UserID = field.NewString(tableName, "user_id")
	_channelLogExt.UserName = field.NewString(tableName, "user_name")
	_channelLogExt.ChannelID = field.NewString(tableName, "channel_id")
	_channelLogExt.ChannelName = field.NewString(tableName, "channel_name")
	_channelLogExt.JoinedTime = field.NewString(tableName, "joined_time")
	_channelLogExt.LeftTime = field.NewString(tableName, "left_time")
	_channelLogExt.IsUpdate = field.NewBool(tableName, "is_update")
	_channelLogExt.MsgID = field.NewString(tableName, "msg_id")
	_channelLogExt.GuildID = field.NewString(tableName, "guild_id")

	_channelLogExt.fillFieldMap()

	return _channelLogExt
}

type channelLogExt struct {
	channelLogExtDo channelLogExtDo

	ALL         field.Asterisk
	UserID      field.String
	UserName    field.String
	ChannelID   field.String
	ChannelName field.String
	JoinedTime  field.String
	LeftTime    field.String
	IsUpdate    field.Bool
	MsgID       field.String
	GuildID     field.String

	fieldMap map[string]field.Expr
}

func (c channelLogExt) Table(newTableName string) *channelLogExt {
	c.channelLogExtDo.UseTable(newTableName)
	return c.updateTableName(newTableName)
}

func (c channelLogExt) As(alias string) *channelLogExt {
	c.channelLogExtDo.DO = *(c.channelLogExtDo.As(alias).(*gen.DO))
	return c.updateTableName(alias)
}

func (c *channelLogExt) updateTableName(table string) *channelLogExt {
	c.ALL = field.NewAsterisk(table)
	c.UserID = field.NewString(table, "user_id")
	c.UserName = field.NewString(table, "user_name")
	c.ChannelID = field.NewString(table, "channel_id")
	c.ChannelName = field.NewString(table, "channel_name")
	c.JoinedTime = field.NewString(table, "joined_time")
	c.LeftTime = field.NewString(table, "left_time")
	c.IsUpdate = field.NewBool(table, "is_update")
	c.MsgID = field.NewString(table, "msg_id")
	c.GuildID = field.NewString(table, "guild_id")

	c.fillFieldMap()

	return c
}

func (c *channelLogExt) WithContext(ctx context.Context) IChannelLogExtDo {
	return c.channelLogExtDo.WithContext(ctx)
}

func (c channelLogExt) TableName() string { return c.channelLogExtDo.TableName() }

func (c channelLogExt) Alias() string { return c.channelLogExtDo.Alias() }

func (c channelLogExt) Columns(cols ...field.Expr) gen.Columns {
	return c.channelLogExtDo.Columns(cols...)
}

func (c *channelLogExt) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := c.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (c *channelLogExt) fillFieldMap() {
	c.fieldMap = make(map[string]field.Expr, 9)
	c.fieldMap["user_id"] = c.UserID
	c.fieldMap["user_name"] = c.UserName
	c.fieldMap["channel_id"] = c.ChannelID
	c.fieldMap["channel_name"] = c.ChannelName
	c.fieldMap["joined_time"] = c.JoinedTime
	c.fieldMap["left_time"] = c.LeftTime
	c.fieldMap["is_update"] = c.IsUpdate
	c.fieldMap["msg_id"] = c.MsgID
	c.fieldMap["guild_id"] = c.GuildID
}

func (c channelLogExt) clone(db *gorm.DB) channelLogExt {
	c.channelLogExtDo.ReplaceConnPool(db.Statement.ConnPool)
	return c
}

func (c channelLogExt) replaceDB(db *gorm.DB) channelLogExt {
	c.channelLogExtDo.ReplaceDB(db)
	return c
}

type channelLogExtDo struct {
	gen.GenericsDo[IChannelLogExtDo, *model.ChannelLogExt]
}
type IChannelLogExtDo interface {
	gen.IGenericsDo[IChannelLogExtDo, *model.ChannelLogExt]
}

func (c *channelLogExtDo) withDO(do gen.Dao) IChannelLogExtDo {
	_r := &channelLogExtDo{}
	_r.DO = *do.(*gen.DO)
	_r.IWithDO = gen.WithDOFunc[IChannelLogExtDo](c.withDO)
	return _r
}
