// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"github.com/BetaGoRobot/BetaGo-Redefine/internal/infrastructure/db/model"
)

func newChannelLog(db *gorm.DB, opts ...gen.DOOption) channelLog {
	_channelLog := channelLog{}

	_channelLog.channelLogDo.IWithDO = gen.WithDOFunc[IChannelLogDo](_channelLog.channelLogDo.withDO)

	_channelLog.channelLogDo.UseDB(db, opts...)
	_channelLog.channelLogDo.UseModel(&model.ChannelLog{})

	tableName := _channelLog.channelLogDo.TableName()
	_channelLog.ALL = field.NewAsterisk(tableName)
	_channelLog.UserID = field.NewString(tableName, "user_id")
	_channelLog.UserName = field.NewString(tableName, "user_name")
	_channelLog.ChannelID = field.NewString(tableName, "channel_id")
	_channelLog.ChannelName = field.NewString(tableName, "channel_name")
	_channelLog.JoinedTime = field.NewTime(tableName, "joined_time")
	_channelLog.LeftTime = field.NewTime(tableName, "left_time")
	_channelLog.IsUpdate = field.NewBool(tableName, "is_update")
	_channelLog.MsgID = field.NewString(tableName, "msg_id")

	_channelLog.fillFieldMap()

	return _channelLog
}

type channelLog struct {
	channelLogDo channelLogDo

	ALL         field.Asterisk
	UserID      field.String
	UserName    field.String
	ChannelID   field.String
	ChannelName field.String
	JoinedTime  field.Time
	LeftTime    field.Time
	IsUpdate    field.Bool
	MsgID       field.String

	fieldMap map[string]field.Expr
}

func (c channelLog) Table(newTableName string) *channelLog {
	c.channelLogDo.UseTable(newTableName)
	return c.updateTableName(newTableName)
}

func (c channelLog) As(alias string) *channelLog {
	c.channelLogDo.DO = *(c.channelLogDo.As(alias).(*gen.DO))
	return c.updateTableName(alias)
}

func (c *channelLog) updateTableName(table string) *channelLog {
	c.ALL = field.NewAsterisk(table)
	c.UserID = field.NewString(table, "user_id")
	c.UserName = field.NewString(table, "user_name")
	c.ChannelID = field.NewString(table, "channel_id")
	c.ChannelName = field.NewString(table, "channel_name")
	c.JoinedTime = field.NewTime(table, "joined_time")
	c.LeftTime = field.NewTime(table, "left_time")
	c.IsUpdate = field.NewBool(table, "is_update")
	c.MsgID = field.NewString(table, "msg_id")

	c.fillFieldMap()

	return c
}

func (c *channelLog) WithContext(ctx context.Context) IChannelLogDo {
	return c.channelLogDo.WithContext(ctx)
}

func (c channelLog) TableName() string { return c.channelLogDo.TableName() }

func (c channelLog) Alias() string { return c.channelLogDo.Alias() }

func (c channelLog) Columns(cols ...field.Expr) gen.Columns { return c.channelLogDo.Columns(cols...) }

func (c *channelLog) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := c.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (c *channelLog) fillFieldMap() {
	c.fieldMap = make(map[string]field.Expr, 8)
	c.fieldMap["user_id"] = c.UserID
	c.fieldMap["user_name"] = c.UserName
	c.fieldMap["channel_id"] = c.ChannelID
	c.fieldMap["channel_name"] = c.ChannelName
	c.fieldMap["joined_time"] = c.JoinedTime
	c.fieldMap["left_time"] = c.LeftTime
	c.fieldMap["is_update"] = c.IsUpdate
	c.fieldMap["msg_id"] = c.MsgID
}

func (c channelLog) clone(db *gorm.DB) channelLog {
	c.channelLogDo.ReplaceConnPool(db.Statement.ConnPool)
	return c
}

func (c channelLog) replaceDB(db *gorm.DB) channelLog {
	c.channelLogDo.ReplaceDB(db)
	return c
}

type channelLogDo struct {
	gen.GenericsDo[IChannelLogDo, *model.ChannelLog]
}
type IChannelLogDo interface {
	gen.IGenericsDo[IChannelLogDo, *model.ChannelLog]
}

func (c *channelLogDo) withDO(do gen.Dao) IChannelLogDo {
	_r := &channelLogDo{}
	_r.DO = *do.(*gen.DO)
	_r.IWithDO = gen.WithDOFunc[IChannelLogDo](c.withDO)
	return _r
}
