// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"github.com/BetaGoRobot/BetaGo-Redefine/internal/infrastructure/db/model"
)

func newChatContextRecord(db *gorm.DB, opts ...gen.DOOption) chatContextRecord {
	_chatContextRecord := chatContextRecord{}

	_chatContextRecord.chatContextRecordDo.IWithDO = gen.WithDOFunc[IChatContextRecordDo](_chatContextRecord.chatContextRecordDo.withDO)

	_chatContextRecord.chatContextRecordDo.UseDB(db, opts...)
	_chatContextRecord.chatContextRecordDo.UseModel(&model.ChatContextRecord{})

	tableName := _chatContextRecord.chatContextRecordDo.TableName()
	_chatContextRecord.ALL = field.NewAsterisk(tableName)
	_chatContextRecord.UserID = field.NewString(tableName, "user_id")
	_chatContextRecord.SessionID = field.NewString(tableName, "session_id")

	_chatContextRecord.fillFieldMap()

	return _chatContextRecord
}

type chatContextRecord struct {
	chatContextRecordDo chatContextRecordDo

	ALL       field.Asterisk
	UserID    field.String
	SessionID field.String

	fieldMap map[string]field.Expr
}

func (c chatContextRecord) Table(newTableName string) *chatContextRecord {
	c.chatContextRecordDo.UseTable(newTableName)
	return c.updateTableName(newTableName)
}

func (c chatContextRecord) As(alias string) *chatContextRecord {
	c.chatContextRecordDo.DO = *(c.chatContextRecordDo.As(alias).(*gen.DO))
	return c.updateTableName(alias)
}

func (c *chatContextRecord) updateTableName(table string) *chatContextRecord {
	c.ALL = field.NewAsterisk(table)
	c.UserID = field.NewString(table, "user_id")
	c.SessionID = field.NewString(table, "session_id")

	c.fillFieldMap()

	return c
}

func (c *chatContextRecord) WithContext(ctx context.Context) IChatContextRecordDo {
	return c.chatContextRecordDo.WithContext(ctx)
}

func (c chatContextRecord) TableName() string { return c.chatContextRecordDo.TableName() }

func (c chatContextRecord) Alias() string { return c.chatContextRecordDo.Alias() }

func (c chatContextRecord) Columns(cols ...field.Expr) gen.Columns {
	return c.chatContextRecordDo.Columns(cols...)
}

func (c *chatContextRecord) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := c.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (c *chatContextRecord) fillFieldMap() {
	c.fieldMap = make(map[string]field.Expr, 2)
	c.fieldMap["user_id"] = c.UserID
	c.fieldMap["session_id"] = c.SessionID
}

func (c chatContextRecord) clone(db *gorm.DB) chatContextRecord {
	c.chatContextRecordDo.ReplaceConnPool(db.Statement.ConnPool)
	return c
}

func (c chatContextRecord) replaceDB(db *gorm.DB) chatContextRecord {
	c.chatContextRecordDo.ReplaceDB(db)
	return c
}

type chatContextRecordDo struct {
	gen.GenericsDo[IChatContextRecordDo, *model.ChatContextRecord]
}
type IChatContextRecordDo interface {
	gen.IGenericsDo[IChatContextRecordDo, *model.ChatContextRecord]
}

func (c *chatContextRecordDo) withDO(do gen.Dao) IChatContextRecordDo {
	_r := &chatContextRecordDo{}
	_r.DO = *do.(*gen.DO)
	_r.IWithDO = gen.WithDOFunc[IChatContextRecordDo](c.withDO)
	return _r
}
