// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"github.com/BetaGoRobot/BetaGo-Redefine/internal/infrastructure/db/model"
)

func newChatRecordLog(db *gorm.DB, opts ...gen.DOOption) chatRecordLog {
	_chatRecordLog := chatRecordLog{}

	_chatRecordLog.chatRecordLogDo.IWithDO = gen.WithDOFunc[IChatRecordLogDo](_chatRecordLog.chatRecordLogDo.withDO)

	_chatRecordLog.chatRecordLogDo.UseDB(db, opts...)
	_chatRecordLog.chatRecordLogDo.UseModel(&model.ChatRecordLog{})

	tableName := _chatRecordLog.chatRecordLogDo.TableName()
	_chatRecordLog.ALL = field.NewAsterisk(tableName)
	_chatRecordLog.AuthorID = field.NewString(tableName, "author_id")
	_chatRecordLog.RecordStr = field.NewString(tableName, "record_str")

	_chatRecordLog.fillFieldMap()

	return _chatRecordLog
}

type chatRecordLog struct {
	chatRecordLogDo chatRecordLogDo

	ALL       field.Asterisk
	AuthorID  field.String
	RecordStr field.String

	fieldMap map[string]field.Expr
}

func (c chatRecordLog) Table(newTableName string) *chatRecordLog {
	c.chatRecordLogDo.UseTable(newTableName)
	return c.updateTableName(newTableName)
}

func (c chatRecordLog) As(alias string) *chatRecordLog {
	c.chatRecordLogDo.DO = *(c.chatRecordLogDo.As(alias).(*gen.DO))
	return c.updateTableName(alias)
}

func (c *chatRecordLog) updateTableName(table string) *chatRecordLog {
	c.ALL = field.NewAsterisk(table)
	c.AuthorID = field.NewString(table, "author_id")
	c.RecordStr = field.NewString(table, "record_str")

	c.fillFieldMap()

	return c
}

func (c *chatRecordLog) WithContext(ctx context.Context) IChatRecordLogDo {
	return c.chatRecordLogDo.WithContext(ctx)
}

func (c chatRecordLog) TableName() string { return c.chatRecordLogDo.TableName() }

func (c chatRecordLog) Alias() string { return c.chatRecordLogDo.Alias() }

func (c chatRecordLog) Columns(cols ...field.Expr) gen.Columns {
	return c.chatRecordLogDo.Columns(cols...)
}

func (c *chatRecordLog) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := c.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (c *chatRecordLog) fillFieldMap() {
	c.fieldMap = make(map[string]field.Expr, 2)
	c.fieldMap["author_id"] = c.AuthorID
	c.fieldMap["record_str"] = c.RecordStr
}

func (c chatRecordLog) clone(db *gorm.DB) chatRecordLog {
	c.chatRecordLogDo.ReplaceConnPool(db.Statement.ConnPool)
	return c
}

func (c chatRecordLog) replaceDB(db *gorm.DB) chatRecordLog {
	c.chatRecordLogDo.ReplaceDB(db)
	return c
}

type chatRecordLogDo struct {
	gen.GenericsDo[IChatRecordLogDo, *model.ChatRecordLog]
}
type IChatRecordLogDo interface {
	gen.IGenericsDo[IChatRecordLogDo, *model.ChatRecordLog]
}

func (c *chatRecordLogDo) withDO(do gen.Dao) IChatRecordLogDo {
	_r := &chatRecordLogDo{}
	_r.DO = *do.(*gen.DO)
	_r.IWithDO = gen.WithDOFunc[IChatRecordLogDo](c.withDO)
	return _r
}
