// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"github.com/BetaGoRobot/BetaGo-Redefine/internal/infrastructure/db/model"
)

func newCommandInfo(db *gorm.DB, opts ...gen.DOOption) commandInfo {
	_commandInfo := commandInfo{}

	_commandInfo.commandInfoDo.IWithDO = gen.WithDOFunc[ICommandInfoDo](_commandInfo.commandInfoDo.withDO)

	_commandInfo.commandInfoDo.UseDB(db, opts...)
	_commandInfo.commandInfoDo.UseModel(&model.CommandInfo{})

	tableName := _commandInfo.commandInfoDo.TableName()
	_commandInfo.ALL = field.NewAsterisk(tableName)
	_commandInfo.CommandName = field.NewString(tableName, "command_name")
	_commandInfo.CommandDesc = field.NewString(tableName, "command_desc")
	_commandInfo.CommandParamLen = field.NewInt64(tableName, "command_param_len")
	_commandInfo.CommandType = field.NewString(tableName, "command_type")
	_commandInfo.CreatedAt = field.NewTime(tableName, "created_at")
	_commandInfo.UpdatedAt = field.NewTime(tableName, "updated_at")

	_commandInfo.fillFieldMap()

	return _commandInfo
}

type commandInfo struct {
	commandInfoDo commandInfoDo

	ALL             field.Asterisk
	CommandName     field.String
	CommandDesc     field.String
	CommandParamLen field.Int64
	CommandType     field.String
	CreatedAt       field.Time
	UpdatedAt       field.Time

	fieldMap map[string]field.Expr
}

func (c commandInfo) Table(newTableName string) *commandInfo {
	c.commandInfoDo.UseTable(newTableName)
	return c.updateTableName(newTableName)
}

func (c commandInfo) As(alias string) *commandInfo {
	c.commandInfoDo.DO = *(c.commandInfoDo.As(alias).(*gen.DO))
	return c.updateTableName(alias)
}

func (c *commandInfo) updateTableName(table string) *commandInfo {
	c.ALL = field.NewAsterisk(table)
	c.CommandName = field.NewString(table, "command_name")
	c.CommandDesc = field.NewString(table, "command_desc")
	c.CommandParamLen = field.NewInt64(table, "command_param_len")
	c.CommandType = field.NewString(table, "command_type")
	c.CreatedAt = field.NewTime(table, "created_at")
	c.UpdatedAt = field.NewTime(table, "updated_at")

	c.fillFieldMap()

	return c
}

func (c *commandInfo) WithContext(ctx context.Context) ICommandInfoDo {
	return c.commandInfoDo.WithContext(ctx)
}

func (c commandInfo) TableName() string { return c.commandInfoDo.TableName() }

func (c commandInfo) Alias() string { return c.commandInfoDo.Alias() }

func (c commandInfo) Columns(cols ...field.Expr) gen.Columns { return c.commandInfoDo.Columns(cols...) }

func (c *commandInfo) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := c.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (c *commandInfo) fillFieldMap() {
	c.fieldMap = make(map[string]field.Expr, 6)
	c.fieldMap["command_name"] = c.CommandName
	c.fieldMap["command_desc"] = c.CommandDesc
	c.fieldMap["command_param_len"] = c.CommandParamLen
	c.fieldMap["command_type"] = c.CommandType
	c.fieldMap["created_at"] = c.CreatedAt
	c.fieldMap["updated_at"] = c.UpdatedAt
}

func (c commandInfo) clone(db *gorm.DB) commandInfo {
	c.commandInfoDo.ReplaceConnPool(db.Statement.ConnPool)
	return c
}

func (c commandInfo) replaceDB(db *gorm.DB) commandInfo {
	c.commandInfoDo.ReplaceDB(db)
	return c
}

type commandInfoDo struct {
	gen.GenericsDo[ICommandInfoDo, *model.CommandInfo]
}
type ICommandInfoDo interface {
	gen.IGenericsDo[ICommandInfoDo, *model.CommandInfo]
}

func (c *commandInfoDo) withDO(do gen.Dao) ICommandInfoDo {
	_r := &commandInfoDo{}
	_r.DO = *do.(*gen.DO)
	_r.IWithDO = gen.WithDOFunc[ICommandInfoDo](c.withDO)
	return _r
}
