// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"github.com/BetaGoRobot/BetaGo-Redefine/internal/infrastructure/db/model"
)

func newCronCmdTask(db *gorm.DB, opts ...gen.DOOption) cronCmdTask {
	_cronCmdTask := cronCmdTask{}

	_cronCmdTask.cronCmdTaskDo.IWithDO = gen.WithDOFunc[ICronCmdTaskDo](_cronCmdTask.cronCmdTaskDo.withDO)

	_cronCmdTask.cronCmdTaskDo.UseDB(db, opts...)
	_cronCmdTask.cronCmdTaskDo.UseModel(&model.CronCmdTask{})

	tableName := _cronCmdTask.cronCmdTaskDo.TableName()
	_cronCmdTask.ALL = field.NewAsterisk(tableName)
	_cronCmdTask.TaskName = field.NewString(tableName, "task_name")
	_cronCmdTask.TaskCron = field.NewString(tableName, "task_cron")
	_cronCmdTask.TaskCmd = field.NewString(tableName, "task_cmd")

	_cronCmdTask.fillFieldMap()

	return _cronCmdTask
}

type cronCmdTask struct {
	cronCmdTaskDo cronCmdTaskDo

	ALL      field.Asterisk
	TaskName field.String
	TaskCron field.String
	TaskCmd  field.String

	fieldMap map[string]field.Expr
}

func (c cronCmdTask) Table(newTableName string) *cronCmdTask {
	c.cronCmdTaskDo.UseTable(newTableName)
	return c.updateTableName(newTableName)
}

func (c cronCmdTask) As(alias string) *cronCmdTask {
	c.cronCmdTaskDo.DO = *(c.cronCmdTaskDo.As(alias).(*gen.DO))
	return c.updateTableName(alias)
}

func (c *cronCmdTask) updateTableName(table string) *cronCmdTask {
	c.ALL = field.NewAsterisk(table)
	c.TaskName = field.NewString(table, "task_name")
	c.TaskCron = field.NewString(table, "task_cron")
	c.TaskCmd = field.NewString(table, "task_cmd")

	c.fillFieldMap()

	return c
}

func (c *cronCmdTask) WithContext(ctx context.Context) ICronCmdTaskDo {
	return c.cronCmdTaskDo.WithContext(ctx)
}

func (c cronCmdTask) TableName() string { return c.cronCmdTaskDo.TableName() }

func (c cronCmdTask) Alias() string { return c.cronCmdTaskDo.Alias() }

func (c cronCmdTask) Columns(cols ...field.Expr) gen.Columns { return c.cronCmdTaskDo.Columns(cols...) }

func (c *cronCmdTask) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := c.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (c *cronCmdTask) fillFieldMap() {
	c.fieldMap = make(map[string]field.Expr, 3)
	c.fieldMap["task_name"] = c.TaskName
	c.fieldMap["task_cron"] = c.TaskCron
	c.fieldMap["task_cmd"] = c.TaskCmd
}

func (c cronCmdTask) clone(db *gorm.DB) cronCmdTask {
	c.cronCmdTaskDo.ReplaceConnPool(db.Statement.ConnPool)
	return c
}

func (c cronCmdTask) replaceDB(db *gorm.DB) cronCmdTask {
	c.cronCmdTaskDo.ReplaceDB(db)
	return c
}

type cronCmdTaskDo struct {
	gen.GenericsDo[ICronCmdTaskDo, *model.CronCmdTask]
}
type ICronCmdTaskDo interface {
	gen.IGenericsDo[ICronCmdTaskDo, *model.CronCmdTask]
}

func (c *cronCmdTaskDo) withDO(do gen.Dao) ICronCmdTaskDo {
	_r := &cronCmdTaskDo{}
	_r.DO = *do.(*gen.DO)
	_r.IWithDO = gen.WithDOFunc[ICronCmdTaskDo](c.withDO)
	return _r
}
