// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"github.com/BetaGoRobot/BetaGo-Redefine/internal/infrastructure/db/model"
)

func newDynamicConfig(db *gorm.DB, opts ...gen.DOOption) dynamicConfig {
	_dynamicConfig := dynamicConfig{}

	_dynamicConfig.dynamicConfigDo.IWithDO = gen.WithDOFunc[IDynamicConfigDo](_dynamicConfig.dynamicConfigDo.withDO)

	_dynamicConfig.dynamicConfigDo.UseDB(db, opts...)
	_dynamicConfig.dynamicConfigDo.UseModel(&model.DynamicConfig{})

	tableName := _dynamicConfig.dynamicConfigDo.TableName()
	_dynamicConfig.ALL = field.NewAsterisk(tableName)
	_dynamicConfig.Key = field.NewString(tableName, "key")
	_dynamicConfig.Value = field.NewString(tableName, "value")

	_dynamicConfig.fillFieldMap()

	return _dynamicConfig
}

type dynamicConfig struct {
	dynamicConfigDo dynamicConfigDo

	ALL   field.Asterisk
	Key   field.String
	Value field.String

	fieldMap map[string]field.Expr
}

func (d dynamicConfig) Table(newTableName string) *dynamicConfig {
	d.dynamicConfigDo.UseTable(newTableName)
	return d.updateTableName(newTableName)
}

func (d dynamicConfig) As(alias string) *dynamicConfig {
	d.dynamicConfigDo.DO = *(d.dynamicConfigDo.As(alias).(*gen.DO))
	return d.updateTableName(alias)
}

func (d *dynamicConfig) updateTableName(table string) *dynamicConfig {
	d.ALL = field.NewAsterisk(table)
	d.Key = field.NewString(table, "key")
	d.Value = field.NewString(table, "value")

	d.fillFieldMap()

	return d
}

func (d *dynamicConfig) WithContext(ctx context.Context) IDynamicConfigDo {
	return d.dynamicConfigDo.WithContext(ctx)
}

func (d dynamicConfig) TableName() string { return d.dynamicConfigDo.TableName() }

func (d dynamicConfig) Alias() string { return d.dynamicConfigDo.Alias() }

func (d dynamicConfig) Columns(cols ...field.Expr) gen.Columns {
	return d.dynamicConfigDo.Columns(cols...)
}

func (d *dynamicConfig) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := d.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (d *dynamicConfig) fillFieldMap() {
	d.fieldMap = make(map[string]field.Expr, 2)
	d.fieldMap["key"] = d.Key
	d.fieldMap["value"] = d.Value
}

func (d dynamicConfig) clone(db *gorm.DB) dynamicConfig {
	d.dynamicConfigDo.ReplaceConnPool(db.Statement.ConnPool)
	return d
}

func (d dynamicConfig) replaceDB(db *gorm.DB) dynamicConfig {
	d.dynamicConfigDo.ReplaceDB(db)
	return d
}

type dynamicConfigDo struct {
	gen.GenericsDo[IDynamicConfigDo, *model.DynamicConfig]
}
type IDynamicConfigDo interface {
	gen.IGenericsDo[IDynamicConfigDo, *model.DynamicConfig]
}

func (d *dynamicConfigDo) withDO(do gen.Dao) IDynamicConfigDo {
	_r := &dynamicConfigDo{}
	_r.DO = *do.(*gen.DO)
	_r.IWithDO = gen.WithDOFunc[IDynamicConfigDo](d.withDO)
	return _r
}
