// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"github.com/BetaGoRobot/BetaGo-Redefine/internal/infrastructure/db/model"
)

func newFunctionEnabling(db *gorm.DB, opts ...gen.DOOption) functionEnabling {
	_functionEnabling := functionEnabling{}

	_functionEnabling.functionEnablingDo.IWithDO = gen.WithDOFunc[IFunctionEnablingDo](_functionEnabling.functionEnablingDo.withDO)

	_functionEnabling.functionEnablingDo.UseDB(db, opts...)
	_functionEnabling.functionEnablingDo.UseModel(&model.FunctionEnabling{})

	tableName := _functionEnabling.functionEnablingDo.TableName()
	_functionEnabling.ALL = field.NewAsterisk(tableName)
	_functionEnabling.GuildID = field.NewString(tableName, "guild_id")
	_functionEnabling.Function = field.NewString(tableName, "function")
	_functionEnabling.Disable = field.NewBool(tableName, "disable")

	_functionEnabling.fillFieldMap()

	return _functionEnabling
}

type functionEnabling struct {
	functionEnablingDo functionEnablingDo

	ALL      field.Asterisk
	GuildID  field.String
	Function field.String
	Disable  field.Bool

	fieldMap map[string]field.Expr
}

func (f functionEnabling) Table(newTableName string) *functionEnabling {
	f.functionEnablingDo.UseTable(newTableName)
	return f.updateTableName(newTableName)
}

func (f functionEnabling) As(alias string) *functionEnabling {
	f.functionEnablingDo.DO = *(f.functionEnablingDo.As(alias).(*gen.DO))
	return f.updateTableName(alias)
}

func (f *functionEnabling) updateTableName(table string) *functionEnabling {
	f.ALL = field.NewAsterisk(table)
	f.GuildID = field.NewString(table, "guild_id")
	f.Function = field.NewString(table, "function")
	f.Disable = field.NewBool(table, "disable")

	f.fillFieldMap()

	return f
}

func (f *functionEnabling) WithContext(ctx context.Context) IFunctionEnablingDo {
	return f.functionEnablingDo.WithContext(ctx)
}

func (f functionEnabling) TableName() string { return f.functionEnablingDo.TableName() }

func (f functionEnabling) Alias() string { return f.functionEnablingDo.Alias() }

func (f functionEnabling) Columns(cols ...field.Expr) gen.Columns {
	return f.functionEnablingDo.Columns(cols...)
}

func (f *functionEnabling) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := f.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (f *functionEnabling) fillFieldMap() {
	f.fieldMap = make(map[string]field.Expr, 3)
	f.fieldMap["guild_id"] = f.GuildID
	f.fieldMap["function"] = f.Function
	f.fieldMap["disable"] = f.Disable
}

func (f functionEnabling) clone(db *gorm.DB) functionEnabling {
	f.functionEnablingDo.ReplaceConnPool(db.Statement.ConnPool)
	return f
}

func (f functionEnabling) replaceDB(db *gorm.DB) functionEnabling {
	f.functionEnablingDo.ReplaceDB(db)
	return f
}

type functionEnablingDo struct {
	gen.GenericsDo[IFunctionEnablingDo, *model.FunctionEnabling]
}
type IFunctionEnablingDo interface {
	gen.IGenericsDo[IFunctionEnablingDo, *model.FunctionEnabling]
}

func (f *functionEnablingDo) withDO(do gen.Dao) IFunctionEnablingDo {
	_r := &functionEnablingDo{}
	_r.DO = *do.(*gen.DO)
	_r.IWithDO = gen.WithDOFunc[IFunctionEnablingDo](f.withDO)
	return _r
}
