// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

var (
	Q                     = new(Query)
	Administrator         *administrator
	AlertList             *alertList
	CardActionRecordLog   *cardActionRecordLog
	ChannelLog            *channelLog
	ChannelLogExt         *channelLogExt
	ChatContextRecord     *chatContextRecord
	ChatRecordLog         *chatRecordLog
	CommandInfo           *commandInfo
	CopyWritingCustom     *copyWritingCustom
	CopyWritingGeneral    *copyWritingGeneral
	CronCmdTask           *cronCmdTask
	DynamicConfig         *dynamicConfig
	FunctionEnabling      *functionEnabling
	ImitateRateCustom     *imitateRateCustom
	InteractionStat       *interactionStat
	LarkImg               *larkImg
	MessageLog            *messageLog
	MsgTraceLog           *msgTraceLog
	PrivateMode           *privateMode
	PromptConf            *promptConf
	PromptTemplateArg     *promptTemplateArg
	QuoteReplyMsg         *quoteReplyMsg
	QuoteReplyMsgCustom   *quoteReplyMsgCustom
	ReactImageMeterial    *reactImageMeterial
	ReactionWhitelist     *reactionWhitelist
	RepeatWhitelist       *repeatWhitelist
	RepeatWordsRate       *repeatWordsRate
	RepeatWordsRateCustom *repeatWordsRateCustom
	StickerMapping        *stickerMapping
	TemplateVersion       *templateVersion
)

func SetDefault(db *gorm.DB, opts ...gen.DOOption) {
	*Q = *Use(db, opts...)
	Administrator = &Q.Administrator
	AlertList = &Q.AlertList
	CardActionRecordLog = &Q.CardActionRecordLog
	ChannelLog = &Q.ChannelLog
	ChannelLogExt = &Q.ChannelLogExt
	ChatContextRecord = &Q.ChatContextRecord
	ChatRecordLog = &Q.ChatRecordLog
	CommandInfo = &Q.CommandInfo
	CopyWritingCustom = &Q.CopyWritingCustom
	CopyWritingGeneral = &Q.CopyWritingGeneral
	CronCmdTask = &Q.CronCmdTask
	DynamicConfig = &Q.DynamicConfig
	FunctionEnabling = &Q.FunctionEnabling
	ImitateRateCustom = &Q.ImitateRateCustom
	InteractionStat = &Q.InteractionStat
	LarkImg = &Q.LarkImg
	MessageLog = &Q.MessageLog
	MsgTraceLog = &Q.MsgTraceLog
	PrivateMode = &Q.PrivateMode
	PromptConf = &Q.PromptConf
	PromptTemplateArg = &Q.PromptTemplateArg
	QuoteReplyMsg = &Q.QuoteReplyMsg
	QuoteReplyMsgCustom = &Q.QuoteReplyMsgCustom
	ReactImageMeterial = &Q.ReactImageMeterial
	ReactionWhitelist = &Q.ReactionWhitelist
	RepeatWhitelist = &Q.RepeatWhitelist
	RepeatWordsRate = &Q.RepeatWordsRate
	RepeatWordsRateCustom = &Q.RepeatWordsRateCustom
	StickerMapping = &Q.StickerMapping
	TemplateVersion = &Q.TemplateVersion
}

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:                    db,
		Administrator:         newAdministrator(db, opts...),
		AlertList:             newAlertList(db, opts...),
		CardActionRecordLog:   newCardActionRecordLog(db, opts...),
		ChannelLog:            newChannelLog(db, opts...),
		ChannelLogExt:         newChannelLogExt(db, opts...),
		ChatContextRecord:     newChatContextRecord(db, opts...),
		ChatRecordLog:         newChatRecordLog(db, opts...),
		CommandInfo:           newCommandInfo(db, opts...),
		CopyWritingCustom:     newCopyWritingCustom(db, opts...),
		CopyWritingGeneral:    newCopyWritingGeneral(db, opts...),
		CronCmdTask:           newCronCmdTask(db, opts...),
		DynamicConfig:         newDynamicConfig(db, opts...),
		FunctionEnabling:      newFunctionEnabling(db, opts...),
		ImitateRateCustom:     newImitateRateCustom(db, opts...),
		InteractionStat:       newInteractionStat(db, opts...),
		LarkImg:               newLarkImg(db, opts...),
		MessageLog:            newMessageLog(db, opts...),
		MsgTraceLog:           newMsgTraceLog(db, opts...),
		PrivateMode:           newPrivateMode(db, opts...),
		PromptConf:            newPromptConf(db, opts...),
		PromptTemplateArg:     newPromptTemplateArg(db, opts...),
		QuoteReplyMsg:         newQuoteReplyMsg(db, opts...),
		QuoteReplyMsgCustom:   newQuoteReplyMsgCustom(db, opts...),
		ReactImageMeterial:    newReactImageMeterial(db, opts...),
		ReactionWhitelist:     newReactionWhitelist(db, opts...),
		RepeatWhitelist:       newRepeatWhitelist(db, opts...),
		RepeatWordsRate:       newRepeatWordsRate(db, opts...),
		RepeatWordsRateCustom: newRepeatWordsRateCustom(db, opts...),
		StickerMapping:        newStickerMapping(db, opts...),
		TemplateVersion:       newTemplateVersion(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	Administrator         administrator
	AlertList             alertList
	CardActionRecordLog   cardActionRecordLog
	ChannelLog            channelLog
	ChannelLogExt         channelLogExt
	ChatContextRecord     chatContextRecord
	ChatRecordLog         chatRecordLog
	CommandInfo           commandInfo
	CopyWritingCustom     copyWritingCustom
	CopyWritingGeneral    copyWritingGeneral
	CronCmdTask           cronCmdTask
	DynamicConfig         dynamicConfig
	FunctionEnabling      functionEnabling
	ImitateRateCustom     imitateRateCustom
	InteractionStat       interactionStat
	LarkImg               larkImg
	MessageLog            messageLog
	MsgTraceLog           msgTraceLog
	PrivateMode           privateMode
	PromptConf            promptConf
	PromptTemplateArg     promptTemplateArg
	QuoteReplyMsg         quoteReplyMsg
	QuoteReplyMsgCustom   quoteReplyMsgCustom
	ReactImageMeterial    reactImageMeterial
	ReactionWhitelist     reactionWhitelist
	RepeatWhitelist       repeatWhitelist
	RepeatWordsRate       repeatWordsRate
	RepeatWordsRateCustom repeatWordsRateCustom
	StickerMapping        stickerMapping
	TemplateVersion       templateVersion
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:                    db,
		Administrator:         q.Administrator.clone(db),
		AlertList:             q.AlertList.clone(db),
		CardActionRecordLog:   q.CardActionRecordLog.clone(db),
		ChannelLog:            q.ChannelLog.clone(db),
		ChannelLogExt:         q.ChannelLogExt.clone(db),
		ChatContextRecord:     q.ChatContextRecord.clone(db),
		ChatRecordLog:         q.ChatRecordLog.clone(db),
		CommandInfo:           q.CommandInfo.clone(db),
		CopyWritingCustom:     q.CopyWritingCustom.clone(db),
		CopyWritingGeneral:    q.CopyWritingGeneral.clone(db),
		CronCmdTask:           q.CronCmdTask.clone(db),
		DynamicConfig:         q.DynamicConfig.clone(db),
		FunctionEnabling:      q.FunctionEnabling.clone(db),
		ImitateRateCustom:     q.ImitateRateCustom.clone(db),
		InteractionStat:       q.InteractionStat.clone(db),
		LarkImg:               q.LarkImg.clone(db),
		MessageLog:            q.MessageLog.clone(db),
		MsgTraceLog:           q.MsgTraceLog.clone(db),
		PrivateMode:           q.PrivateMode.clone(db),
		PromptConf:            q.PromptConf.clone(db),
		PromptTemplateArg:     q.PromptTemplateArg.clone(db),
		QuoteReplyMsg:         q.QuoteReplyMsg.clone(db),
		QuoteReplyMsgCustom:   q.QuoteReplyMsgCustom.clone(db),
		ReactImageMeterial:    q.ReactImageMeterial.clone(db),
		ReactionWhitelist:     q.ReactionWhitelist.clone(db),
		RepeatWhitelist:       q.RepeatWhitelist.clone(db),
		RepeatWordsRate:       q.RepeatWordsRate.clone(db),
		RepeatWordsRateCustom: q.RepeatWordsRateCustom.clone(db),
		StickerMapping:        q.StickerMapping.clone(db),
		TemplateVersion:       q.TemplateVersion.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.clone(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.clone(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:                    db,
		Administrator:         q.Administrator.replaceDB(db),
		AlertList:             q.AlertList.replaceDB(db),
		CardActionRecordLog:   q.CardActionRecordLog.replaceDB(db),
		ChannelLog:            q.ChannelLog.replaceDB(db),
		ChannelLogExt:         q.ChannelLogExt.replaceDB(db),
		ChatContextRecord:     q.ChatContextRecord.replaceDB(db),
		ChatRecordLog:         q.ChatRecordLog.replaceDB(db),
		CommandInfo:           q.CommandInfo.replaceDB(db),
		CopyWritingCustom:     q.CopyWritingCustom.replaceDB(db),
		CopyWritingGeneral:    q.CopyWritingGeneral.replaceDB(db),
		CronCmdTask:           q.CronCmdTask.replaceDB(db),
		DynamicConfig:         q.DynamicConfig.replaceDB(db),
		FunctionEnabling:      q.FunctionEnabling.replaceDB(db),
		ImitateRateCustom:     q.ImitateRateCustom.replaceDB(db),
		InteractionStat:       q.InteractionStat.replaceDB(db),
		LarkImg:               q.LarkImg.replaceDB(db),
		MessageLog:            q.MessageLog.replaceDB(db),
		MsgTraceLog:           q.MsgTraceLog.replaceDB(db),
		PrivateMode:           q.PrivateMode.replaceDB(db),
		PromptConf:            q.PromptConf.replaceDB(db),
		PromptTemplateArg:     q.PromptTemplateArg.replaceDB(db),
		QuoteReplyMsg:         q.QuoteReplyMsg.replaceDB(db),
		QuoteReplyMsgCustom:   q.QuoteReplyMsgCustom.replaceDB(db),
		ReactImageMeterial:    q.ReactImageMeterial.replaceDB(db),
		ReactionWhitelist:     q.ReactionWhitelist.replaceDB(db),
		RepeatWhitelist:       q.RepeatWhitelist.replaceDB(db),
		RepeatWordsRate:       q.RepeatWordsRate.replaceDB(db),
		RepeatWordsRateCustom: q.RepeatWordsRateCustom.replaceDB(db),
		StickerMapping:        q.StickerMapping.replaceDB(db),
		TemplateVersion:       q.TemplateVersion.replaceDB(db),
	}
}

type queryCtx struct {
	Administrator         IAdministratorDo
	AlertList             IAlertListDo
	CardActionRecordLog   ICardActionRecordLogDo
	ChannelLog            IChannelLogDo
	ChannelLogExt         IChannelLogExtDo
	ChatContextRecord     IChatContextRecordDo
	ChatRecordLog         IChatRecordLogDo
	CommandInfo           ICommandInfoDo
	CopyWritingCustom     ICopyWritingCustomDo
	CopyWritingGeneral    ICopyWritingGeneralDo
	CronCmdTask           ICronCmdTaskDo
	DynamicConfig         IDynamicConfigDo
	FunctionEnabling      IFunctionEnablingDo
	ImitateRateCustom     IImitateRateCustomDo
	InteractionStat       IInteractionStatDo
	LarkImg               ILarkImgDo
	MessageLog            IMessageLogDo
	MsgTraceLog           IMsgTraceLogDo
	PrivateMode           IPrivateModeDo
	PromptConf            IPromptConfDo
	PromptTemplateArg     IPromptTemplateArgDo
	QuoteReplyMsg         IQuoteReplyMsgDo
	QuoteReplyMsgCustom   IQuoteReplyMsgCustomDo
	ReactImageMeterial    IReactImageMeterialDo
	ReactionWhitelist     IReactionWhitelistDo
	RepeatWhitelist       IRepeatWhitelistDo
	RepeatWordsRate       IRepeatWordsRateDo
	RepeatWordsRateCustom IRepeatWordsRateCustomDo
	StickerMapping        IStickerMappingDo
	TemplateVersion       ITemplateVersionDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		Administrator:         q.Administrator.WithContext(ctx),
		AlertList:             q.AlertList.WithContext(ctx),
		CardActionRecordLog:   q.CardActionRecordLog.WithContext(ctx),
		ChannelLog:            q.ChannelLog.WithContext(ctx),
		ChannelLogExt:         q.ChannelLogExt.WithContext(ctx),
		ChatContextRecord:     q.ChatContextRecord.WithContext(ctx),
		ChatRecordLog:         q.ChatRecordLog.WithContext(ctx),
		CommandInfo:           q.CommandInfo.WithContext(ctx),
		CopyWritingCustom:     q.CopyWritingCustom.WithContext(ctx),
		CopyWritingGeneral:    q.CopyWritingGeneral.WithContext(ctx),
		CronCmdTask:           q.CronCmdTask.WithContext(ctx),
		DynamicConfig:         q.DynamicConfig.WithContext(ctx),
		FunctionEnabling:      q.FunctionEnabling.WithContext(ctx),
		ImitateRateCustom:     q.ImitateRateCustom.WithContext(ctx),
		InteractionStat:       q.InteractionStat.WithContext(ctx),
		LarkImg:               q.LarkImg.WithContext(ctx),
		MessageLog:            q.MessageLog.WithContext(ctx),
		MsgTraceLog:           q.MsgTraceLog.WithContext(ctx),
		PrivateMode:           q.PrivateMode.WithContext(ctx),
		PromptConf:            q.PromptConf.WithContext(ctx),
		PromptTemplateArg:     q.PromptTemplateArg.WithContext(ctx),
		QuoteReplyMsg:         q.QuoteReplyMsg.WithContext(ctx),
		QuoteReplyMsgCustom:   q.QuoteReplyMsgCustom.WithContext(ctx),
		ReactImageMeterial:    q.ReactImageMeterial.WithContext(ctx),
		ReactionWhitelist:     q.ReactionWhitelist.WithContext(ctx),
		RepeatWhitelist:       q.RepeatWhitelist.WithContext(ctx),
		RepeatWordsRate:       q.RepeatWordsRate.WithContext(ctx),
		RepeatWordsRateCustom: q.RepeatWordsRateCustom.WithContext(ctx),
		StickerMapping:        q.StickerMapping.WithContext(ctx),
		TemplateVersion:       q.TemplateVersion.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	tx := q.db.Begin(opts...)
	return &QueryTx{Query: q.clone(tx), Error: tx.Error}
}

type QueryTx struct {
	*Query
	Error error
}

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
