// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"github.com/BetaGoRobot/BetaGo-Redefine/internal/infrastructure/db/model"
)

func newImitateRateCustom(db *gorm.DB, opts ...gen.DOOption) imitateRateCustom {
	_imitateRateCustom := imitateRateCustom{}

	_imitateRateCustom.imitateRateCustomDo.IWithDO = gen.WithDOFunc[IImitateRateCustomDo](_imitateRateCustom.imitateRateCustomDo.withDO)

	_imitateRateCustom.imitateRateCustomDo.UseDB(db, opts...)
	_imitateRateCustom.imitateRateCustomDo.UseModel(&model.ImitateRateCustom{})

	tableName := _imitateRateCustom.imitateRateCustomDo.TableName()
	_imitateRateCustom.ALL = field.NewAsterisk(tableName)
	_imitateRateCustom.CreatedAt = field.NewTime(tableName, "created_at")
	_imitateRateCustom.UpdatedAt = field.NewTime(tableName, "updated_at")
	_imitateRateCustom.DeletedAt = field.NewField(tableName, "deleted_at")
	_imitateRateCustom.GuildID = field.NewString(tableName, "guild_id")
	_imitateRateCustom.Rate = field.NewInt64(tableName, "rate")

	_imitateRateCustom.fillFieldMap()

	return _imitateRateCustom
}

type imitateRateCustom struct {
	imitateRateCustomDo imitateRateCustomDo

	ALL       field.Asterisk
	CreatedAt field.Time
	UpdatedAt field.Time
	DeletedAt field.Field
	GuildID   field.String
	Rate      field.Int64

	fieldMap map[string]field.Expr
}

func (i imitateRateCustom) Table(newTableName string) *imitateRateCustom {
	i.imitateRateCustomDo.UseTable(newTableName)
	return i.updateTableName(newTableName)
}

func (i imitateRateCustom) As(alias string) *imitateRateCustom {
	i.imitateRateCustomDo.DO = *(i.imitateRateCustomDo.As(alias).(*gen.DO))
	return i.updateTableName(alias)
}

func (i *imitateRateCustom) updateTableName(table string) *imitateRateCustom {
	i.ALL = field.NewAsterisk(table)
	i.CreatedAt = field.NewTime(table, "created_at")
	i.UpdatedAt = field.NewTime(table, "updated_at")
	i.DeletedAt = field.NewField(table, "deleted_at")
	i.GuildID = field.NewString(table, "guild_id")
	i.Rate = field.NewInt64(table, "rate")

	i.fillFieldMap()

	return i
}

func (i *imitateRateCustom) WithContext(ctx context.Context) IImitateRateCustomDo {
	return i.imitateRateCustomDo.WithContext(ctx)
}

func (i imitateRateCustom) TableName() string { return i.imitateRateCustomDo.TableName() }

func (i imitateRateCustom) Alias() string { return i.imitateRateCustomDo.Alias() }

func (i imitateRateCustom) Columns(cols ...field.Expr) gen.Columns {
	return i.imitateRateCustomDo.Columns(cols...)
}

func (i *imitateRateCustom) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := i.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (i *imitateRateCustom) fillFieldMap() {
	i.fieldMap = make(map[string]field.Expr, 5)
	i.fieldMap["created_at"] = i.CreatedAt
	i.fieldMap["updated_at"] = i.UpdatedAt
	i.fieldMap["deleted_at"] = i.DeletedAt
	i.fieldMap["guild_id"] = i.GuildID
	i.fieldMap["rate"] = i.Rate
}

func (i imitateRateCustom) clone(db *gorm.DB) imitateRateCustom {
	i.imitateRateCustomDo.ReplaceConnPool(db.Statement.ConnPool)
	return i
}

func (i imitateRateCustom) replaceDB(db *gorm.DB) imitateRateCustom {
	i.imitateRateCustomDo.ReplaceDB(db)
	return i
}

type imitateRateCustomDo struct {
	gen.GenericsDo[IImitateRateCustomDo, *model.ImitateRateCustom]
}
type IImitateRateCustomDo interface {
	gen.IGenericsDo[IImitateRateCustomDo, *model.ImitateRateCustom]
}

func (i *imitateRateCustomDo) withDO(do gen.Dao) IImitateRateCustomDo {
	_r := &imitateRateCustomDo{}
	_r.DO = *do.(*gen.DO)
	_r.IWithDO = gen.WithDOFunc[IImitateRateCustomDo](i.withDO)
	return _r
}
