// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"github.com/BetaGoRobot/BetaGo-Redefine/internal/infrastructure/db/model"
)

func newInsightLlmTokenUsage(db *gorm.DB, opts ...gen.DOOption) insightLlmTokenUsage {
	_insightLlmTokenUsage := insightLlmTokenUsage{}

	_insightLlmTokenUsage.insightLlmTokenUsageDo.IWithDO = gen.WithDOFunc[IInsightLlmTokenUsageDo](_insightLlmTokenUsage.insightLlmTokenUsageDo.withDO)

	_insightLlmTokenUsage.insightLlmTokenUsageDo.UseDB(db, opts...)
	_insightLlmTokenUsage.insightLlmTokenUsageDo.UseModel(&model.InsightLlmTokenUsage{})

	tableName := _insightLlmTokenUsage.insightLlmTokenUsageDo.TableName()
	_insightLlmTokenUsage.ALL = field.NewAsterisk(tableName)
	_insightLlmTokenUsage.ID = field.NewInt64(tableName, "id")
	_insightLlmTokenUsage.AccountID = field.NewString(tableName, "account_id")
	_insightLlmTokenUsage.ProductName = field.NewString(tableName, "product_name")
	_insightLlmTokenUsage.ModelNameArk = field.NewString(tableName, "model_name_ark")
	_insightLlmTokenUsage.ModelVersionArk = field.NewString(tableName, "model_version_ark")
	_insightLlmTokenUsage.ModelBillingIdentity = field.NewString(tableName, "model_billing_identity")
	_insightLlmTokenUsage.EndpointID = field.NewString(tableName, "endpoint_id")
	_insightLlmTokenUsage.LogID = field.NewString(tableName, "log_id")
	_insightLlmTokenUsage.PromptTokens = field.NewInt64(tableName, "prompt_tokens")
	_insightLlmTokenUsage.CompletionTokens = field.NewInt64(tableName, "completion_tokens")
	_insightLlmTokenUsage.RequestTime = field.NewTime(tableName, "request_time")

	_insightLlmTokenUsage.fillFieldMap()

	return _insightLlmTokenUsage
}

type insightLlmTokenUsage struct {
	insightLlmTokenUsageDo insightLlmTokenUsageDo

	ALL                  field.Asterisk
	ID                   field.Int64
	AccountID            field.String
	ProductName          field.String
	ModelNameArk         field.String
	ModelVersionArk      field.String
	ModelBillingIdentity field.String
	EndpointID           field.String
	LogID                field.String
	PromptTokens         field.Int64
	CompletionTokens     field.Int64
	RequestTime          field.Time

	fieldMap map[string]field.Expr
}

func (i insightLlmTokenUsage) Table(newTableName string) *insightLlmTokenUsage {
	i.insightLlmTokenUsageDo.UseTable(newTableName)
	return i.updateTableName(newTableName)
}

func (i insightLlmTokenUsage) As(alias string) *insightLlmTokenUsage {
	i.insightLlmTokenUsageDo.DO = *(i.insightLlmTokenUsageDo.As(alias).(*gen.DO))
	return i.updateTableName(alias)
}

func (i *insightLlmTokenUsage) updateTableName(table string) *insightLlmTokenUsage {
	i.ALL = field.NewAsterisk(table)
	i.ID = field.NewInt64(table, "id")
	i.AccountID = field.NewString(table, "account_id")
	i.ProductName = field.NewString(table, "product_name")
	i.ModelNameArk = field.NewString(table, "model_name_ark")
	i.ModelVersionArk = field.NewString(table, "model_version_ark")
	i.ModelBillingIdentity = field.NewString(table, "model_billing_identity")
	i.EndpointID = field.NewString(table, "endpoint_id")
	i.LogID = field.NewString(table, "log_id")
	i.PromptTokens = field.NewInt64(table, "prompt_tokens")
	i.CompletionTokens = field.NewInt64(table, "completion_tokens")
	i.RequestTime = field.NewTime(table, "request_time")

	i.fillFieldMap()

	return i
}

func (i *insightLlmTokenUsage) WithContext(ctx context.Context) IInsightLlmTokenUsageDo {
	return i.insightLlmTokenUsageDo.WithContext(ctx)
}

func (i insightLlmTokenUsage) TableName() string { return i.insightLlmTokenUsageDo.TableName() }

func (i insightLlmTokenUsage) Alias() string { return i.insightLlmTokenUsageDo.Alias() }

func (i insightLlmTokenUsage) Columns(cols ...field.Expr) gen.Columns {
	return i.insightLlmTokenUsageDo.Columns(cols...)
}

func (i *insightLlmTokenUsage) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := i.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (i *insightLlmTokenUsage) fillFieldMap() {
	i.fieldMap = make(map[string]field.Expr, 11)
	i.fieldMap["id"] = i.ID
	i.fieldMap["account_id"] = i.AccountID
	i.fieldMap["product_name"] = i.ProductName
	i.fieldMap["model_name_ark"] = i.ModelNameArk
	i.fieldMap["model_version_ark"] = i.ModelVersionArk
	i.fieldMap["model_billing_identity"] = i.ModelBillingIdentity
	i.fieldMap["endpoint_id"] = i.EndpointID
	i.fieldMap["log_id"] = i.LogID
	i.fieldMap["prompt_tokens"] = i.PromptTokens
	i.fieldMap["completion_tokens"] = i.CompletionTokens
	i.fieldMap["request_time"] = i.RequestTime
}

func (i insightLlmTokenUsage) clone(db *gorm.DB) insightLlmTokenUsage {
	i.insightLlmTokenUsageDo.ReplaceConnPool(db.Statement.ConnPool)
	return i
}

func (i insightLlmTokenUsage) replaceDB(db *gorm.DB) insightLlmTokenUsage {
	i.insightLlmTokenUsageDo.ReplaceDB(db)
	return i
}

type insightLlmTokenUsageDo struct {
	gen.GenericsDo[IInsightLlmTokenUsageDo, *model.InsightLlmTokenUsage]
}
type IInsightLlmTokenUsageDo interface {
	gen.IGenericsDo[IInsightLlmTokenUsageDo, *model.InsightLlmTokenUsage]
}

func (i *insightLlmTokenUsageDo) withDO(do gen.Dao) IInsightLlmTokenUsageDo {
	_r := &insightLlmTokenUsageDo{}
	_r.DO = *do.(*gen.DO)
	_r.IWithDO = gen.WithDOFunc[IInsightLlmTokenUsageDo](i.withDO)
	return _r
}
