// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"github.com/BetaGoRobot/BetaGo-Redefine/internal/infrastructure/db/model"
)

func newInteractionStat(db *gorm.DB, opts ...gen.DOOption) interactionStat {
	_interactionStat := interactionStat{}

	_interactionStat.interactionStatDo.IWithDO = gen.WithDOFunc[IInteractionStatDo](_interactionStat.interactionStatDo.withDO)

	_interactionStat.interactionStatDo.UseDB(db, opts...)
	_interactionStat.interactionStatDo.UseModel(&model.InteractionStat{})

	tableName := _interactionStat.interactionStatDo.TableName()
	_interactionStat.ALL = field.NewAsterisk(tableName)
	_interactionStat.OpenID = field.NewString(tableName, "open_id")
	_interactionStat.GuildID = field.NewString(tableName, "guild_id")
	_interactionStat.NickName = field.NewString(tableName, "nick_name")
	_interactionStat.UserName = field.NewString(tableName, "user_name")
	_interactionStat.ActionType = field.NewString(tableName, "action_type")
	_interactionStat.CreatedAt = field.NewTime(tableName, "created_at")
	_interactionStat.MsgID = field.NewString(tableName, "msg_id")

	_interactionStat.fillFieldMap()

	return _interactionStat
}

type interactionStat struct {
	interactionStatDo interactionStatDo

	ALL        field.Asterisk
	OpenID     field.String
	GuildID    field.String
	NickName   field.String
	UserName   field.String
	ActionType field.String
	CreatedAt  field.Time
	MsgID      field.String

	fieldMap map[string]field.Expr
}

func (i interactionStat) Table(newTableName string) *interactionStat {
	i.interactionStatDo.UseTable(newTableName)
	return i.updateTableName(newTableName)
}

func (i interactionStat) As(alias string) *interactionStat {
	i.interactionStatDo.DO = *(i.interactionStatDo.As(alias).(*gen.DO))
	return i.updateTableName(alias)
}

func (i *interactionStat) updateTableName(table string) *interactionStat {
	i.ALL = field.NewAsterisk(table)
	i.OpenID = field.NewString(table, "open_id")
	i.GuildID = field.NewString(table, "guild_id")
	i.NickName = field.NewString(table, "nick_name")
	i.UserName = field.NewString(table, "user_name")
	i.ActionType = field.NewString(table, "action_type")
	i.CreatedAt = field.NewTime(table, "created_at")
	i.MsgID = field.NewString(table, "msg_id")

	i.fillFieldMap()

	return i
}

func (i *interactionStat) WithContext(ctx context.Context) IInteractionStatDo {
	return i.interactionStatDo.WithContext(ctx)
}

func (i interactionStat) TableName() string { return i.interactionStatDo.TableName() }

func (i interactionStat) Alias() string { return i.interactionStatDo.Alias() }

func (i interactionStat) Columns(cols ...field.Expr) gen.Columns {
	return i.interactionStatDo.Columns(cols...)
}

func (i *interactionStat) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := i.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (i *interactionStat) fillFieldMap() {
	i.fieldMap = make(map[string]field.Expr, 7)
	i.fieldMap["open_id"] = i.OpenID
	i.fieldMap["guild_id"] = i.GuildID
	i.fieldMap["nick_name"] = i.NickName
	i.fieldMap["user_name"] = i.UserName
	i.fieldMap["action_type"] = i.ActionType
	i.fieldMap["created_at"] = i.CreatedAt
	i.fieldMap["msg_id"] = i.MsgID
}

func (i interactionStat) clone(db *gorm.DB) interactionStat {
	i.interactionStatDo.ReplaceConnPool(db.Statement.ConnPool)
	return i
}

func (i interactionStat) replaceDB(db *gorm.DB) interactionStat {
	i.interactionStatDo.ReplaceDB(db)
	return i
}

type interactionStatDo struct {
	gen.GenericsDo[IInteractionStatDo, *model.InteractionStat]
}
type IInteractionStatDo interface {
	gen.IGenericsDo[IInteractionStatDo, *model.InteractionStat]
}

func (i *interactionStatDo) withDO(do gen.Dao) IInteractionStatDo {
	_r := &interactionStatDo{}
	_r.DO = *do.(*gen.DO)
	_r.IWithDO = gen.WithDOFunc[IInteractionStatDo](i.withDO)
	return _r
}
