// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"github.com/BetaGoRobot/BetaGo-Redefine/internal/infrastructure/db/model"
)

func newLarkImg(db *gorm.DB, opts ...gen.DOOption) larkImg {
	_larkImg := larkImg{}

	_larkImg.larkImgDo.IWithDO = gen.WithDOFunc[ILarkImgDo](_larkImg.larkImgDo.withDO)

	_larkImg.larkImgDo.UseDB(db, opts...)
	_larkImg.larkImgDo.UseModel(&model.LarkImg{})

	tableName := _larkImg.larkImgDo.TableName()
	_larkImg.ALL = field.NewAsterisk(tableName)
	_larkImg.ID = field.NewInt64(tableName, "id")
	_larkImg.CreatedAt = field.NewTime(tableName, "created_at")
	_larkImg.UpdatedAt = field.NewTime(tableName, "updated_at")
	_larkImg.DeletedAt = field.NewField(tableName, "deleted_at")
	_larkImg.SongID = field.NewString(tableName, "song_id")
	_larkImg.ImgKey = field.NewString(tableName, "img_key")

	_larkImg.fillFieldMap()

	return _larkImg
}

type larkImg struct {
	larkImgDo larkImgDo

	ALL       field.Asterisk
	ID        field.Int64
	CreatedAt field.Time
	UpdatedAt field.Time
	DeletedAt field.Field
	SongID    field.String
	ImgKey    field.String

	fieldMap map[string]field.Expr
}

func (l larkImg) Table(newTableName string) *larkImg {
	l.larkImgDo.UseTable(newTableName)
	return l.updateTableName(newTableName)
}

func (l larkImg) As(alias string) *larkImg {
	l.larkImgDo.DO = *(l.larkImgDo.As(alias).(*gen.DO))
	return l.updateTableName(alias)
}

func (l *larkImg) updateTableName(table string) *larkImg {
	l.ALL = field.NewAsterisk(table)
	l.ID = field.NewInt64(table, "id")
	l.CreatedAt = field.NewTime(table, "created_at")
	l.UpdatedAt = field.NewTime(table, "updated_at")
	l.DeletedAt = field.NewField(table, "deleted_at")
	l.SongID = field.NewString(table, "song_id")
	l.ImgKey = field.NewString(table, "img_key")

	l.fillFieldMap()

	return l
}

func (l *larkImg) WithContext(ctx context.Context) ILarkImgDo { return l.larkImgDo.WithContext(ctx) }

func (l larkImg) TableName() string { return l.larkImgDo.TableName() }

func (l larkImg) Alias() string { return l.larkImgDo.Alias() }

func (l larkImg) Columns(cols ...field.Expr) gen.Columns { return l.larkImgDo.Columns(cols...) }

func (l *larkImg) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := l.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (l *larkImg) fillFieldMap() {
	l.fieldMap = make(map[string]field.Expr, 6)
	l.fieldMap["id"] = l.ID
	l.fieldMap["created_at"] = l.CreatedAt
	l.fieldMap["updated_at"] = l.UpdatedAt
	l.fieldMap["deleted_at"] = l.DeletedAt
	l.fieldMap["song_id"] = l.SongID
	l.fieldMap["img_key"] = l.ImgKey
}

func (l larkImg) clone(db *gorm.DB) larkImg {
	l.larkImgDo.ReplaceConnPool(db.Statement.ConnPool)
	return l
}

func (l larkImg) replaceDB(db *gorm.DB) larkImg {
	l.larkImgDo.ReplaceDB(db)
	return l
}

type larkImgDo struct {
	gen.GenericsDo[ILarkImgDo, *model.LarkImg]
}
type ILarkImgDo interface {
	gen.IGenericsDo[ILarkImgDo, *model.LarkImg]
}

func (l *larkImgDo) withDO(do gen.Dao) ILarkImgDo {
	_r := &larkImgDo{}
	_r.DO = *do.(*gen.DO)
	_r.IWithDO = gen.WithDOFunc[ILarkImgDo](l.withDO)
	return _r
}
