// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"github.com/BetaGoRobot/BetaGo-Redefine/internal/infrastructure/db/model"
)

func newLlmTokenUsageRecord(db *gorm.DB, opts ...gen.DOOption) llmTokenUsageRecord {
	_llmTokenUsageRecord := llmTokenUsageRecord{}

	_llmTokenUsageRecord.llmTokenUsageRecordDo.IWithDO = gen.WithDOFunc[ILlmTokenUsageRecordDo](_llmTokenUsageRecord.llmTokenUsageRecordDo.withDO)

	_llmTokenUsageRecord.llmTokenUsageRecordDo.UseDB(db, opts...)
	_llmTokenUsageRecord.llmTokenUsageRecordDo.UseModel(&model.LlmTokenUsageRecord{})

	tableName := _llmTokenUsageRecord.llmTokenUsageRecordDo.TableName()
	_llmTokenUsageRecord.ALL = field.NewAsterisk(tableName)
	_llmTokenUsageRecord.ID = field.NewInt64(tableName, "id")
	_llmTokenUsageRecord.CreatedAt = field.NewTime(tableName, "created_at")
	_llmTokenUsageRecord.BucketMinute = field.NewTime(tableName, "bucket_minute")
	_llmTokenUsageRecord.BucketHour = field.NewTime(tableName, "bucket_hour")
	_llmTokenUsageRecord.BucketDay = field.NewTime(tableName, "bucket_day")
	_llmTokenUsageRecord.Provider = field.NewString(tableName, "provider")
	_llmTokenUsageRecord.Model = field.NewString(tableName, "model")
	_llmTokenUsageRecord.Kind = field.NewString(tableName, "kind")
	_llmTokenUsageRecord.SourceType = field.NewString(tableName, "source_type")
	_llmTokenUsageRecord.Source = field.NewString(tableName, "source")
	_llmTokenUsageRecord.ChatID = field.NewString(tableName, "chat_id")
	_llmTokenUsageRecord.ChatName = field.NewString(tableName, "chat_name")
	_llmTokenUsageRecord.OpenID = field.NewString(tableName, "open_id")
	_llmTokenUsageRecord.UserName = field.NewString(tableName, "user_name")
	_llmTokenUsageRecord.Status = field.NewString(tableName, "status")
	_llmTokenUsageRecord.PromptTokens = field.NewInt64(tableName, "prompt_tokens")
	_llmTokenUsageRecord.CompletionTokens = field.NewInt64(tableName, "completion_tokens")
	_llmTokenUsageRecord.TotalTokens = field.NewInt64(tableName, "total_tokens")
	_llmTokenUsageRecord.ResponseID = field.NewString(tableName, "response_id")
	_llmTokenUsageRecord.TraceID = field.NewString(tableName, "trace_id")
	_llmTokenUsageRecord.Error = field.NewString(tableName, "error")

	_llmTokenUsageRecord.fillFieldMap()

	return _llmTokenUsageRecord
}

type llmTokenUsageRecord struct {
	llmTokenUsageRecordDo llmTokenUsageRecordDo

	ALL              field.Asterisk
	ID               field.Int64
	CreatedAt        field.Time
	BucketMinute     field.Time
	BucketHour       field.Time
	BucketDay        field.Time
	Provider         field.String
	Model            field.String
	Kind             field.String
	SourceType       field.String
	Source           field.String
	ChatID           field.String
	ChatName         field.String
	OpenID           field.String
	UserName         field.String
	Status           field.String
	PromptTokens     field.Int64
	CompletionTokens field.Int64
	TotalTokens      field.Int64
	ResponseID       field.String
	TraceID          field.String
	Error            field.String

	fieldMap map[string]field.Expr
}

func (l llmTokenUsageRecord) Table(newTableName string) *llmTokenUsageRecord {
	l.llmTokenUsageRecordDo.UseTable(newTableName)
	return l.updateTableName(newTableName)
}

func (l llmTokenUsageRecord) As(alias string) *llmTokenUsageRecord {
	l.llmTokenUsageRecordDo.DO = *(l.llmTokenUsageRecordDo.As(alias).(*gen.DO))
	return l.updateTableName(alias)
}

func (l *llmTokenUsageRecord) updateTableName(table string) *llmTokenUsageRecord {
	l.ALL = field.NewAsterisk(table)
	l.ID = field.NewInt64(table, "id")
	l.CreatedAt = field.NewTime(table, "created_at")
	l.BucketMinute = field.NewTime(table, "bucket_minute")
	l.BucketHour = field.NewTime(table, "bucket_hour")
	l.BucketDay = field.NewTime(table, "bucket_day")
	l.Provider = field.NewString(table, "provider")
	l.Model = field.NewString(table, "model")
	l.Kind = field.NewString(table, "kind")
	l.SourceType = field.NewString(table, "source_type")
	l.Source = field.NewString(table, "source")
	l.ChatID = field.NewString(table, "chat_id")
	l.ChatName = field.NewString(table, "chat_name")
	l.OpenID = field.NewString(table, "open_id")
	l.UserName = field.NewString(table, "user_name")
	l.Status = field.NewString(table, "status")
	l.PromptTokens = field.NewInt64(table, "prompt_tokens")
	l.CompletionTokens = field.NewInt64(table, "completion_tokens")
	l.TotalTokens = field.NewInt64(table, "total_tokens")
	l.ResponseID = field.NewString(table, "response_id")
	l.TraceID = field.NewString(table, "trace_id")
	l.Error = field.NewString(table, "error")

	l.fillFieldMap()

	return l
}

func (l *llmTokenUsageRecord) WithContext(ctx context.Context) ILlmTokenUsageRecordDo {
	return l.llmTokenUsageRecordDo.WithContext(ctx)
}

func (l llmTokenUsageRecord) TableName() string { return l.llmTokenUsageRecordDo.TableName() }

func (l llmTokenUsageRecord) Alias() string { return l.llmTokenUsageRecordDo.Alias() }

func (l llmTokenUsageRecord) Columns(cols ...field.Expr) gen.Columns {
	return l.llmTokenUsageRecordDo.Columns(cols...)
}

func (l *llmTokenUsageRecord) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := l.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (l *llmTokenUsageRecord) fillFieldMap() {
	l.fieldMap = make(map[string]field.Expr, 21)
	l.fieldMap["id"] = l.ID
	l.fieldMap["created_at"] = l.CreatedAt
	l.fieldMap["bucket_minute"] = l.BucketMinute
	l.fieldMap["bucket_hour"] = l.BucketHour
	l.fieldMap["bucket_day"] = l.BucketDay
	l.fieldMap["provider"] = l.Provider
	l.fieldMap["model"] = l.Model
	l.fieldMap["kind"] = l.Kind
	l.fieldMap["source_type"] = l.SourceType
	l.fieldMap["source"] = l.Source
	l.fieldMap["chat_id"] = l.ChatID
	l.fieldMap["chat_name"] = l.ChatName
	l.fieldMap["open_id"] = l.OpenID
	l.fieldMap["user_name"] = l.UserName
	l.fieldMap["status"] = l.Status
	l.fieldMap["prompt_tokens"] = l.PromptTokens
	l.fieldMap["completion_tokens"] = l.CompletionTokens
	l.fieldMap["total_tokens"] = l.TotalTokens
	l.fieldMap["response_id"] = l.ResponseID
	l.fieldMap["trace_id"] = l.TraceID
	l.fieldMap["error"] = l.Error
}

func (l llmTokenUsageRecord) clone(db *gorm.DB) llmTokenUsageRecord {
	l.llmTokenUsageRecordDo.ReplaceConnPool(db.Statement.ConnPool)
	return l
}

func (l llmTokenUsageRecord) replaceDB(db *gorm.DB) llmTokenUsageRecord {
	l.llmTokenUsageRecordDo.ReplaceDB(db)
	return l
}

type llmTokenUsageRecordDo struct {
	gen.GenericsDo[ILlmTokenUsageRecordDo, *model.LlmTokenUsageRecord]
}
type ILlmTokenUsageRecordDo interface {
	gen.IGenericsDo[ILlmTokenUsageRecordDo, *model.LlmTokenUsageRecord]
}

func (l *llmTokenUsageRecordDo) withDO(do gen.Dao) ILlmTokenUsageRecordDo {
	_r := &llmTokenUsageRecordDo{}
	_r.DO = *do.(*gen.DO)
	_r.IWithDO = gen.WithDOFunc[ILlmTokenUsageRecordDo](l.withDO)
	return _r
}
