// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"github.com/BetaGoRobot/BetaGo-Redefine/internal/infrastructure/db/model"
)

func newLlmToolCallRecord(db *gorm.DB, opts ...gen.DOOption) llmToolCallRecord {
	_llmToolCallRecord := llmToolCallRecord{}

	_llmToolCallRecord.llmToolCallRecordDo.IWithDO = gen.WithDOFunc[ILlmToolCallRecordDo](_llmToolCallRecord.llmToolCallRecordDo.withDO)

	_llmToolCallRecord.llmToolCallRecordDo.UseDB(db, opts...)
	_llmToolCallRecord.llmToolCallRecordDo.UseModel(&model.LlmToolCallRecord{})

	tableName := _llmToolCallRecord.llmToolCallRecordDo.TableName()
	_llmToolCallRecord.ALL = field.NewAsterisk(tableName)
	_llmToolCallRecord.ID = field.NewInt64(tableName, "id")
	_llmToolCallRecord.UsageRecordID = field.NewInt64(tableName, "usage_record_id")
	_llmToolCallRecord.BotID = field.NewString(tableName, "bot_id")
	_llmToolCallRecord.ChatID = field.NewString(tableName, "chat_id")
	_llmToolCallRecord.BusinessScene = field.NewString(tableName, "business_scene")
	_llmToolCallRecord.BusinessOperation = field.NewString(tableName, "business_operation")
	_llmToolCallRecord.ToolName = field.NewString(tableName, "tool_name")
	_llmToolCallRecord.Status = field.NewString(tableName, "status")
	_llmToolCallRecord.DurationMs = field.NewInt64(tableName, "duration_ms")
	_llmToolCallRecord.ErrorKind = field.NewString(tableName, "error_kind")
	_llmToolCallRecord.TraceID = field.NewString(tableName, "trace_id")
	_llmToolCallRecord.CalledAt = field.NewTime(tableName, "called_at")
	_llmToolCallRecord.CreatedAt = field.NewTime(tableName, "created_at")

	_llmToolCallRecord.fillFieldMap()

	return _llmToolCallRecord
}

type llmToolCallRecord struct {
	llmToolCallRecordDo llmToolCallRecordDo

	ALL               field.Asterisk
	ID                field.Int64
	UsageRecordID     field.Int64
	BotID             field.String
	ChatID            field.String
	BusinessScene     field.String
	BusinessOperation field.String
	ToolName          field.String
	Status            field.String
	DurationMs        field.Int64
	ErrorKind         field.String
	TraceID           field.String
	CalledAt          field.Time
	CreatedAt         field.Time

	fieldMap map[string]field.Expr
}

func (l llmToolCallRecord) Table(newTableName string) *llmToolCallRecord {
	l.llmToolCallRecordDo.UseTable(newTableName)
	return l.updateTableName(newTableName)
}

func (l llmToolCallRecord) As(alias string) *llmToolCallRecord {
	l.llmToolCallRecordDo.DO = *(l.llmToolCallRecordDo.As(alias).(*gen.DO))
	return l.updateTableName(alias)
}

func (l *llmToolCallRecord) updateTableName(table string) *llmToolCallRecord {
	l.ALL = field.NewAsterisk(table)
	l.ID = field.NewInt64(table, "id")
	l.UsageRecordID = field.NewInt64(table, "usage_record_id")
	l.BotID = field.NewString(table, "bot_id")
	l.ChatID = field.NewString(table, "chat_id")
	l.BusinessScene = field.NewString(table, "business_scene")
	l.BusinessOperation = field.NewString(table, "business_operation")
	l.ToolName = field.NewString(table, "tool_name")
	l.Status = field.NewString(table, "status")
	l.DurationMs = field.NewInt64(table, "duration_ms")
	l.ErrorKind = field.NewString(table, "error_kind")
	l.TraceID = field.NewString(table, "trace_id")
	l.CalledAt = field.NewTime(table, "called_at")
	l.CreatedAt = field.NewTime(table, "created_at")

	l.fillFieldMap()

	return l
}

func (l *llmToolCallRecord) WithContext(ctx context.Context) ILlmToolCallRecordDo {
	return l.llmToolCallRecordDo.WithContext(ctx)
}

func (l llmToolCallRecord) TableName() string { return l.llmToolCallRecordDo.TableName() }

func (l llmToolCallRecord) Alias() string { return l.llmToolCallRecordDo.Alias() }

func (l llmToolCallRecord) Columns(cols ...field.Expr) gen.Columns {
	return l.llmToolCallRecordDo.Columns(cols...)
}

func (l *llmToolCallRecord) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := l.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (l *llmToolCallRecord) fillFieldMap() {
	l.fieldMap = make(map[string]field.Expr, 13)
	l.fieldMap["id"] = l.ID
	l.fieldMap["usage_record_id"] = l.UsageRecordID
	l.fieldMap["bot_id"] = l.BotID
	l.fieldMap["chat_id"] = l.ChatID
	l.fieldMap["business_scene"] = l.BusinessScene
	l.fieldMap["business_operation"] = l.BusinessOperation
	l.fieldMap["tool_name"] = l.ToolName
	l.fieldMap["status"] = l.Status
	l.fieldMap["duration_ms"] = l.DurationMs
	l.fieldMap["error_kind"] = l.ErrorKind
	l.fieldMap["trace_id"] = l.TraceID
	l.fieldMap["called_at"] = l.CalledAt
	l.fieldMap["created_at"] = l.CreatedAt
}

func (l llmToolCallRecord) clone(db *gorm.DB) llmToolCallRecord {
	l.llmToolCallRecordDo.ReplaceConnPool(db.Statement.ConnPool)
	return l
}

func (l llmToolCallRecord) replaceDB(db *gorm.DB) llmToolCallRecord {
	l.llmToolCallRecordDo.ReplaceDB(db)
	return l
}

type llmToolCallRecordDo struct {
	gen.GenericsDo[ILlmToolCallRecordDo, *model.LlmToolCallRecord]
}
type ILlmToolCallRecordDo interface {
	gen.IGenericsDo[ILlmToolCallRecordDo, *model.LlmToolCallRecord]
}

func (l *llmToolCallRecordDo) withDO(do gen.Dao) ILlmToolCallRecordDo {
	_r := &llmToolCallRecordDo{}
	_r.DO = *do.(*gen.DO)
	_r.IWithDO = gen.WithDOFunc[ILlmToolCallRecordDo](l.withDO)
	return _r
}
