// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"github.com/BetaGoRobot/BetaGo-Redefine/internal/infrastructure/db/model"
)

func newLuckinOrder(db *gorm.DB, opts ...gen.DOOption) luckinOrder {
	_luckinOrder := luckinOrder{}

	_luckinOrder.luckinOrderDo.IWithDO = gen.WithDOFunc[ILuckinOrderDo](_luckinOrder.luckinOrderDo.withDO)

	_luckinOrder.luckinOrderDo.UseDB(db, opts...)
	_luckinOrder.luckinOrderDo.UseModel(&model.LuckinOrder{})

	tableName := _luckinOrder.luckinOrderDo.TableName()
	_luckinOrder.ALL = field.NewAsterisk(tableName)
	_luckinOrder.ID = field.NewInt64(tableName, "id")
	_luckinOrder.OrderID = field.NewString(tableName, "order_id")
	_luckinOrder.AppID = field.NewString(tableName, "app_id")
	_luckinOrder.BotOpenID = field.NewString(tableName, "bot_open_id")
	_luckinOrder.ChatID = field.NewString(tableName, "chat_id")
	_luckinOrder.RequesterOpenID = field.NewString(tableName, "requester_open_id")
	_luckinOrder.CredentialScopeType = field.NewString(tableName, "credential_scope_type")
	_luckinOrder.CredentialScopeID = field.NewString(tableName, "credential_scope_id")
	_luckinOrder.MessageID = field.NewString(tableName, "message_id")
	_luckinOrder.Status = field.NewString(tableName, "status")
	_luckinOrder.LastRemoteStatus = field.NewInt64(tableName, "last_remote_status")
	_luckinOrder.NeedPay = field.NewBool(tableName, "need_pay")
	_luckinOrder.PayURL = field.NewString(tableName, "pay_url")
	_luckinOrder.QrURL = field.NewString(tableName, "qr_url")
	_luckinOrder.DiscountPrice = field.NewFloat64(tableName, "discount_price")
	_luckinOrder.UnpaidReminded = field.NewBool(tableName, "unpaid_reminded")
	_luckinOrder.NextPollAt = field.NewTime(tableName, "next_poll_at")
	_luckinOrder.PollDeadline = field.NewTime(tableName, "poll_deadline")
	_luckinOrder.FailCount = field.NewInt64(tableName, "fail_count")
	_luckinOrder.StoppedReason = field.NewString(tableName, "stopped_reason")
	_luckinOrder.PlacedAt = field.NewTime(tableName, "placed_at")
	_luckinOrder.MakingAt = field.NewTime(tableName, "making_at")
	_luckinOrder.ReadyAt = field.NewTime(tableName, "ready_at")
	_luckinOrder.CompletedAt = field.NewTime(tableName, "completed_at")
	_luckinOrder.CancelledAt = field.NewTime(tableName, "cancelled_at")
	_luckinOrder.CreatedAt = field.NewTime(tableName, "created_at")
	_luckinOrder.UpdatedAt = field.NewTime(tableName, "updated_at")

	_luckinOrder.fillFieldMap()

	return _luckinOrder
}

type luckinOrder struct {
	luckinOrderDo luckinOrderDo

	ALL                 field.Asterisk
	ID                  field.Int64
	OrderID             field.String
	AppID               field.String
	BotOpenID           field.String
	ChatID              field.String
	RequesterOpenID     field.String
	CredentialScopeType field.String
	CredentialScopeID   field.String
	MessageID           field.String
	Status              field.String
	LastRemoteStatus    field.Int64
	NeedPay             field.Bool
	PayURL              field.String
	QrURL               field.String
	DiscountPrice       field.Float64
	UnpaidReminded      field.Bool
	NextPollAt          field.Time
	PollDeadline        field.Time
	FailCount           field.Int64
	StoppedReason       field.String
	PlacedAt            field.Time
	MakingAt            field.Time
	ReadyAt             field.Time
	CompletedAt         field.Time
	CancelledAt         field.Time
	CreatedAt           field.Time
	UpdatedAt           field.Time

	fieldMap map[string]field.Expr
}

func (l luckinOrder) Table(newTableName string) *luckinOrder {
	l.luckinOrderDo.UseTable(newTableName)
	return l.updateTableName(newTableName)
}

func (l luckinOrder) As(alias string) *luckinOrder {
	l.luckinOrderDo.DO = *(l.luckinOrderDo.As(alias).(*gen.DO))
	return l.updateTableName(alias)
}

func (l *luckinOrder) updateTableName(table string) *luckinOrder {
	l.ALL = field.NewAsterisk(table)
	l.ID = field.NewInt64(table, "id")
	l.OrderID = field.NewString(table, "order_id")
	l.AppID = field.NewString(table, "app_id")
	l.BotOpenID = field.NewString(table, "bot_open_id")
	l.ChatID = field.NewString(table, "chat_id")
	l.RequesterOpenID = field.NewString(table, "requester_open_id")
	l.CredentialScopeType = field.NewString(table, "credential_scope_type")
	l.CredentialScopeID = field.NewString(table, "credential_scope_id")
	l.MessageID = field.NewString(table, "message_id")
	l.Status = field.NewString(table, "status")
	l.LastRemoteStatus = field.NewInt64(table, "last_remote_status")
	l.NeedPay = field.NewBool(table, "need_pay")
	l.PayURL = field.NewString(table, "pay_url")
	l.QrURL = field.NewString(table, "qr_url")
	l.DiscountPrice = field.NewFloat64(table, "discount_price")
	l.UnpaidReminded = field.NewBool(table, "unpaid_reminded")
	l.NextPollAt = field.NewTime(table, "next_poll_at")
	l.PollDeadline = field.NewTime(table, "poll_deadline")
	l.FailCount = field.NewInt64(table, "fail_count")
	l.StoppedReason = field.NewString(table, "stopped_reason")
	l.PlacedAt = field.NewTime(table, "placed_at")
	l.MakingAt = field.NewTime(table, "making_at")
	l.ReadyAt = field.NewTime(table, "ready_at")
	l.CompletedAt = field.NewTime(table, "completed_at")
	l.CancelledAt = field.NewTime(table, "cancelled_at")
	l.CreatedAt = field.NewTime(table, "created_at")
	l.UpdatedAt = field.NewTime(table, "updated_at")

	l.fillFieldMap()

	return l
}

func (l *luckinOrder) WithContext(ctx context.Context) ILuckinOrderDo {
	return l.luckinOrderDo.WithContext(ctx)
}

func (l luckinOrder) TableName() string { return l.luckinOrderDo.TableName() }

func (l luckinOrder) Alias() string { return l.luckinOrderDo.Alias() }

func (l luckinOrder) Columns(cols ...field.Expr) gen.Columns {
	return l.luckinOrderDo.Columns(cols...)
}

func (l *luckinOrder) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := l.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (l *luckinOrder) fillFieldMap() {
	l.fieldMap = make(map[string]field.Expr, 27)
	l.fieldMap["id"] = l.ID
	l.fieldMap["order_id"] = l.OrderID
	l.fieldMap["app_id"] = l.AppID
	l.fieldMap["bot_open_id"] = l.BotOpenID
	l.fieldMap["chat_id"] = l.ChatID
	l.fieldMap["requester_open_id"] = l.RequesterOpenID
	l.fieldMap["credential_scope_type"] = l.CredentialScopeType
	l.fieldMap["credential_scope_id"] = l.CredentialScopeID
	l.fieldMap["message_id"] = l.MessageID
	l.fieldMap["status"] = l.Status
	l.fieldMap["last_remote_status"] = l.LastRemoteStatus
	l.fieldMap["need_pay"] = l.NeedPay
	l.fieldMap["pay_url"] = l.PayURL
	l.fieldMap["qr_url"] = l.QrURL
	l.fieldMap["discount_price"] = l.DiscountPrice
	l.fieldMap["unpaid_reminded"] = l.UnpaidReminded
	l.fieldMap["next_poll_at"] = l.NextPollAt
	l.fieldMap["poll_deadline"] = l.PollDeadline
	l.fieldMap["fail_count"] = l.FailCount
	l.fieldMap["stopped_reason"] = l.StoppedReason
	l.fieldMap["placed_at"] = l.PlacedAt
	l.fieldMap["making_at"] = l.MakingAt
	l.fieldMap["ready_at"] = l.ReadyAt
	l.fieldMap["completed_at"] = l.CompletedAt
	l.fieldMap["cancelled_at"] = l.CancelledAt
	l.fieldMap["created_at"] = l.CreatedAt
	l.fieldMap["updated_at"] = l.UpdatedAt
}

func (l luckinOrder) clone(db *gorm.DB) luckinOrder {
	l.luckinOrderDo.ReplaceConnPool(db.Statement.ConnPool)
	return l
}

func (l luckinOrder) replaceDB(db *gorm.DB) luckinOrder {
	l.luckinOrderDo.ReplaceDB(db)
	return l
}

type luckinOrderDo struct {
	gen.GenericsDo[ILuckinOrderDo, *model.LuckinOrder]
}
type ILuckinOrderDo interface {
	gen.IGenericsDo[ILuckinOrderDo, *model.LuckinOrder]
}

func (l *luckinOrderDo) withDO(do gen.Dao) ILuckinOrderDo {
	_r := &luckinOrderDo{}
	_r.DO = *do.(*gen.DO)
	_r.IWithDO = gen.WithDOFunc[ILuckinOrderDo](l.withDO)
	return _r
}
