// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"github.com/BetaGoRobot/BetaGo-Redefine/internal/infrastructure/db/model"
)

func newLuckinPendingOrder(db *gorm.DB, opts ...gen.DOOption) luckinPendingOrder {
	_luckinPendingOrder := luckinPendingOrder{}

	_luckinPendingOrder.luckinPendingOrderDo.IWithDO = gen.WithDOFunc[ILuckinPendingOrderDo](_luckinPendingOrder.luckinPendingOrderDo.withDO)

	_luckinPendingOrder.luckinPendingOrderDo.UseDB(db, opts...)
	_luckinPendingOrder.luckinPendingOrderDo.UseModel(&model.LuckinPendingOrder{})

	tableName := _luckinPendingOrder.luckinPendingOrderDo.TableName()
	_luckinPendingOrder.ALL = field.NewAsterisk(tableName)
	_luckinPendingOrder.ID = field.NewString(tableName, "id")
	_luckinPendingOrder.AppID = field.NewString(tableName, "app_id")
	_luckinPendingOrder.BotOpenID = field.NewString(tableName, "bot_open_id")
	_luckinPendingOrder.ChatID = field.NewString(tableName, "chat_id")
	_luckinPendingOrder.RequesterOpenID = field.NewString(tableName, "requester_open_id")
	_luckinPendingOrder.CredentialScopeType = field.NewString(tableName, "credential_scope_type")
	_luckinPendingOrder.CredentialScopeID = field.NewString(tableName, "credential_scope_id")
	_luckinPendingOrder.McpServerName = field.NewString(tableName, "mcp_server_name")
	_luckinPendingOrder.CreateOrderPayload = field.NewField(tableName, "create_order_payload")
	_luckinPendingOrder.PayloadHash = field.NewString(tableName, "payload_hash")
	_luckinPendingOrder.PreviewResult = field.NewField(tableName, "preview_result")
	_luckinPendingOrder.Status = field.NewString(tableName, "status")
	_luckinPendingOrder.ResultJSON = field.NewField(tableName, "result_json")
	_luckinPendingOrder.ErrorText = field.NewString(tableName, "error_text")
	_luckinPendingOrder.ExpiresAt = field.NewTime(tableName, "expires_at")
	_luckinPendingOrder.ConfirmedByOpenID = field.NewString(tableName, "confirmed_by_open_id")
	_luckinPendingOrder.ConfirmedAt = field.NewTime(tableName, "confirmed_at")
	_luckinPendingOrder.CreatedAt = field.NewTime(tableName, "created_at")
	_luckinPendingOrder.UpdatedAt = field.NewTime(tableName, "updated_at")

	_luckinPendingOrder.fillFieldMap()

	return _luckinPendingOrder
}

type luckinPendingOrder struct {
	luckinPendingOrderDo luckinPendingOrderDo

	ALL                 field.Asterisk
	ID                  field.String
	AppID               field.String
	BotOpenID           field.String
	ChatID              field.String
	RequesterOpenID     field.String
	CredentialScopeType field.String
	CredentialScopeID   field.String
	McpServerName       field.String
	CreateOrderPayload  field.Field
	PayloadHash         field.String
	PreviewResult       field.Field
	Status              field.String
	ResultJSON          field.Field
	ErrorText           field.String
	ExpiresAt           field.Time
	ConfirmedByOpenID   field.String
	ConfirmedAt         field.Time
	CreatedAt           field.Time
	UpdatedAt           field.Time

	fieldMap map[string]field.Expr
}

func (l luckinPendingOrder) Table(newTableName string) *luckinPendingOrder {
	l.luckinPendingOrderDo.UseTable(newTableName)
	return l.updateTableName(newTableName)
}

func (l luckinPendingOrder) As(alias string) *luckinPendingOrder {
	l.luckinPendingOrderDo.DO = *(l.luckinPendingOrderDo.As(alias).(*gen.DO))
	return l.updateTableName(alias)
}

func (l *luckinPendingOrder) updateTableName(table string) *luckinPendingOrder {
	l.ALL = field.NewAsterisk(table)
	l.ID = field.NewString(table, "id")
	l.AppID = field.NewString(table, "app_id")
	l.BotOpenID = field.NewString(table, "bot_open_id")
	l.ChatID = field.NewString(table, "chat_id")
	l.RequesterOpenID = field.NewString(table, "requester_open_id")
	l.CredentialScopeType = field.NewString(table, "credential_scope_type")
	l.CredentialScopeID = field.NewString(table, "credential_scope_id")
	l.McpServerName = field.NewString(table, "mcp_server_name")
	l.CreateOrderPayload = field.NewField(table, "create_order_payload")
	l.PayloadHash = field.NewString(table, "payload_hash")
	l.PreviewResult = field.NewField(table, "preview_result")
	l.Status = field.NewString(table, "status")
	l.ResultJSON = field.NewField(table, "result_json")
	l.ErrorText = field.NewString(table, "error_text")
	l.ExpiresAt = field.NewTime(table, "expires_at")
	l.ConfirmedByOpenID = field.NewString(table, "confirmed_by_open_id")
	l.ConfirmedAt = field.NewTime(table, "confirmed_at")
	l.CreatedAt = field.NewTime(table, "created_at")
	l.UpdatedAt = field.NewTime(table, "updated_at")

	l.fillFieldMap()

	return l
}

func (l *luckinPendingOrder) WithContext(ctx context.Context) ILuckinPendingOrderDo {
	return l.luckinPendingOrderDo.WithContext(ctx)
}

func (l luckinPendingOrder) TableName() string { return l.luckinPendingOrderDo.TableName() }

func (l luckinPendingOrder) Alias() string { return l.luckinPendingOrderDo.Alias() }

func (l luckinPendingOrder) Columns(cols ...field.Expr) gen.Columns {
	return l.luckinPendingOrderDo.Columns(cols...)
}

func (l *luckinPendingOrder) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := l.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (l *luckinPendingOrder) fillFieldMap() {
	l.fieldMap = make(map[string]field.Expr, 19)
	l.fieldMap["id"] = l.ID
	l.fieldMap["app_id"] = l.AppID
	l.fieldMap["bot_open_id"] = l.BotOpenID
	l.fieldMap["chat_id"] = l.ChatID
	l.fieldMap["requester_open_id"] = l.RequesterOpenID
	l.fieldMap["credential_scope_type"] = l.CredentialScopeType
	l.fieldMap["credential_scope_id"] = l.CredentialScopeID
	l.fieldMap["mcp_server_name"] = l.McpServerName
	l.fieldMap["create_order_payload"] = l.CreateOrderPayload
	l.fieldMap["payload_hash"] = l.PayloadHash
	l.fieldMap["preview_result"] = l.PreviewResult
	l.fieldMap["status"] = l.Status
	l.fieldMap["result_json"] = l.ResultJSON
	l.fieldMap["error_text"] = l.ErrorText
	l.fieldMap["expires_at"] = l.ExpiresAt
	l.fieldMap["confirmed_by_open_id"] = l.ConfirmedByOpenID
	l.fieldMap["confirmed_at"] = l.ConfirmedAt
	l.fieldMap["created_at"] = l.CreatedAt
	l.fieldMap["updated_at"] = l.UpdatedAt
}

func (l luckinPendingOrder) clone(db *gorm.DB) luckinPendingOrder {
	l.luckinPendingOrderDo.ReplaceConnPool(db.Statement.ConnPool)
	return l
}

func (l luckinPendingOrder) replaceDB(db *gorm.DB) luckinPendingOrder {
	l.luckinPendingOrderDo.ReplaceDB(db)
	return l
}

type luckinPendingOrderDo struct {
	gen.GenericsDo[ILuckinPendingOrderDo, *model.LuckinPendingOrder]
}
type ILuckinPendingOrderDo interface {
	gen.IGenericsDo[ILuckinPendingOrderDo, *model.LuckinPendingOrder]
}

func (l *luckinPendingOrderDo) withDO(do gen.Dao) ILuckinPendingOrderDo {
	_r := &luckinPendingOrderDo{}
	_r.DO = *do.(*gen.DO)
	_r.IWithDO = gen.WithDOFunc[ILuckinPendingOrderDo](l.withDO)
	return _r
}
