// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"github.com/BetaGoRobot/BetaGo-Redefine/internal/infrastructure/db/model"
)

func newMcpCredential(db *gorm.DB, opts ...gen.DOOption) mcpCredential {
	_mcpCredential := mcpCredential{}

	_mcpCredential.mcpCredentialDo.IWithDO = gen.WithDOFunc[IMcpCredentialDo](_mcpCredential.mcpCredentialDo.withDO)

	_mcpCredential.mcpCredentialDo.UseDB(db, opts...)
	_mcpCredential.mcpCredentialDo.UseModel(&model.McpCredential{})

	tableName := _mcpCredential.mcpCredentialDo.TableName()
	_mcpCredential.ALL = field.NewAsterisk(tableName)
	_mcpCredential.ID = field.NewInt64(tableName, "id")
	_mcpCredential.Provider = field.NewString(tableName, "provider")
	_mcpCredential.AppID = field.NewString(tableName, "app_id")
	_mcpCredential.BotOpenID = field.NewString(tableName, "bot_open_id")
	_mcpCredential.ScopeType = field.NewString(tableName, "scope_type")
	_mcpCredential.ScopeID = field.NewString(tableName, "scope_id")
	_mcpCredential.EncryptedToken = field.NewString(tableName, "encrypted_token")
	_mcpCredential.TokenHint = field.NewString(tableName, "token_hint")
	_mcpCredential.CreatedByOpenID = field.NewString(tableName, "created_by_open_id")
	_mcpCredential.UpdatedByOpenID = field.NewString(tableName, "updated_by_open_id")
	_mcpCredential.CreatedAt = field.NewTime(tableName, "created_at")
	_mcpCredential.UpdatedAt = field.NewTime(tableName, "updated_at")
	_mcpCredential.DeletedAt = field.NewField(tableName, "deleted_at")

	_mcpCredential.fillFieldMap()

	return _mcpCredential
}

type mcpCredential struct {
	mcpCredentialDo mcpCredentialDo

	ALL             field.Asterisk
	ID              field.Int64
	Provider        field.String
	AppID           field.String
	BotOpenID       field.String
	ScopeType       field.String
	ScopeID         field.String
	EncryptedToken  field.String
	TokenHint       field.String
	CreatedByOpenID field.String
	UpdatedByOpenID field.String
	CreatedAt       field.Time
	UpdatedAt       field.Time
	DeletedAt       field.Field

	fieldMap map[string]field.Expr
}

func (m mcpCredential) Table(newTableName string) *mcpCredential {
	m.mcpCredentialDo.UseTable(newTableName)
	return m.updateTableName(newTableName)
}

func (m mcpCredential) As(alias string) *mcpCredential {
	m.mcpCredentialDo.DO = *(m.mcpCredentialDo.As(alias).(*gen.DO))
	return m.updateTableName(alias)
}

func (m *mcpCredential) updateTableName(table string) *mcpCredential {
	m.ALL = field.NewAsterisk(table)
	m.ID = field.NewInt64(table, "id")
	m.Provider = field.NewString(table, "provider")
	m.AppID = field.NewString(table, "app_id")
	m.BotOpenID = field.NewString(table, "bot_open_id")
	m.ScopeType = field.NewString(table, "scope_type")
	m.ScopeID = field.NewString(table, "scope_id")
	m.EncryptedToken = field.NewString(table, "encrypted_token")
	m.TokenHint = field.NewString(table, "token_hint")
	m.CreatedByOpenID = field.NewString(table, "created_by_open_id")
	m.UpdatedByOpenID = field.NewString(table, "updated_by_open_id")
	m.CreatedAt = field.NewTime(table, "created_at")
	m.UpdatedAt = field.NewTime(table, "updated_at")
	m.DeletedAt = field.NewField(table, "deleted_at")

	m.fillFieldMap()

	return m
}

func (m *mcpCredential) WithContext(ctx context.Context) IMcpCredentialDo {
	return m.mcpCredentialDo.WithContext(ctx)
}

func (m mcpCredential) TableName() string { return m.mcpCredentialDo.TableName() }

func (m mcpCredential) Alias() string { return m.mcpCredentialDo.Alias() }

func (m mcpCredential) Columns(cols ...field.Expr) gen.Columns {
	return m.mcpCredentialDo.Columns(cols...)
}

func (m *mcpCredential) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := m.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (m *mcpCredential) fillFieldMap() {
	m.fieldMap = make(map[string]field.Expr, 13)
	m.fieldMap["id"] = m.ID
	m.fieldMap["provider"] = m.Provider
	m.fieldMap["app_id"] = m.AppID
	m.fieldMap["bot_open_id"] = m.BotOpenID
	m.fieldMap["scope_type"] = m.ScopeType
	m.fieldMap["scope_id"] = m.ScopeID
	m.fieldMap["encrypted_token"] = m.EncryptedToken
	m.fieldMap["token_hint"] = m.TokenHint
	m.fieldMap["created_by_open_id"] = m.CreatedByOpenID
	m.fieldMap["updated_by_open_id"] = m.UpdatedByOpenID
	m.fieldMap["created_at"] = m.CreatedAt
	m.fieldMap["updated_at"] = m.UpdatedAt
	m.fieldMap["deleted_at"] = m.DeletedAt
}

func (m mcpCredential) clone(db *gorm.DB) mcpCredential {
	m.mcpCredentialDo.ReplaceConnPool(db.Statement.ConnPool)
	return m
}

func (m mcpCredential) replaceDB(db *gorm.DB) mcpCredential {
	m.mcpCredentialDo.ReplaceDB(db)
	return m
}

type mcpCredentialDo struct {
	gen.GenericsDo[IMcpCredentialDo, *model.McpCredential]
}
type IMcpCredentialDo interface {
	gen.IGenericsDo[IMcpCredentialDo, *model.McpCredential]
}

func (m *mcpCredentialDo) withDO(do gen.Dao) IMcpCredentialDo {
	_r := &mcpCredentialDo{}
	_r.DO = *do.(*gen.DO)
	_r.IWithDO = gen.WithDOFunc[IMcpCredentialDo](m.withDO)
	return _r
}
