// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"github.com/BetaGoRobot/BetaGo-Redefine/internal/infrastructure/db/model"
)

func newMessageLog(db *gorm.DB, opts ...gen.DOOption) messageLog {
	_messageLog := messageLog{}

	_messageLog.messageLogDo.IWithDO = gen.WithDOFunc[IMessageLogDo](_messageLog.messageLogDo.withDO)

	_messageLog.messageLogDo.UseDB(db, opts...)
	_messageLog.messageLogDo.UseModel(&model.MessageLog{})

	tableName := _messageLog.messageLogDo.TableName()
	_messageLog.ALL = field.NewAsterisk(tableName)
	_messageLog.MessageID = field.NewString(tableName, "message_id")
	_messageLog.RootID = field.NewString(tableName, "root_id")
	_messageLog.ParentID = field.NewString(tableName, "parent_id")
	_messageLog.ChatID = field.NewString(tableName, "chat_id")
	_messageLog.ThreadID = field.NewString(tableName, "thread_id")
	_messageLog.ChatType = field.NewString(tableName, "chat_type")
	_messageLog.MessageType = field.NewString(tableName, "message_type")
	_messageLog.UserAgent = field.NewString(tableName, "user_agent")
	_messageLog.Mentions = field.NewString(tableName, "mentions")
	_messageLog.RawBody = field.NewString(tableName, "raw_body")
	_messageLog.Content = field.NewString(tableName, "content")
	_messageLog.FileKey = field.NewString(tableName, "file_key")
	_messageLog.CreatedAt = field.NewTime(tableName, "created_at")
	_messageLog.TraceID = field.NewString(tableName, "trace_id")

	_messageLog.fillFieldMap()

	return _messageLog
}

type messageLog struct {
	messageLogDo messageLogDo

	ALL         field.Asterisk
	MessageID   field.String
	RootID      field.String
	ParentID    field.String
	ChatID      field.String
	ThreadID    field.String
	ChatType    field.String
	MessageType field.String
	UserAgent   field.String
	Mentions    field.String
	RawBody     field.String
	Content     field.String
	FileKey     field.String
	CreatedAt   field.Time
	TraceID     field.String

	fieldMap map[string]field.Expr
}

func (m messageLog) Table(newTableName string) *messageLog {
	m.messageLogDo.UseTable(newTableName)
	return m.updateTableName(newTableName)
}

func (m messageLog) As(alias string) *messageLog {
	m.messageLogDo.DO = *(m.messageLogDo.As(alias).(*gen.DO))
	return m.updateTableName(alias)
}

func (m *messageLog) updateTableName(table string) *messageLog {
	m.ALL = field.NewAsterisk(table)
	m.MessageID = field.NewString(table, "message_id")
	m.RootID = field.NewString(table, "root_id")
	m.ParentID = field.NewString(table, "parent_id")
	m.ChatID = field.NewString(table, "chat_id")
	m.ThreadID = field.NewString(table, "thread_id")
	m.ChatType = field.NewString(table, "chat_type")
	m.MessageType = field.NewString(table, "message_type")
	m.UserAgent = field.NewString(table, "user_agent")
	m.Mentions = field.NewString(table, "mentions")
	m.RawBody = field.NewString(table, "raw_body")
	m.Content = field.NewString(table, "content")
	m.FileKey = field.NewString(table, "file_key")
	m.CreatedAt = field.NewTime(table, "created_at")
	m.TraceID = field.NewString(table, "trace_id")

	m.fillFieldMap()

	return m
}

func (m *messageLog) WithContext(ctx context.Context) IMessageLogDo {
	return m.messageLogDo.WithContext(ctx)
}

func (m messageLog) TableName() string { return m.messageLogDo.TableName() }

func (m messageLog) Alias() string { return m.messageLogDo.Alias() }

func (m messageLog) Columns(cols ...field.Expr) gen.Columns { return m.messageLogDo.Columns(cols...) }

func (m *messageLog) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := m.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (m *messageLog) fillFieldMap() {
	m.fieldMap = make(map[string]field.Expr, 14)
	m.fieldMap["message_id"] = m.MessageID
	m.fieldMap["root_id"] = m.RootID
	m.fieldMap["parent_id"] = m.ParentID
	m.fieldMap["chat_id"] = m.ChatID
	m.fieldMap["thread_id"] = m.ThreadID
	m.fieldMap["chat_type"] = m.ChatType
	m.fieldMap["message_type"] = m.MessageType
	m.fieldMap["user_agent"] = m.UserAgent
	m.fieldMap["mentions"] = m.Mentions
	m.fieldMap["raw_body"] = m.RawBody
	m.fieldMap["content"] = m.Content
	m.fieldMap["file_key"] = m.FileKey
	m.fieldMap["created_at"] = m.CreatedAt
	m.fieldMap["trace_id"] = m.TraceID
}

func (m messageLog) clone(db *gorm.DB) messageLog {
	m.messageLogDo.ReplaceConnPool(db.Statement.ConnPool)
	return m
}

func (m messageLog) replaceDB(db *gorm.DB) messageLog {
	m.messageLogDo.ReplaceDB(db)
	return m
}

type messageLogDo struct {
	gen.GenericsDo[IMessageLogDo, *model.MessageLog]
}
type IMessageLogDo interface {
	gen.IGenericsDo[IMessageLogDo, *model.MessageLog]
}

func (m *messageLogDo) withDO(do gen.Dao) IMessageLogDo {
	_r := &messageLogDo{}
	_r.DO = *do.(*gen.DO)
	_r.IWithDO = gen.WithDOFunc[IMessageLogDo](m.withDO)
	return _r
}
