// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"github.com/BetaGoRobot/BetaGo-Redefine/internal/infrastructure/db/model"
)

func newMsgTraceLog(db *gorm.DB, opts ...gen.DOOption) msgTraceLog {
	_msgTraceLog := msgTraceLog{}

	_msgTraceLog.msgTraceLogDo.IWithDO = gen.WithDOFunc[IMsgTraceLogDo](_msgTraceLog.msgTraceLogDo.withDO)

	_msgTraceLog.msgTraceLogDo.UseDB(db, opts...)
	_msgTraceLog.msgTraceLogDo.UseModel(&model.MsgTraceLog{})

	tableName := _msgTraceLog.msgTraceLogDo.TableName()
	_msgTraceLog.ALL = field.NewAsterisk(tableName)
	_msgTraceLog.MsgID = field.NewString(tableName, "msg_id")
	_msgTraceLog.TraceID = field.NewString(tableName, "trace_id")
	_msgTraceLog.CreatedAt = field.NewTime(tableName, "created_at")

	_msgTraceLog.fillFieldMap()

	return _msgTraceLog
}

type msgTraceLog struct {
	msgTraceLogDo msgTraceLogDo

	ALL       field.Asterisk
	MsgID     field.String
	TraceID   field.String
	CreatedAt field.Time

	fieldMap map[string]field.Expr
}

func (m msgTraceLog) Table(newTableName string) *msgTraceLog {
	m.msgTraceLogDo.UseTable(newTableName)
	return m.updateTableName(newTableName)
}

func (m msgTraceLog) As(alias string) *msgTraceLog {
	m.msgTraceLogDo.DO = *(m.msgTraceLogDo.As(alias).(*gen.DO))
	return m.updateTableName(alias)
}

func (m *msgTraceLog) updateTableName(table string) *msgTraceLog {
	m.ALL = field.NewAsterisk(table)
	m.MsgID = field.NewString(table, "msg_id")
	m.TraceID = field.NewString(table, "trace_id")
	m.CreatedAt = field.NewTime(table, "created_at")

	m.fillFieldMap()

	return m
}

func (m *msgTraceLog) WithContext(ctx context.Context) IMsgTraceLogDo {
	return m.msgTraceLogDo.WithContext(ctx)
}

func (m msgTraceLog) TableName() string { return m.msgTraceLogDo.TableName() }

func (m msgTraceLog) Alias() string { return m.msgTraceLogDo.Alias() }

func (m msgTraceLog) Columns(cols ...field.Expr) gen.Columns { return m.msgTraceLogDo.Columns(cols...) }

func (m *msgTraceLog) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := m.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (m *msgTraceLog) fillFieldMap() {
	m.fieldMap = make(map[string]field.Expr, 3)
	m.fieldMap["msg_id"] = m.MsgID
	m.fieldMap["trace_id"] = m.TraceID
	m.fieldMap["created_at"] = m.CreatedAt
}

func (m msgTraceLog) clone(db *gorm.DB) msgTraceLog {
	m.msgTraceLogDo.ReplaceConnPool(db.Statement.ConnPool)
	return m
}

func (m msgTraceLog) replaceDB(db *gorm.DB) msgTraceLog {
	m.msgTraceLogDo.ReplaceDB(db)
	return m
}

type msgTraceLogDo struct {
	gen.GenericsDo[IMsgTraceLogDo, *model.MsgTraceLog]
}
type IMsgTraceLogDo interface {
	gen.IGenericsDo[IMsgTraceLogDo, *model.MsgTraceLog]
}

func (m *msgTraceLogDo) withDO(do gen.Dao) IMsgTraceLogDo {
	_r := &msgTraceLogDo{}
	_r.DO = *do.(*gen.DO)
	_r.IWithDO = gen.WithDOFunc[IMsgTraceLogDo](m.withDO)
	return _r
}
