// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"github.com/BetaGoRobot/BetaGo-Redefine/internal/infrastructure/db/model"
)

func newPermissionGrant(db *gorm.DB, opts ...gen.DOOption) permissionGrant {
	_permissionGrant := permissionGrant{}

	_permissionGrant.permissionGrantDo.IWithDO = gen.WithDOFunc[IPermissionGrantDo](_permissionGrant.permissionGrantDo.withDO)

	_permissionGrant.permissionGrantDo.UseDB(db, opts...)
	_permissionGrant.permissionGrantDo.UseModel(&model.PermissionGrant{})

	tableName := _permissionGrant.permissionGrantDo.TableName()
	_permissionGrant.ALL = field.NewAsterisk(tableName)
	_permissionGrant.ID = field.NewInt64(tableName, "id")
	_permissionGrant.SubjectType = field.NewString(tableName, "subject_type")
	_permissionGrant.SubjectID = field.NewString(tableName, "subject_id")
	_permissionGrant.PermissionPoint = field.NewString(tableName, "permission_point")
	_permissionGrant.Scope = field.NewString(tableName, "scope")
	_permissionGrant.ResourceChatID = field.NewString(tableName, "resource_chat_id")
	_permissionGrant.ResourceUserID = field.NewString(tableName, "resource_user_id")
	_permissionGrant.Remark = field.NewString(tableName, "remark")
	_permissionGrant.CreatedAt = field.NewTime(tableName, "created_at")
	_permissionGrant.UpdatedAt = field.NewTime(tableName, "updated_at")
	_permissionGrant.DeletedAt = field.NewField(tableName, "deleted_at")
	_permissionGrant.AppID = field.NewString(tableName, "app_id")
	_permissionGrant.BotOpenID = field.NewString(tableName, "bot_open_id")

	_permissionGrant.fillFieldMap()

	return _permissionGrant
}

type permissionGrant struct {
	permissionGrantDo permissionGrantDo

	ALL             field.Asterisk
	ID              field.Int64
	SubjectType     field.String // 授权主体类型，当前固定为 user
	SubjectID       field.String // 授权主体标识，飞书侧优先使用 OpenID
	PermissionPoint field.String // 权限点，例如 config.write
	Scope           field.String // 授权作用域，例如 global/chat/user
	ResourceChatID  field.String // 作用域资源 chat_id，global scope 为空
	ResourceUserID  field.String // 作用域资源 user_id，global scope 为空
	Remark          field.String // 授权备注
	CreatedAt       field.Time
	UpdatedAt       field.Time
	DeletedAt       field.Field
	AppID           field.String // 授权所属的飞书应用 AppID
	BotOpenID       field.String // 授权所属的机器人 OpenID

	fieldMap map[string]field.Expr
}

func (p permissionGrant) Table(newTableName string) *permissionGrant {
	p.permissionGrantDo.UseTable(newTableName)
	return p.updateTableName(newTableName)
}

func (p permissionGrant) As(alias string) *permissionGrant {
	p.permissionGrantDo.DO = *(p.permissionGrantDo.As(alias).(*gen.DO))
	return p.updateTableName(alias)
}

func (p *permissionGrant) updateTableName(table string) *permissionGrant {
	p.ALL = field.NewAsterisk(table)
	p.ID = field.NewInt64(table, "id")
	p.SubjectType = field.NewString(table, "subject_type")
	p.SubjectID = field.NewString(table, "subject_id")
	p.PermissionPoint = field.NewString(table, "permission_point")
	p.Scope = field.NewString(table, "scope")
	p.ResourceChatID = field.NewString(table, "resource_chat_id")
	p.ResourceUserID = field.NewString(table, "resource_user_id")
	p.Remark = field.NewString(table, "remark")
	p.CreatedAt = field.NewTime(table, "created_at")
	p.UpdatedAt = field.NewTime(table, "updated_at")
	p.DeletedAt = field.NewField(table, "deleted_at")
	p.AppID = field.NewString(table, "app_id")
	p.BotOpenID = field.NewString(table, "bot_open_id")

	p.fillFieldMap()

	return p
}

func (p *permissionGrant) WithContext(ctx context.Context) IPermissionGrantDo {
	return p.permissionGrantDo.WithContext(ctx)
}

func (p permissionGrant) TableName() string { return p.permissionGrantDo.TableName() }

func (p permissionGrant) Alias() string { return p.permissionGrantDo.Alias() }

func (p permissionGrant) Columns(cols ...field.Expr) gen.Columns {
	return p.permissionGrantDo.Columns(cols...)
}

func (p *permissionGrant) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := p.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (p *permissionGrant) fillFieldMap() {
	p.fieldMap = make(map[string]field.Expr, 13)
	p.fieldMap["id"] = p.ID
	p.fieldMap["subject_type"] = p.SubjectType
	p.fieldMap["subject_id"] = p.SubjectID
	p.fieldMap["permission_point"] = p.PermissionPoint
	p.fieldMap["scope"] = p.Scope
	p.fieldMap["resource_chat_id"] = p.ResourceChatID
	p.fieldMap["resource_user_id"] = p.ResourceUserID
	p.fieldMap["remark"] = p.Remark
	p.fieldMap["created_at"] = p.CreatedAt
	p.fieldMap["updated_at"] = p.UpdatedAt
	p.fieldMap["deleted_at"] = p.DeletedAt
	p.fieldMap["app_id"] = p.AppID
	p.fieldMap["bot_open_id"] = p.BotOpenID
}

func (p permissionGrant) clone(db *gorm.DB) permissionGrant {
	p.permissionGrantDo.ReplaceConnPool(db.Statement.ConnPool)
	return p
}

func (p permissionGrant) replaceDB(db *gorm.DB) permissionGrant {
	p.permissionGrantDo.ReplaceDB(db)
	return p
}

type permissionGrantDo struct {
	gen.GenericsDo[IPermissionGrantDo, *model.PermissionGrant]
}
type IPermissionGrantDo interface {
	gen.IGenericsDo[IPermissionGrantDo, *model.PermissionGrant]
}

func (p *permissionGrantDo) withDO(do gen.Dao) IPermissionGrantDo {
	_r := &permissionGrantDo{}
	_r.DO = *do.(*gen.DO)
	_r.IWithDO = gen.WithDOFunc[IPermissionGrantDo](p.withDO)
	return _r
}
