// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"github.com/BetaGoRobot/BetaGo-Redefine/internal/infrastructure/db/model"
)

func newPrivateMode(db *gorm.DB, opts ...gen.DOOption) privateMode {
	_privateMode := privateMode{}

	_privateMode.privateModeDo.IWithDO = gen.WithDOFunc[IPrivateModeDo](_privateMode.privateModeDo.withDO)

	_privateMode.privateModeDo.UseDB(db, opts...)
	_privateMode.privateModeDo.UseModel(&model.PrivateMode{})

	tableName := _privateMode.privateModeDo.TableName()
	_privateMode.ALL = field.NewAsterisk(tableName)
	_privateMode.ChatID = field.NewString(tableName, "chat_id")
	_privateMode.Enable = field.NewBool(tableName, "enable")

	_privateMode.fillFieldMap()

	return _privateMode
}

type privateMode struct {
	privateModeDo privateModeDo

	ALL    field.Asterisk
	ChatID field.String
	Enable field.Bool

	fieldMap map[string]field.Expr
}

func (p privateMode) Table(newTableName string) *privateMode {
	p.privateModeDo.UseTable(newTableName)
	return p.updateTableName(newTableName)
}

func (p privateMode) As(alias string) *privateMode {
	p.privateModeDo.DO = *(p.privateModeDo.As(alias).(*gen.DO))
	return p.updateTableName(alias)
}

func (p *privateMode) updateTableName(table string) *privateMode {
	p.ALL = field.NewAsterisk(table)
	p.ChatID = field.NewString(table, "chat_id")
	p.Enable = field.NewBool(table, "enable")

	p.fillFieldMap()

	return p
}

func (p *privateMode) WithContext(ctx context.Context) IPrivateModeDo {
	return p.privateModeDo.WithContext(ctx)
}

func (p privateMode) TableName() string { return p.privateModeDo.TableName() }

func (p privateMode) Alias() string { return p.privateModeDo.Alias() }

func (p privateMode) Columns(cols ...field.Expr) gen.Columns { return p.privateModeDo.Columns(cols...) }

func (p *privateMode) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := p.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (p *privateMode) fillFieldMap() {
	p.fieldMap = make(map[string]field.Expr, 2)
	p.fieldMap["chat_id"] = p.ChatID
	p.fieldMap["enable"] = p.Enable
}

func (p privateMode) clone(db *gorm.DB) privateMode {
	p.privateModeDo.ReplaceConnPool(db.Statement.ConnPool)
	return p
}

func (p privateMode) replaceDB(db *gorm.DB) privateMode {
	p.privateModeDo.ReplaceDB(db)
	return p
}

type privateModeDo struct {
	gen.GenericsDo[IPrivateModeDo, *model.PrivateMode]
}
type IPrivateModeDo interface {
	gen.IGenericsDo[IPrivateModeDo, *model.PrivateMode]
}

func (p *privateModeDo) withDO(do gen.Dao) IPrivateModeDo {
	_r := &privateModeDo{}
	_r.DO = *do.(*gen.DO)
	_r.IWithDO = gen.WithDOFunc[IPrivateModeDo](p.withDO)
	return _r
}
