// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"github.com/BetaGoRobot/BetaGo-Redefine/internal/infrastructure/db/model"
)

func newPromptConf(db *gorm.DB, opts ...gen.DOOption) promptConf {
	_promptConf := promptConf{}

	_promptConf.promptConfDo.IWithDO = gen.WithDOFunc[IPromptConfDo](_promptConf.promptConfDo.withDO)

	_promptConf.promptConfDo.UseDB(db, opts...)
	_promptConf.promptConfDo.UseModel(&model.PromptConf{})

	tableName := _promptConf.promptConfDo.TableName()
	_promptConf.ALL = field.NewAsterisk(tableName)
	_promptConf.CreatedAt = field.NewTime(tableName, "created_at")
	_promptConf.UpdatedAt = field.NewTime(tableName, "updated_at")
	_promptConf.DeletedAt = field.NewField(tableName, "deleted_at")
	_promptConf.PromptKey = field.NewString(tableName, "prompt_key")
	_promptConf.SystemPromptTpl = field.NewString(tableName, "system_prompt_tpl")
	_promptConf.UserPromptTpl = field.NewString(tableName, "user_prompt_tpl")

	_promptConf.fillFieldMap()

	return _promptConf
}

type promptConf struct {
	promptConfDo promptConfDo

	ALL             field.Asterisk
	CreatedAt       field.Time
	UpdatedAt       field.Time
	DeletedAt       field.Field
	PromptKey       field.String
	SystemPromptTpl field.String
	UserPromptTpl   field.String

	fieldMap map[string]field.Expr
}

func (p promptConf) Table(newTableName string) *promptConf {
	p.promptConfDo.UseTable(newTableName)
	return p.updateTableName(newTableName)
}

func (p promptConf) As(alias string) *promptConf {
	p.promptConfDo.DO = *(p.promptConfDo.As(alias).(*gen.DO))
	return p.updateTableName(alias)
}

func (p *promptConf) updateTableName(table string) *promptConf {
	p.ALL = field.NewAsterisk(table)
	p.CreatedAt = field.NewTime(table, "created_at")
	p.UpdatedAt = field.NewTime(table, "updated_at")
	p.DeletedAt = field.NewField(table, "deleted_at")
	p.PromptKey = field.NewString(table, "prompt_key")
	p.SystemPromptTpl = field.NewString(table, "system_prompt_tpl")
	p.UserPromptTpl = field.NewString(table, "user_prompt_tpl")

	p.fillFieldMap()

	return p
}

func (p *promptConf) WithContext(ctx context.Context) IPromptConfDo {
	return p.promptConfDo.WithContext(ctx)
}

func (p promptConf) TableName() string { return p.promptConfDo.TableName() }

func (p promptConf) Alias() string { return p.promptConfDo.Alias() }

func (p promptConf) Columns(cols ...field.Expr) gen.Columns { return p.promptConfDo.Columns(cols...) }

func (p *promptConf) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := p.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (p *promptConf) fillFieldMap() {
	p.fieldMap = make(map[string]field.Expr, 6)
	p.fieldMap["created_at"] = p.CreatedAt
	p.fieldMap["updated_at"] = p.UpdatedAt
	p.fieldMap["deleted_at"] = p.DeletedAt
	p.fieldMap["prompt_key"] = p.PromptKey
	p.fieldMap["system_prompt_tpl"] = p.SystemPromptTpl
	p.fieldMap["user_prompt_tpl"] = p.UserPromptTpl
}

func (p promptConf) clone(db *gorm.DB) promptConf {
	p.promptConfDo.ReplaceConnPool(db.Statement.ConnPool)
	return p
}

func (p promptConf) replaceDB(db *gorm.DB) promptConf {
	p.promptConfDo.ReplaceDB(db)
	return p
}

type promptConfDo struct {
	gen.GenericsDo[IPromptConfDo, *model.PromptConf]
}
type IPromptConfDo interface {
	gen.IGenericsDo[IPromptConfDo, *model.PromptConf]
}

func (p *promptConfDo) withDO(do gen.Dao) IPromptConfDo {
	_r := &promptConfDo{}
	_r.DO = *do.(*gen.DO)
	_r.IWithDO = gen.WithDOFunc[IPromptConfDo](p.withDO)
	return _r
}
