// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"github.com/BetaGoRobot/BetaGo-Redefine/internal/infrastructure/db/model"
)

func newPromptTemplateArg(db *gorm.DB, opts ...gen.DOOption) promptTemplateArg {
	_promptTemplateArg := promptTemplateArg{}

	_promptTemplateArg.promptTemplateArgDo.IWithDO = gen.WithDOFunc[IPromptTemplateArgDo](_promptTemplateArg.promptTemplateArgDo.withDO)

	_promptTemplateArg.promptTemplateArgDo.UseDB(db, opts...)
	_promptTemplateArg.promptTemplateArgDo.UseModel(&model.PromptTemplateArg{})

	tableName := _promptTemplateArg.promptTemplateArgDo.TableName()
	_promptTemplateArg.ALL = field.NewAsterisk(tableName)
	_promptTemplateArg.PromptID = field.NewInt64(tableName, "prompt_id")
	_promptTemplateArg.TemplateStr = field.NewString(tableName, "template_str")
	_promptTemplateArg.Task = field.NewString(tableName, "task")
	_promptTemplateArg.Constraints = field.NewString(tableName, "constraints")

	_promptTemplateArg.fillFieldMap()

	return _promptTemplateArg
}

type promptTemplateArg struct {
	promptTemplateArgDo promptTemplateArgDo

	ALL         field.Asterisk
	PromptID    field.Int64
	TemplateStr field.String
	Task        field.String
	Constraints field.String

	fieldMap map[string]field.Expr
}

func (p promptTemplateArg) Table(newTableName string) *promptTemplateArg {
	p.promptTemplateArgDo.UseTable(newTableName)
	return p.updateTableName(newTableName)
}

func (p promptTemplateArg) As(alias string) *promptTemplateArg {
	p.promptTemplateArgDo.DO = *(p.promptTemplateArgDo.As(alias).(*gen.DO))
	return p.updateTableName(alias)
}

func (p *promptTemplateArg) updateTableName(table string) *promptTemplateArg {
	p.ALL = field.NewAsterisk(table)
	p.PromptID = field.NewInt64(table, "prompt_id")
	p.TemplateStr = field.NewString(table, "template_str")
	p.Task = field.NewString(table, "task")
	p.Constraints = field.NewString(table, "constraints")

	p.fillFieldMap()

	return p
}

func (p *promptTemplateArg) WithContext(ctx context.Context) IPromptTemplateArgDo {
	return p.promptTemplateArgDo.WithContext(ctx)
}

func (p promptTemplateArg) TableName() string { return p.promptTemplateArgDo.TableName() }

func (p promptTemplateArg) Alias() string { return p.promptTemplateArgDo.Alias() }

func (p promptTemplateArg) Columns(cols ...field.Expr) gen.Columns {
	return p.promptTemplateArgDo.Columns(cols...)
}

func (p *promptTemplateArg) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := p.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (p *promptTemplateArg) fillFieldMap() {
	p.fieldMap = make(map[string]field.Expr, 4)
	p.fieldMap["prompt_id"] = p.PromptID
	p.fieldMap["template_str"] = p.TemplateStr
	p.fieldMap["task"] = p.Task
	p.fieldMap["constraints"] = p.Constraints
}

func (p promptTemplateArg) clone(db *gorm.DB) promptTemplateArg {
	p.promptTemplateArgDo.ReplaceConnPool(db.Statement.ConnPool)
	return p
}

func (p promptTemplateArg) replaceDB(db *gorm.DB) promptTemplateArg {
	p.promptTemplateArgDo.ReplaceDB(db)
	return p
}

type promptTemplateArgDo struct {
	gen.GenericsDo[IPromptTemplateArgDo, *model.PromptTemplateArg]
}
type IPromptTemplateArgDo interface {
	gen.IGenericsDo[IPromptTemplateArgDo, *model.PromptTemplateArg]
}

func (p *promptTemplateArgDo) withDO(do gen.Dao) IPromptTemplateArgDo {
	_r := &promptTemplateArgDo{}
	_r.DO = *do.(*gen.DO)
	_r.IWithDO = gen.WithDOFunc[IPromptTemplateArgDo](p.withDO)
	return _r
}
