// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"github.com/BetaGoRobot/BetaGo-Redefine/internal/infrastructure/db/model"
)

func newQuoteReplyMsgCustom(db *gorm.DB, opts ...gen.DOOption) quoteReplyMsgCustom {
	_quoteReplyMsgCustom := quoteReplyMsgCustom{}

	_quoteReplyMsgCustom.quoteReplyMsgCustomDo.IWithDO = gen.WithDOFunc[IQuoteReplyMsgCustomDo](_quoteReplyMsgCustom.quoteReplyMsgCustomDo.withDO)

	_quoteReplyMsgCustom.quoteReplyMsgCustomDo.UseDB(db, opts...)
	_quoteReplyMsgCustom.quoteReplyMsgCustomDo.UseModel(&model.QuoteReplyMsgCustom{})

	tableName := _quoteReplyMsgCustom.quoteReplyMsgCustomDo.TableName()
	_quoteReplyMsgCustom.ALL = field.NewAsterisk(tableName)
	_quoteReplyMsgCustom.GuildID = field.NewString(tableName, "guild_id")
	_quoteReplyMsgCustom.MatchType = field.NewString(tableName, "match_type")
	_quoteReplyMsgCustom.Keyword = field.NewString(tableName, "keyword")
	_quoteReplyMsgCustom.Reply = field.NewString(tableName, "reply")
	_quoteReplyMsgCustom.ReplyType = field.NewString(tableName, "reply_type")

	_quoteReplyMsgCustom.fillFieldMap()

	return _quoteReplyMsgCustom
}

type quoteReplyMsgCustom struct {
	quoteReplyMsgCustomDo quoteReplyMsgCustomDo

	ALL       field.Asterisk
	GuildID   field.String
	MatchType field.String
	Keyword   field.String
	Reply     field.String
	ReplyType field.String

	fieldMap map[string]field.Expr
}

func (q quoteReplyMsgCustom) Table(newTableName string) *quoteReplyMsgCustom {
	q.quoteReplyMsgCustomDo.UseTable(newTableName)
	return q.updateTableName(newTableName)
}

func (q quoteReplyMsgCustom) As(alias string) *quoteReplyMsgCustom {
	q.quoteReplyMsgCustomDo.DO = *(q.quoteReplyMsgCustomDo.As(alias).(*gen.DO))
	return q.updateTableName(alias)
}

func (q *quoteReplyMsgCustom) updateTableName(table string) *quoteReplyMsgCustom {
	q.ALL = field.NewAsterisk(table)
	q.GuildID = field.NewString(table, "guild_id")
	q.MatchType = field.NewString(table, "match_type")
	q.Keyword = field.NewString(table, "keyword")
	q.Reply = field.NewString(table, "reply")
	q.ReplyType = field.NewString(table, "reply_type")

	q.fillFieldMap()

	return q
}

func (q *quoteReplyMsgCustom) WithContext(ctx context.Context) IQuoteReplyMsgCustomDo {
	return q.quoteReplyMsgCustomDo.WithContext(ctx)
}

func (q quoteReplyMsgCustom) TableName() string { return q.quoteReplyMsgCustomDo.TableName() }

func (q quoteReplyMsgCustom) Alias() string { return q.quoteReplyMsgCustomDo.Alias() }

func (q quoteReplyMsgCustom) Columns(cols ...field.Expr) gen.Columns {
	return q.quoteReplyMsgCustomDo.Columns(cols...)
}

func (q *quoteReplyMsgCustom) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := q.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (q *quoteReplyMsgCustom) fillFieldMap() {
	q.fieldMap = make(map[string]field.Expr, 5)
	q.fieldMap["guild_id"] = q.GuildID
	q.fieldMap["match_type"] = q.MatchType
	q.fieldMap["keyword"] = q.Keyword
	q.fieldMap["reply"] = q.Reply
	q.fieldMap["reply_type"] = q.ReplyType
}

func (q quoteReplyMsgCustom) clone(db *gorm.DB) quoteReplyMsgCustom {
	q.quoteReplyMsgCustomDo.ReplaceConnPool(db.Statement.ConnPool)
	return q
}

func (q quoteReplyMsgCustom) replaceDB(db *gorm.DB) quoteReplyMsgCustom {
	q.quoteReplyMsgCustomDo.ReplaceDB(db)
	return q
}

type quoteReplyMsgCustomDo struct {
	gen.GenericsDo[IQuoteReplyMsgCustomDo, *model.QuoteReplyMsgCustom]
}
type IQuoteReplyMsgCustomDo interface {
	gen.IGenericsDo[IQuoteReplyMsgCustomDo, *model.QuoteReplyMsgCustom]
}

func (q *quoteReplyMsgCustomDo) withDO(do gen.Dao) IQuoteReplyMsgCustomDo {
	_r := &quoteReplyMsgCustomDo{}
	_r.DO = *do.(*gen.DO)
	_r.IWithDO = gen.WithDOFunc[IQuoteReplyMsgCustomDo](q.withDO)
	return _r
}
