// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"github.com/BetaGoRobot/BetaGo-Redefine/internal/infrastructure/db/model"
)

func newReactionWhitelist(db *gorm.DB, opts ...gen.DOOption) reactionWhitelist {
	_reactionWhitelist := reactionWhitelist{}

	_reactionWhitelist.reactionWhitelistDo.IWithDO = gen.WithDOFunc[IReactionWhitelistDo](_reactionWhitelist.reactionWhitelistDo.withDO)

	_reactionWhitelist.reactionWhitelistDo.UseDB(db, opts...)
	_reactionWhitelist.reactionWhitelistDo.UseModel(&model.ReactionWhitelist{})

	tableName := _reactionWhitelist.reactionWhitelistDo.TableName()
	_reactionWhitelist.ALL = field.NewAsterisk(tableName)
	_reactionWhitelist.GuildID = field.NewString(tableName, "guild_id")

	_reactionWhitelist.fillFieldMap()

	return _reactionWhitelist
}

type reactionWhitelist struct {
	reactionWhitelistDo reactionWhitelistDo

	ALL     field.Asterisk
	GuildID field.String

	fieldMap map[string]field.Expr
}

func (r reactionWhitelist) Table(newTableName string) *reactionWhitelist {
	r.reactionWhitelistDo.UseTable(newTableName)
	return r.updateTableName(newTableName)
}

func (r reactionWhitelist) As(alias string) *reactionWhitelist {
	r.reactionWhitelistDo.DO = *(r.reactionWhitelistDo.As(alias).(*gen.DO))
	return r.updateTableName(alias)
}

func (r *reactionWhitelist) updateTableName(table string) *reactionWhitelist {
	r.ALL = field.NewAsterisk(table)
	r.GuildID = field.NewString(table, "guild_id")

	r.fillFieldMap()

	return r
}

func (r *reactionWhitelist) WithContext(ctx context.Context) IReactionWhitelistDo {
	return r.reactionWhitelistDo.WithContext(ctx)
}

func (r reactionWhitelist) TableName() string { return r.reactionWhitelistDo.TableName() }

func (r reactionWhitelist) Alias() string { return r.reactionWhitelistDo.Alias() }

func (r reactionWhitelist) Columns(cols ...field.Expr) gen.Columns {
	return r.reactionWhitelistDo.Columns(cols...)
}

func (r *reactionWhitelist) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := r.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (r *reactionWhitelist) fillFieldMap() {
	r.fieldMap = make(map[string]field.Expr, 1)
	r.fieldMap["guild_id"] = r.GuildID
}

func (r reactionWhitelist) clone(db *gorm.DB) reactionWhitelist {
	r.reactionWhitelistDo.ReplaceConnPool(db.Statement.ConnPool)
	return r
}

func (r reactionWhitelist) replaceDB(db *gorm.DB) reactionWhitelist {
	r.reactionWhitelistDo.ReplaceDB(db)
	return r
}

type reactionWhitelistDo struct {
	gen.GenericsDo[IReactionWhitelistDo, *model.ReactionWhitelist]
}
type IReactionWhitelistDo interface {
	gen.IGenericsDo[IReactionWhitelistDo, *model.ReactionWhitelist]
}

func (r *reactionWhitelistDo) withDO(do gen.Dao) IReactionWhitelistDo {
	_r := &reactionWhitelistDo{}
	_r.DO = *do.(*gen.DO)
	_r.IWithDO = gen.WithDOFunc[IReactionWhitelistDo](r.withDO)
	return _r
}
