// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"github.com/BetaGoRobot/BetaGo-Redefine/internal/infrastructure/db/model"
)

func newReactImageMeterial(db *gorm.DB, opts ...gen.DOOption) reactImageMeterial {
	_reactImageMeterial := reactImageMeterial{}

	_reactImageMeterial.reactImageMeterialDo.IWithDO = gen.WithDOFunc[IReactImageMeterialDo](_reactImageMeterial.reactImageMeterialDo.withDO)

	_reactImageMeterial.reactImageMeterialDo.UseDB(db, opts...)
	_reactImageMeterial.reactImageMeterialDo.UseModel(&model.ReactImageMeterial{})

	tableName := _reactImageMeterial.reactImageMeterialDo.TableName()
	_reactImageMeterial.ALL = field.NewAsterisk(tableName)
	_reactImageMeterial.GuildID = field.NewString(tableName, "guild_id")
	_reactImageMeterial.FileID = field.NewString(tableName, "file_id")
	_reactImageMeterial.Type = field.NewString(tableName, "type")
	_reactImageMeterial.Md5Str = field.NewString(tableName, "md5_str")

	_reactImageMeterial.fillFieldMap()

	return _reactImageMeterial
}

type reactImageMeterial struct {
	reactImageMeterialDo reactImageMeterialDo

	ALL     field.Asterisk
	GuildID field.String
	FileID  field.String
	Type    field.String
	Md5Str  field.String

	fieldMap map[string]field.Expr
}

func (r reactImageMeterial) Table(newTableName string) *reactImageMeterial {
	r.reactImageMeterialDo.UseTable(newTableName)
	return r.updateTableName(newTableName)
}

func (r reactImageMeterial) As(alias string) *reactImageMeterial {
	r.reactImageMeterialDo.DO = *(r.reactImageMeterialDo.As(alias).(*gen.DO))
	return r.updateTableName(alias)
}

func (r *reactImageMeterial) updateTableName(table string) *reactImageMeterial {
	r.ALL = field.NewAsterisk(table)
	r.GuildID = field.NewString(table, "guild_id")
	r.FileID = field.NewString(table, "file_id")
	r.Type = field.NewString(table, "type")
	r.Md5Str = field.NewString(table, "md5_str")

	r.fillFieldMap()

	return r
}

func (r *reactImageMeterial) WithContext(ctx context.Context) IReactImageMeterialDo {
	return r.reactImageMeterialDo.WithContext(ctx)
}

func (r reactImageMeterial) TableName() string { return r.reactImageMeterialDo.TableName() }

func (r reactImageMeterial) Alias() string { return r.reactImageMeterialDo.Alias() }

func (r reactImageMeterial) Columns(cols ...field.Expr) gen.Columns {
	return r.reactImageMeterialDo.Columns(cols...)
}

func (r *reactImageMeterial) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := r.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (r *reactImageMeterial) fillFieldMap() {
	r.fieldMap = make(map[string]field.Expr, 4)
	r.fieldMap["guild_id"] = r.GuildID
	r.fieldMap["file_id"] = r.FileID
	r.fieldMap["type"] = r.Type
	r.fieldMap["md5_str"] = r.Md5Str
}

func (r reactImageMeterial) clone(db *gorm.DB) reactImageMeterial {
	r.reactImageMeterialDo.ReplaceConnPool(db.Statement.ConnPool)
	return r
}

func (r reactImageMeterial) replaceDB(db *gorm.DB) reactImageMeterial {
	r.reactImageMeterialDo.ReplaceDB(db)
	return r
}

type reactImageMeterialDo struct {
	gen.GenericsDo[IReactImageMeterialDo, *model.ReactImageMeterial]
}
type IReactImageMeterialDo interface {
	gen.IGenericsDo[IReactImageMeterialDo, *model.ReactImageMeterial]
}

func (r *reactImageMeterialDo) withDO(do gen.Dao) IReactImageMeterialDo {
	_r := &reactImageMeterialDo{}
	_r.DO = *do.(*gen.DO)
	_r.IWithDO = gen.WithDOFunc[IReactImageMeterialDo](r.withDO)
	return _r
}
