// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"github.com/BetaGoRobot/BetaGo-Redefine/internal/infrastructure/db/model"
)

func newRepeatWhitelist(db *gorm.DB, opts ...gen.DOOption) repeatWhitelist {
	_repeatWhitelist := repeatWhitelist{}

	_repeatWhitelist.repeatWhitelistDo.IWithDO = gen.WithDOFunc[IRepeatWhitelistDo](_repeatWhitelist.repeatWhitelistDo.withDO)

	_repeatWhitelist.repeatWhitelistDo.UseDB(db, opts...)
	_repeatWhitelist.repeatWhitelistDo.UseModel(&model.RepeatWhitelist{})

	tableName := _repeatWhitelist.repeatWhitelistDo.TableName()
	_repeatWhitelist.ALL = field.NewAsterisk(tableName)
	_repeatWhitelist.GuildID = field.NewString(tableName, "guild_id")

	_repeatWhitelist.fillFieldMap()

	return _repeatWhitelist
}

type repeatWhitelist struct {
	repeatWhitelistDo repeatWhitelistDo

	ALL     field.Asterisk
	GuildID field.String

	fieldMap map[string]field.Expr
}

func (r repeatWhitelist) Table(newTableName string) *repeatWhitelist {
	r.repeatWhitelistDo.UseTable(newTableName)
	return r.updateTableName(newTableName)
}

func (r repeatWhitelist) As(alias string) *repeatWhitelist {
	r.repeatWhitelistDo.DO = *(r.repeatWhitelistDo.As(alias).(*gen.DO))
	return r.updateTableName(alias)
}

func (r *repeatWhitelist) updateTableName(table string) *repeatWhitelist {
	r.ALL = field.NewAsterisk(table)
	r.GuildID = field.NewString(table, "guild_id")

	r.fillFieldMap()

	return r
}

func (r *repeatWhitelist) WithContext(ctx context.Context) IRepeatWhitelistDo {
	return r.repeatWhitelistDo.WithContext(ctx)
}

func (r repeatWhitelist) TableName() string { return r.repeatWhitelistDo.TableName() }

func (r repeatWhitelist) Alias() string { return r.repeatWhitelistDo.Alias() }

func (r repeatWhitelist) Columns(cols ...field.Expr) gen.Columns {
	return r.repeatWhitelistDo.Columns(cols...)
}

func (r *repeatWhitelist) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := r.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (r *repeatWhitelist) fillFieldMap() {
	r.fieldMap = make(map[string]field.Expr, 1)
	r.fieldMap["guild_id"] = r.GuildID
}

func (r repeatWhitelist) clone(db *gorm.DB) repeatWhitelist {
	r.repeatWhitelistDo.ReplaceConnPool(db.Statement.ConnPool)
	return r
}

func (r repeatWhitelist) replaceDB(db *gorm.DB) repeatWhitelist {
	r.repeatWhitelistDo.ReplaceDB(db)
	return r
}

type repeatWhitelistDo struct {
	gen.GenericsDo[IRepeatWhitelistDo, *model.RepeatWhitelist]
}
type IRepeatWhitelistDo interface {
	gen.IGenericsDo[IRepeatWhitelistDo, *model.RepeatWhitelist]
}

func (r *repeatWhitelistDo) withDO(do gen.Dao) IRepeatWhitelistDo {
	_r := &repeatWhitelistDo{}
	_r.DO = *do.(*gen.DO)
	_r.IWithDO = gen.WithDOFunc[IRepeatWhitelistDo](r.withDO)
	return _r
}
