// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"github.com/BetaGoRobot/BetaGo-Redefine/internal/infrastructure/db/model"
)

func newRepeatWordsRateCustom(db *gorm.DB, opts ...gen.DOOption) repeatWordsRateCustom {
	_repeatWordsRateCustom := repeatWordsRateCustom{}

	_repeatWordsRateCustom.repeatWordsRateCustomDo.IWithDO = gen.WithDOFunc[IRepeatWordsRateCustomDo](_repeatWordsRateCustom.repeatWordsRateCustomDo.withDO)

	_repeatWordsRateCustom.repeatWordsRateCustomDo.UseDB(db, opts...)
	_repeatWordsRateCustom.repeatWordsRateCustomDo.UseModel(&model.RepeatWordsRateCustom{})

	tableName := _repeatWordsRateCustom.repeatWordsRateCustomDo.TableName()
	_repeatWordsRateCustom.ALL = field.NewAsterisk(tableName)
	_repeatWordsRateCustom.CreatedAt = field.NewTime(tableName, "created_at")
	_repeatWordsRateCustom.UpdatedAt = field.NewTime(tableName, "updated_at")
	_repeatWordsRateCustom.DeletedAt = field.NewField(tableName, "deleted_at")
	_repeatWordsRateCustom.GuildID = field.NewString(tableName, "guild_id")
	_repeatWordsRateCustom.Word = field.NewString(tableName, "word")
	_repeatWordsRateCustom.Rate = field.NewInt64(tableName, "rate")

	_repeatWordsRateCustom.fillFieldMap()

	return _repeatWordsRateCustom
}

type repeatWordsRateCustom struct {
	repeatWordsRateCustomDo repeatWordsRateCustomDo

	ALL       field.Asterisk
	CreatedAt field.Time
	UpdatedAt field.Time
	DeletedAt field.Field
	GuildID   field.String
	Word      field.String
	Rate      field.Int64

	fieldMap map[string]field.Expr
}

func (r repeatWordsRateCustom) Table(newTableName string) *repeatWordsRateCustom {
	r.repeatWordsRateCustomDo.UseTable(newTableName)
	return r.updateTableName(newTableName)
}

func (r repeatWordsRateCustom) As(alias string) *repeatWordsRateCustom {
	r.repeatWordsRateCustomDo.DO = *(r.repeatWordsRateCustomDo.As(alias).(*gen.DO))
	return r.updateTableName(alias)
}

func (r *repeatWordsRateCustom) updateTableName(table string) *repeatWordsRateCustom {
	r.ALL = field.NewAsterisk(table)
	r.CreatedAt = field.NewTime(table, "created_at")
	r.UpdatedAt = field.NewTime(table, "updated_at")
	r.DeletedAt = field.NewField(table, "deleted_at")
	r.GuildID = field.NewString(table, "guild_id")
	r.Word = field.NewString(table, "word")
	r.Rate = field.NewInt64(table, "rate")

	r.fillFieldMap()

	return r
}

func (r *repeatWordsRateCustom) WithContext(ctx context.Context) IRepeatWordsRateCustomDo {
	return r.repeatWordsRateCustomDo.WithContext(ctx)
}

func (r repeatWordsRateCustom) TableName() string { return r.repeatWordsRateCustomDo.TableName() }

func (r repeatWordsRateCustom) Alias() string { return r.repeatWordsRateCustomDo.Alias() }

func (r repeatWordsRateCustom) Columns(cols ...field.Expr) gen.Columns {
	return r.repeatWordsRateCustomDo.Columns(cols...)
}

func (r *repeatWordsRateCustom) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := r.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (r *repeatWordsRateCustom) fillFieldMap() {
	r.fieldMap = make(map[string]field.Expr, 6)
	r.fieldMap["created_at"] = r.CreatedAt
	r.fieldMap["updated_at"] = r.UpdatedAt
	r.fieldMap["deleted_at"] = r.DeletedAt
	r.fieldMap["guild_id"] = r.GuildID
	r.fieldMap["word"] = r.Word
	r.fieldMap["rate"] = r.Rate
}

func (r repeatWordsRateCustom) clone(db *gorm.DB) repeatWordsRateCustom {
	r.repeatWordsRateCustomDo.ReplaceConnPool(db.Statement.ConnPool)
	return r
}

func (r repeatWordsRateCustom) replaceDB(db *gorm.DB) repeatWordsRateCustom {
	r.repeatWordsRateCustomDo.ReplaceDB(db)
	return r
}

type repeatWordsRateCustomDo struct {
	gen.GenericsDo[IRepeatWordsRateCustomDo, *model.RepeatWordsRateCustom]
}
type IRepeatWordsRateCustomDo interface {
	gen.IGenericsDo[IRepeatWordsRateCustomDo, *model.RepeatWordsRateCustom]
}

func (r *repeatWordsRateCustomDo) withDO(do gen.Dao) IRepeatWordsRateCustomDo {
	_r := &repeatWordsRateCustomDo{}
	_r.DO = *do.(*gen.DO)
	_r.IWithDO = gen.WithDOFunc[IRepeatWordsRateCustomDo](r.withDO)
	return _r
}
