// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"github.com/BetaGoRobot/BetaGo-Redefine/internal/infrastructure/db/model"
)

func newRepeatWordsRate(db *gorm.DB, opts ...gen.DOOption) repeatWordsRate {
	_repeatWordsRate := repeatWordsRate{}

	_repeatWordsRate.repeatWordsRateDo.IWithDO = gen.WithDOFunc[IRepeatWordsRateDo](_repeatWordsRate.repeatWordsRateDo.withDO)

	_repeatWordsRate.repeatWordsRateDo.UseDB(db, opts...)
	_repeatWordsRate.repeatWordsRateDo.UseModel(&model.RepeatWordsRate{})

	tableName := _repeatWordsRate.repeatWordsRateDo.TableName()
	_repeatWordsRate.ALL = field.NewAsterisk(tableName)
	_repeatWordsRate.Word = field.NewString(tableName, "word")
	_repeatWordsRate.Rate = field.NewInt64(tableName, "rate")
	_repeatWordsRate.ID = field.NewInt64(tableName, "id")
	_repeatWordsRate.CreatedAt = field.NewTime(tableName, "created_at")
	_repeatWordsRate.UpdatedAt = field.NewTime(tableName, "updated_at")
	_repeatWordsRate.DeletedAt = field.NewField(tableName, "deleted_at")

	_repeatWordsRate.fillFieldMap()

	return _repeatWordsRate
}

type repeatWordsRate struct {
	repeatWordsRateDo repeatWordsRateDo

	ALL       field.Asterisk
	Word      field.String
	Rate      field.Int64
	ID        field.Int64
	CreatedAt field.Time
	UpdatedAt field.Time
	DeletedAt field.Field

	fieldMap map[string]field.Expr
}

func (r repeatWordsRate) Table(newTableName string) *repeatWordsRate {
	r.repeatWordsRateDo.UseTable(newTableName)
	return r.updateTableName(newTableName)
}

func (r repeatWordsRate) As(alias string) *repeatWordsRate {
	r.repeatWordsRateDo.DO = *(r.repeatWordsRateDo.As(alias).(*gen.DO))
	return r.updateTableName(alias)
}

func (r *repeatWordsRate) updateTableName(table string) *repeatWordsRate {
	r.ALL = field.NewAsterisk(table)
	r.Word = field.NewString(table, "word")
	r.Rate = field.NewInt64(table, "rate")
	r.ID = field.NewInt64(table, "id")
	r.CreatedAt = field.NewTime(table, "created_at")
	r.UpdatedAt = field.NewTime(table, "updated_at")
	r.DeletedAt = field.NewField(table, "deleted_at")

	r.fillFieldMap()

	return r
}

func (r *repeatWordsRate) WithContext(ctx context.Context) IRepeatWordsRateDo {
	return r.repeatWordsRateDo.WithContext(ctx)
}

func (r repeatWordsRate) TableName() string { return r.repeatWordsRateDo.TableName() }

func (r repeatWordsRate) Alias() string { return r.repeatWordsRateDo.Alias() }

func (r repeatWordsRate) Columns(cols ...field.Expr) gen.Columns {
	return r.repeatWordsRateDo.Columns(cols...)
}

func (r *repeatWordsRate) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := r.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (r *repeatWordsRate) fillFieldMap() {
	r.fieldMap = make(map[string]field.Expr, 6)
	r.fieldMap["word"] = r.Word
	r.fieldMap["rate"] = r.Rate
	r.fieldMap["id"] = r.ID
	r.fieldMap["created_at"] = r.CreatedAt
	r.fieldMap["updated_at"] = r.UpdatedAt
	r.fieldMap["deleted_at"] = r.DeletedAt
}

func (r repeatWordsRate) clone(db *gorm.DB) repeatWordsRate {
	r.repeatWordsRateDo.ReplaceConnPool(db.Statement.ConnPool)
	return r
}

func (r repeatWordsRate) replaceDB(db *gorm.DB) repeatWordsRate {
	r.repeatWordsRateDo.ReplaceDB(db)
	return r
}

type repeatWordsRateDo struct {
	gen.GenericsDo[IRepeatWordsRateDo, *model.RepeatWordsRate]
}
type IRepeatWordsRateDo interface {
	gen.IGenericsDo[IRepeatWordsRateDo, *model.RepeatWordsRate]
}

func (r *repeatWordsRateDo) withDO(do gen.Dao) IRepeatWordsRateDo {
	_r := &repeatWordsRateDo{}
	_r.DO = *do.(*gen.DO)
	_r.IWithDO = gen.WithDOFunc[IRepeatWordsRateDo](r.withDO)
	return _r
}
