// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"github.com/BetaGoRobot/BetaGo-Redefine/internal/infrastructure/db/model"
)

func newRuntimeSchemaMigration(db *gorm.DB, opts ...gen.DOOption) runtimeSchemaMigration {
	_runtimeSchemaMigration := runtimeSchemaMigration{}

	_runtimeSchemaMigration.runtimeSchemaMigrationDo.IWithDO = gen.WithDOFunc[IRuntimeSchemaMigrationDo](_runtimeSchemaMigration.runtimeSchemaMigrationDo.withDO)

	_runtimeSchemaMigration.runtimeSchemaMigrationDo.UseDB(db, opts...)
	_runtimeSchemaMigration.runtimeSchemaMigrationDo.UseModel(&model.RuntimeSchemaMigration{})

	tableName := _runtimeSchemaMigration.runtimeSchemaMigrationDo.TableName()
	_runtimeSchemaMigration.ALL = field.NewAsterisk(tableName)
	_runtimeSchemaMigration.Version = field.NewString(tableName, "version")
	_runtimeSchemaMigration.Checksum = field.NewString(tableName, "checksum")
	_runtimeSchemaMigration.BinaryRevision = field.NewString(tableName, "binary_revision")
	_runtimeSchemaMigration.AppliedAt = field.NewTime(tableName, "applied_at")

	_runtimeSchemaMigration.fillFieldMap()

	return _runtimeSchemaMigration
}

type runtimeSchemaMigration struct {
	runtimeSchemaMigrationDo runtimeSchemaMigrationDo

	ALL            field.Asterisk
	Version        field.String
	Checksum       field.String
	BinaryRevision field.String
	AppliedAt      field.Time

	fieldMap map[string]field.Expr
}

func (r runtimeSchemaMigration) Table(newTableName string) *runtimeSchemaMigration {
	r.runtimeSchemaMigrationDo.UseTable(newTableName)
	return r.updateTableName(newTableName)
}

func (r runtimeSchemaMigration) As(alias string) *runtimeSchemaMigration {
	r.runtimeSchemaMigrationDo.DO = *(r.runtimeSchemaMigrationDo.As(alias).(*gen.DO))
	return r.updateTableName(alias)
}

func (r *runtimeSchemaMigration) updateTableName(table string) *runtimeSchemaMigration {
	r.ALL = field.NewAsterisk(table)
	r.Version = field.NewString(table, "version")
	r.Checksum = field.NewString(table, "checksum")
	r.BinaryRevision = field.NewString(table, "binary_revision")
	r.AppliedAt = field.NewTime(table, "applied_at")

	r.fillFieldMap()

	return r
}

func (r *runtimeSchemaMigration) WithContext(ctx context.Context) IRuntimeSchemaMigrationDo {
	return r.runtimeSchemaMigrationDo.WithContext(ctx)
}

func (r runtimeSchemaMigration) TableName() string { return r.runtimeSchemaMigrationDo.TableName() }

func (r runtimeSchemaMigration) Alias() string { return r.runtimeSchemaMigrationDo.Alias() }

func (r runtimeSchemaMigration) Columns(cols ...field.Expr) gen.Columns {
	return r.runtimeSchemaMigrationDo.Columns(cols...)
}

func (r *runtimeSchemaMigration) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := r.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (r *runtimeSchemaMigration) fillFieldMap() {
	r.fieldMap = make(map[string]field.Expr, 4)
	r.fieldMap["version"] = r.Version
	r.fieldMap["checksum"] = r.Checksum
	r.fieldMap["binary_revision"] = r.BinaryRevision
	r.fieldMap["applied_at"] = r.AppliedAt
}

func (r runtimeSchemaMigration) clone(db *gorm.DB) runtimeSchemaMigration {
	r.runtimeSchemaMigrationDo.ReplaceConnPool(db.Statement.ConnPool)
	return r
}

func (r runtimeSchemaMigration) replaceDB(db *gorm.DB) runtimeSchemaMigration {
	r.runtimeSchemaMigrationDo.ReplaceDB(db)
	return r
}

type runtimeSchemaMigrationDo struct {
	gen.GenericsDo[IRuntimeSchemaMigrationDo, *model.RuntimeSchemaMigration]
}
type IRuntimeSchemaMigrationDo interface {
	gen.IGenericsDo[IRuntimeSchemaMigrationDo, *model.RuntimeSchemaMigration]
}

func (r *runtimeSchemaMigrationDo) withDO(do gen.Dao) IRuntimeSchemaMigrationDo {
	_r := &runtimeSchemaMigrationDo{}
	_r.DO = *do.(*gen.DO)
	_r.IWithDO = gen.WithDOFunc[IRuntimeSchemaMigrationDo](r.withDO)
	return _r
}
