// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"github.com/BetaGoRobot/BetaGo-Redefine/internal/infrastructure/db/model"
)

func newScheduledTask(db *gorm.DB, opts ...gen.DOOption) scheduledTask {
	_scheduledTask := scheduledTask{}

	_scheduledTask.scheduledTaskDo.IWithDO = gen.WithDOFunc[IScheduledTaskDo](_scheduledTask.scheduledTaskDo.withDO)

	_scheduledTask.scheduledTaskDo.UseDB(db, opts...)
	_scheduledTask.scheduledTaskDo.UseModel(&model.ScheduledTask{})

	tableName := _scheduledTask.scheduledTaskDo.TableName()
	_scheduledTask.ALL = field.NewAsterisk(tableName)
	_scheduledTask.ID = field.NewString(tableName, "id")
	_scheduledTask.Name = field.NewString(tableName, "name")
	_scheduledTask.Type = field.NewString(tableName, "type")
	_scheduledTask.ChatID = field.NewString(tableName, "chat_id")
	_scheduledTask.AppID = field.NewString(tableName, "app_id")
	_scheduledTask.BotOpenID = field.NewString(tableName, "bot_open_id")
	_scheduledTask.CreatorID = field.NewString(tableName, "creator_id")
	_scheduledTask.ToolName = field.NewString(tableName, "tool_name")
	_scheduledTask.ToolArgs = field.NewString(tableName, "tool_args")
	_scheduledTask.RunAt = field.NewTime(tableName, "run_at")
	_scheduledTask.CronExpr = field.NewString(tableName, "cron_expr")
	_scheduledTask.Timezone = field.NewString(tableName, "timezone")
	_scheduledTask.Status = field.NewString(tableName, "status")
	_scheduledTask.NotifyOnError = field.NewBool(tableName, "notify_on_error")
	_scheduledTask.NotifyResult = field.NewBool(tableName, "notify_result")
	_scheduledTask.LastRunAt = field.NewTime(tableName, "last_run_at")
	_scheduledTask.NextRunAt = field.NewTime(tableName, "next_run_at")
	_scheduledTask.LastError = field.NewString(tableName, "last_error")
	_scheduledTask.LastResult = field.NewString(tableName, "last_result")
	_scheduledTask.RunCount = field.NewInt64(tableName, "run_count")
	_scheduledTask.CreatedAt = field.NewTime(tableName, "created_at")
	_scheduledTask.UpdatedAt = field.NewTime(tableName, "updated_at")

	_scheduledTask.fillFieldMap()

	return _scheduledTask
}

type scheduledTask struct {
	scheduledTaskDo scheduledTaskDo

	ALL           field.Asterisk
	ID            field.String
	Name          field.String
	Type          field.String // 调度类型: once, cron
	ChatID        field.String
	AppID         field.String
	BotOpenID     field.String
	CreatorID     field.String
	ToolName      field.String // 要执行的工具名称
	ToolArgs      field.String // 工具参数 JSON
	RunAt         field.Time   // 单次 schedule 的执行时间
	CronExpr      field.String // cron schedule 的标准 5 段表达式
	Timezone      field.String
	Status        field.String // 任务状态: enabled, paused, completed, disabled
	NotifyOnError field.Bool
	NotifyResult  field.Bool
	LastRunAt     field.Time
	NextRunAt     field.Time
	LastError     field.String
	LastResult    field.String
	RunCount      field.Int64
	CreatedAt     field.Time
	UpdatedAt     field.Time

	fieldMap map[string]field.Expr
}

func (s scheduledTask) Table(newTableName string) *scheduledTask {
	s.scheduledTaskDo.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

func (s scheduledTask) As(alias string) *scheduledTask {
	s.scheduledTaskDo.DO = *(s.scheduledTaskDo.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *scheduledTask) updateTableName(table string) *scheduledTask {
	s.ALL = field.NewAsterisk(table)
	s.ID = field.NewString(table, "id")
	s.Name = field.NewString(table, "name")
	s.Type = field.NewString(table, "type")
	s.ChatID = field.NewString(table, "chat_id")
	s.AppID = field.NewString(table, "app_id")
	s.BotOpenID = field.NewString(table, "bot_open_id")
	s.CreatorID = field.NewString(table, "creator_id")
	s.ToolName = field.NewString(table, "tool_name")
	s.ToolArgs = field.NewString(table, "tool_args")
	s.RunAt = field.NewTime(table, "run_at")
	s.CronExpr = field.NewString(table, "cron_expr")
	s.Timezone = field.NewString(table, "timezone")
	s.Status = field.NewString(table, "status")
	s.NotifyOnError = field.NewBool(table, "notify_on_error")
	s.NotifyResult = field.NewBool(table, "notify_result")
	s.LastRunAt = field.NewTime(table, "last_run_at")
	s.NextRunAt = field.NewTime(table, "next_run_at")
	s.LastError = field.NewString(table, "last_error")
	s.LastResult = field.NewString(table, "last_result")
	s.RunCount = field.NewInt64(table, "run_count")
	s.CreatedAt = field.NewTime(table, "created_at")
	s.UpdatedAt = field.NewTime(table, "updated_at")

	s.fillFieldMap()

	return s
}

func (s *scheduledTask) WithContext(ctx context.Context) IScheduledTaskDo {
	return s.scheduledTaskDo.WithContext(ctx)
}

func (s scheduledTask) TableName() string { return s.scheduledTaskDo.TableName() }

func (s scheduledTask) Alias() string { return s.scheduledTaskDo.Alias() }

func (s scheduledTask) Columns(cols ...field.Expr) gen.Columns {
	return s.scheduledTaskDo.Columns(cols...)
}

func (s *scheduledTask) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *scheduledTask) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 22)
	s.fieldMap["id"] = s.ID
	s.fieldMap["name"] = s.Name
	s.fieldMap["type"] = s.Type
	s.fieldMap["chat_id"] = s.ChatID
	s.fieldMap["app_id"] = s.AppID
	s.fieldMap["bot_open_id"] = s.BotOpenID
	s.fieldMap["creator_id"] = s.CreatorID
	s.fieldMap["tool_name"] = s.ToolName
	s.fieldMap["tool_args"] = s.ToolArgs
	s.fieldMap["run_at"] = s.RunAt
	s.fieldMap["cron_expr"] = s.CronExpr
	s.fieldMap["timezone"] = s.Timezone
	s.fieldMap["status"] = s.Status
	s.fieldMap["notify_on_error"] = s.NotifyOnError
	s.fieldMap["notify_result"] = s.NotifyResult
	s.fieldMap["last_run_at"] = s.LastRunAt
	s.fieldMap["next_run_at"] = s.NextRunAt
	s.fieldMap["last_error"] = s.LastError
	s.fieldMap["last_result"] = s.LastResult
	s.fieldMap["run_count"] = s.RunCount
	s.fieldMap["created_at"] = s.CreatedAt
	s.fieldMap["updated_at"] = s.UpdatedAt
}

func (s scheduledTask) clone(db *gorm.DB) scheduledTask {
	s.scheduledTaskDo.ReplaceConnPool(db.Statement.ConnPool)
	return s
}

func (s scheduledTask) replaceDB(db *gorm.DB) scheduledTask {
	s.scheduledTaskDo.ReplaceDB(db)
	return s
}

type scheduledTaskDo struct {
	gen.GenericsDo[IScheduledTaskDo, *model.ScheduledTask]
}
type IScheduledTaskDo interface {
	gen.IGenericsDo[IScheduledTaskDo, *model.ScheduledTask]
}

func (s *scheduledTaskDo) withDO(do gen.Dao) IScheduledTaskDo {
	_r := &scheduledTaskDo{}
	_r.DO = *do.(*gen.DO)
	_r.IWithDO = gen.WithDOFunc[IScheduledTaskDo](s.withDO)
	return _r
}
