// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"github.com/BetaGoRobot/BetaGo-Redefine/internal/infrastructure/db/model"
)

func newStickerMapping(db *gorm.DB, opts ...gen.DOOption) stickerMapping {
	_stickerMapping := stickerMapping{}

	_stickerMapping.stickerMappingDo.IWithDO = gen.WithDOFunc[IStickerMappingDo](_stickerMapping.stickerMappingDo.withDO)

	_stickerMapping.stickerMappingDo.UseDB(db, opts...)
	_stickerMapping.stickerMappingDo.UseModel(&model.StickerMapping{})

	tableName := _stickerMapping.stickerMappingDo.TableName()
	_stickerMapping.ALL = field.NewAsterisk(tableName)
	_stickerMapping.CreatedAt = field.NewTime(tableName, "created_at")
	_stickerMapping.UpdatedAt = field.NewTime(tableName, "updated_at")
	_stickerMapping.DeletedAt = field.NewField(tableName, "deleted_at")
	_stickerMapping.StickerKey = field.NewString(tableName, "sticker_key")
	_stickerMapping.ImageKey = field.NewString(tableName, "image_key")

	_stickerMapping.fillFieldMap()

	return _stickerMapping
}

type stickerMapping struct {
	stickerMappingDo stickerMappingDo

	ALL        field.Asterisk
	CreatedAt  field.Time
	UpdatedAt  field.Time
	DeletedAt  field.Field
	StickerKey field.String
	ImageKey   field.String

	fieldMap map[string]field.Expr
}

func (s stickerMapping) Table(newTableName string) *stickerMapping {
	s.stickerMappingDo.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

func (s stickerMapping) As(alias string) *stickerMapping {
	s.stickerMappingDo.DO = *(s.stickerMappingDo.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *stickerMapping) updateTableName(table string) *stickerMapping {
	s.ALL = field.NewAsterisk(table)
	s.CreatedAt = field.NewTime(table, "created_at")
	s.UpdatedAt = field.NewTime(table, "updated_at")
	s.DeletedAt = field.NewField(table, "deleted_at")
	s.StickerKey = field.NewString(table, "sticker_key")
	s.ImageKey = field.NewString(table, "image_key")

	s.fillFieldMap()

	return s
}

func (s *stickerMapping) WithContext(ctx context.Context) IStickerMappingDo {
	return s.stickerMappingDo.WithContext(ctx)
}

func (s stickerMapping) TableName() string { return s.stickerMappingDo.TableName() }

func (s stickerMapping) Alias() string { return s.stickerMappingDo.Alias() }

func (s stickerMapping) Columns(cols ...field.Expr) gen.Columns {
	return s.stickerMappingDo.Columns(cols...)
}

func (s *stickerMapping) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *stickerMapping) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 5)
	s.fieldMap["created_at"] = s.CreatedAt
	s.fieldMap["updated_at"] = s.UpdatedAt
	s.fieldMap["deleted_at"] = s.DeletedAt
	s.fieldMap["sticker_key"] = s.StickerKey
	s.fieldMap["image_key"] = s.ImageKey
}

func (s stickerMapping) clone(db *gorm.DB) stickerMapping {
	s.stickerMappingDo.ReplaceConnPool(db.Statement.ConnPool)
	return s
}

func (s stickerMapping) replaceDB(db *gorm.DB) stickerMapping {
	s.stickerMappingDo.ReplaceDB(db)
	return s
}

type stickerMappingDo struct {
	gen.GenericsDo[IStickerMappingDo, *model.StickerMapping]
}
type IStickerMappingDo interface {
	gen.IGenericsDo[IStickerMappingDo, *model.StickerMapping]
}

func (s *stickerMappingDo) withDO(do gen.Dao) IStickerMappingDo {
	_r := &stickerMappingDo{}
	_r.DO = *do.(*gen.DO)
	_r.IWithDO = gen.WithDOFunc[IStickerMappingDo](s.withDO)
	return _r
}
