// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"github.com/BetaGoRobot/BetaGo-Redefine/internal/infrastructure/db/model"
)

func newTemplateVersion(db *gorm.DB, opts ...gen.DOOption) templateVersion {
	_templateVersion := templateVersion{}

	_templateVersion.templateVersionDo.IWithDO = gen.WithDOFunc[ITemplateVersionDo](_templateVersion.templateVersionDo.withDO)

	_templateVersion.templateVersionDo.UseDB(db, opts...)
	_templateVersion.templateVersionDo.UseModel(&model.TemplateVersion{})

	tableName := _templateVersion.templateVersionDo.TableName()
	_templateVersion.ALL = field.NewAsterisk(tableName)
	_templateVersion.TemplateID = field.NewString(tableName, "template_id")
	_templateVersion.TemplateVersion = field.NewString(tableName, "template_version")
	_templateVersion.CreatedAt = field.NewTime(tableName, "created_at")
	_templateVersion.UpdatedAt = field.NewTime(tableName, "updated_at")
	_templateVersion.TemplateSrc = field.NewString(tableName, "template_src")

	_templateVersion.fillFieldMap()

	return _templateVersion
}

type templateVersion struct {
	templateVersionDo templateVersionDo

	ALL             field.Asterisk
	TemplateID      field.String
	TemplateVersion field.String
	CreatedAt       field.Time
	UpdatedAt       field.Time
	TemplateSrc     field.String

	fieldMap map[string]field.Expr
}

func (t templateVersion) Table(newTableName string) *templateVersion {
	t.templateVersionDo.UseTable(newTableName)
	return t.updateTableName(newTableName)
}

func (t templateVersion) As(alias string) *templateVersion {
	t.templateVersionDo.DO = *(t.templateVersionDo.As(alias).(*gen.DO))
	return t.updateTableName(alias)
}

func (t *templateVersion) updateTableName(table string) *templateVersion {
	t.ALL = field.NewAsterisk(table)
	t.TemplateID = field.NewString(table, "template_id")
	t.TemplateVersion = field.NewString(table, "template_version")
	t.CreatedAt = field.NewTime(table, "created_at")
	t.UpdatedAt = field.NewTime(table, "updated_at")
	t.TemplateSrc = field.NewString(table, "template_src")

	t.fillFieldMap()

	return t
}

func (t *templateVersion) WithContext(ctx context.Context) ITemplateVersionDo {
	return t.templateVersionDo.WithContext(ctx)
}

func (t templateVersion) TableName() string { return t.templateVersionDo.TableName() }

func (t templateVersion) Alias() string { return t.templateVersionDo.Alias() }

func (t templateVersion) Columns(cols ...field.Expr) gen.Columns {
	return t.templateVersionDo.Columns(cols...)
}

func (t *templateVersion) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := t.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (t *templateVersion) fillFieldMap() {
	t.fieldMap = make(map[string]field.Expr, 5)
	t.fieldMap["template_id"] = t.TemplateID
	t.fieldMap["template_version"] = t.TemplateVersion
	t.fieldMap["created_at"] = t.CreatedAt
	t.fieldMap["updated_at"] = t.UpdatedAt
	t.fieldMap["template_src"] = t.TemplateSrc
}

func (t templateVersion) clone(db *gorm.DB) templateVersion {
	t.templateVersionDo.ReplaceConnPool(db.Statement.ConnPool)
	return t
}

func (t templateVersion) replaceDB(db *gorm.DB) templateVersion {
	t.templateVersionDo.ReplaceDB(db)
	return t
}

type templateVersionDo struct {
	gen.GenericsDo[ITemplateVersionDo, *model.TemplateVersion]
}
type ITemplateVersionDo interface {
	gen.IGenericsDo[ITemplateVersionDo, *model.TemplateVersion]
}

func (t *templateVersionDo) withDO(do gen.Dao) ITemplateVersionDo {
	_r := &templateVersionDo{}
	_r.DO = *do.(*gen.DO)
	_r.IWithDO = gen.WithDOFunc[ITemplateVersionDo](t.withDO)
	return _r
}
