// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"github.com/BetaGoRobot/BetaGo-Redefine/internal/infrastructure/db/model"
)

func newTodoReminder(db *gorm.DB, opts ...gen.DOOption) todoReminder {
	_todoReminder := todoReminder{}

	_todoReminder.todoReminderDo.IWithDO = gen.WithDOFunc[ITodoReminderDo](_todoReminder.todoReminderDo.withDO)

	_todoReminder.todoReminderDo.UseDB(db, opts...)
	_todoReminder.todoReminderDo.UseModel(&model.TodoReminder{})

	tableName := _todoReminder.todoReminderDo.TableName()
	_todoReminder.ALL = field.NewAsterisk(tableName)
	_todoReminder.ID = field.NewString(tableName, "id")
	_todoReminder.TodoID = field.NewString(tableName, "todo_id")
	_todoReminder.ChatID = field.NewString(tableName, "chat_id")
	_todoReminder.CreatorID = field.NewString(tableName, "creator_id")
	_todoReminder.Title = field.NewString(tableName, "title")
	_todoReminder.Content = field.NewString(tableName, "content")
	_todoReminder.Type = field.NewString(tableName, "type")
	_todoReminder.Status = field.NewString(tableName, "status")
	_todoReminder.TriggerAt = field.NewTime(tableName, "trigger_at")
	_todoReminder.RepeatRule = field.NewString(tableName, "repeat_rule")
	_todoReminder.CreatedAt = field.NewTime(tableName, "created_at")
	_todoReminder.UpdatedAt = field.NewTime(tableName, "updated_at")

	_todoReminder.fillFieldMap()

	return _todoReminder
}

type todoReminder struct {
	todoReminderDo todoReminderDo

	ALL        field.Asterisk
	ID         field.String
	TodoID     field.String
	ChatID     field.String
	CreatorID  field.String
	Title      field.String
	Content    field.String
	Type       field.String // 提醒类型: once, daily, weekly, monthly, custom
	Status     field.String // 提醒状态: pending, triggered, cancelled
	TriggerAt  field.Time
	RepeatRule field.String
	CreatedAt  field.Time
	UpdatedAt  field.Time

	fieldMap map[string]field.Expr
}

func (t todoReminder) Table(newTableName string) *todoReminder {
	t.todoReminderDo.UseTable(newTableName)
	return t.updateTableName(newTableName)
}

func (t todoReminder) As(alias string) *todoReminder {
	t.todoReminderDo.DO = *(t.todoReminderDo.As(alias).(*gen.DO))
	return t.updateTableName(alias)
}

func (t *todoReminder) updateTableName(table string) *todoReminder {
	t.ALL = field.NewAsterisk(table)
	t.ID = field.NewString(table, "id")
	t.TodoID = field.NewString(table, "todo_id")
	t.ChatID = field.NewString(table, "chat_id")
	t.CreatorID = field.NewString(table, "creator_id")
	t.Title = field.NewString(table, "title")
	t.Content = field.NewString(table, "content")
	t.Type = field.NewString(table, "type")
	t.Status = field.NewString(table, "status")
	t.TriggerAt = field.NewTime(table, "trigger_at")
	t.RepeatRule = field.NewString(table, "repeat_rule")
	t.CreatedAt = field.NewTime(table, "created_at")
	t.UpdatedAt = field.NewTime(table, "updated_at")

	t.fillFieldMap()

	return t
}

func (t *todoReminder) WithContext(ctx context.Context) ITodoReminderDo {
	return t.todoReminderDo.WithContext(ctx)
}

func (t todoReminder) TableName() string { return t.todoReminderDo.TableName() }

func (t todoReminder) Alias() string { return t.todoReminderDo.Alias() }

func (t todoReminder) Columns(cols ...field.Expr) gen.Columns {
	return t.todoReminderDo.Columns(cols...)
}

func (t *todoReminder) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := t.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (t *todoReminder) fillFieldMap() {
	t.fieldMap = make(map[string]field.Expr, 12)
	t.fieldMap["id"] = t.ID
	t.fieldMap["todo_id"] = t.TodoID
	t.fieldMap["chat_id"] = t.ChatID
	t.fieldMap["creator_id"] = t.CreatorID
	t.fieldMap["title"] = t.Title
	t.fieldMap["content"] = t.Content
	t.fieldMap["type"] = t.Type
	t.fieldMap["status"] = t.Status
	t.fieldMap["trigger_at"] = t.TriggerAt
	t.fieldMap["repeat_rule"] = t.RepeatRule
	t.fieldMap["created_at"] = t.CreatedAt
	t.fieldMap["updated_at"] = t.UpdatedAt
}

func (t todoReminder) clone(db *gorm.DB) todoReminder {
	t.todoReminderDo.ReplaceConnPool(db.Statement.ConnPool)
	return t
}

func (t todoReminder) replaceDB(db *gorm.DB) todoReminder {
	t.todoReminderDo.ReplaceDB(db)
	return t
}

type todoReminderDo struct {
	gen.GenericsDo[ITodoReminderDo, *model.TodoReminder]
}
type ITodoReminderDo interface {
	gen.IGenericsDo[ITodoReminderDo, *model.TodoReminder]
}

func (t *todoReminderDo) withDO(do gen.Dao) ITodoReminderDo {
	_r := &todoReminderDo{}
	_r.DO = *do.(*gen.DO)
	_r.IWithDO = gen.WithDOFunc[ITodoReminderDo](t.withDO)
	return _r
}
