// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"github.com/BetaGoRobot/BetaGo-Redefine/internal/infrastructure/db/model"
)

func newTodoItem(db *gorm.DB, opts ...gen.DOOption) todoItem {
	_todoItem := todoItem{}

	_todoItem.todoItemDo.IWithDO = gen.WithDOFunc[ITodoItemDo](_todoItem.todoItemDo.withDO)

	_todoItem.todoItemDo.UseDB(db, opts...)
	_todoItem.todoItemDo.UseModel(&model.TodoItem{})

	tableName := _todoItem.todoItemDo.TableName()
	_todoItem.ALL = field.NewAsterisk(tableName)
	_todoItem.ID = field.NewString(tableName, "id")
	_todoItem.ChatID = field.NewString(tableName, "chat_id")
	_todoItem.AppID = field.NewString(tableName, "app_id")
	_todoItem.BotOpenID = field.NewString(tableName, "bot_open_id")
	_todoItem.CreatorID = field.NewString(tableName, "creator_id")
	_todoItem.CreatorName = field.NewString(tableName, "creator_name")
	_todoItem.AssigneeID = field.NewString(tableName, "assignee_id")
	_todoItem.Title = field.NewString(tableName, "title")
	_todoItem.Description = field.NewString(tableName, "description")
	_todoItem.Status = field.NewString(tableName, "status")
	_todoItem.Priority = field.NewString(tableName, "priority")
	_todoItem.DueAt = field.NewTime(tableName, "due_at")
	_todoItem.CompletedAt = field.NewTime(tableName, "completed_at")
	_todoItem.Tags = field.NewField(tableName, "tags")
	_todoItem.CreatedAt = field.NewTime(tableName, "created_at")
	_todoItem.UpdatedAt = field.NewTime(tableName, "updated_at")

	_todoItem.fillFieldMap()

	return _todoItem
}

type todoItem struct {
	todoItemDo todoItemDo

	ALL         field.Asterisk
	ID          field.String
	ChatID      field.String
	AppID       field.String
	BotOpenID   field.String
	CreatorID   field.String
	CreatorName field.String
	AssigneeID  field.String
	Title       field.String
	Description field.String
	Status      field.String // 状态: pending, doing, done, cancelled
	Priority    field.String // 优先级: low, medium, high, urgent
	DueAt       field.Time
	CompletedAt field.Time
	Tags        field.Field
	CreatedAt   field.Time
	UpdatedAt   field.Time

	fieldMap map[string]field.Expr
}

func (t todoItem) Table(newTableName string) *todoItem {
	t.todoItemDo.UseTable(newTableName)
	return t.updateTableName(newTableName)
}

func (t todoItem) As(alias string) *todoItem {
	t.todoItemDo.DO = *(t.todoItemDo.As(alias).(*gen.DO))
	return t.updateTableName(alias)
}

func (t *todoItem) updateTableName(table string) *todoItem {
	t.ALL = field.NewAsterisk(table)
	t.ID = field.NewString(table, "id")
	t.ChatID = field.NewString(table, "chat_id")
	t.AppID = field.NewString(table, "app_id")
	t.BotOpenID = field.NewString(table, "bot_open_id")
	t.CreatorID = field.NewString(table, "creator_id")
	t.CreatorName = field.NewString(table, "creator_name")
	t.AssigneeID = field.NewString(table, "assignee_id")
	t.Title = field.NewString(table, "title")
	t.Description = field.NewString(table, "description")
	t.Status = field.NewString(table, "status")
	t.Priority = field.NewString(table, "priority")
	t.DueAt = field.NewTime(table, "due_at")
	t.CompletedAt = field.NewTime(table, "completed_at")
	t.Tags = field.NewField(table, "tags")
	t.CreatedAt = field.NewTime(table, "created_at")
	t.UpdatedAt = field.NewTime(table, "updated_at")

	t.fillFieldMap()

	return t
}

func (t *todoItem) WithContext(ctx context.Context) ITodoItemDo { return t.todoItemDo.WithContext(ctx) }

func (t todoItem) TableName() string { return t.todoItemDo.TableName() }

func (t todoItem) Alias() string { return t.todoItemDo.Alias() }

func (t todoItem) Columns(cols ...field.Expr) gen.Columns { return t.todoItemDo.Columns(cols...) }

func (t *todoItem) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := t.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (t *todoItem) fillFieldMap() {
	t.fieldMap = make(map[string]field.Expr, 16)
	t.fieldMap["id"] = t.ID
	t.fieldMap["chat_id"] = t.ChatID
	t.fieldMap["app_id"] = t.AppID
	t.fieldMap["bot_open_id"] = t.BotOpenID
	t.fieldMap["creator_id"] = t.CreatorID
	t.fieldMap["creator_name"] = t.CreatorName
	t.fieldMap["assignee_id"] = t.AssigneeID
	t.fieldMap["title"] = t.Title
	t.fieldMap["description"] = t.Description
	t.fieldMap["status"] = t.Status
	t.fieldMap["priority"] = t.Priority
	t.fieldMap["due_at"] = t.DueAt
	t.fieldMap["completed_at"] = t.CompletedAt
	t.fieldMap["tags"] = t.Tags
	t.fieldMap["created_at"] = t.CreatedAt
	t.fieldMap["updated_at"] = t.UpdatedAt
}

func (t todoItem) clone(db *gorm.DB) todoItem {
	t.todoItemDo.ReplaceConnPool(db.Statement.ConnPool)
	return t
}

func (t todoItem) replaceDB(db *gorm.DB) todoItem {
	t.todoItemDo.ReplaceDB(db)
	return t
}

type todoItemDo struct {
	gen.GenericsDo[ITodoItemDo, *model.TodoItem]
}
type ITodoItemDo interface {
	gen.IGenericsDo[ITodoItemDo, *model.TodoItem]
}

func (t *todoItemDo) withDO(do gen.Dao) ITodoItemDo {
	_r := &todoItemDo{}
	_r.DO = *do.(*gen.DO)
	_r.IWithDO = gen.WithDOFunc[ITodoItemDo](t.withDO)
	return _r
}
