// Code generated by warmup; DO NOT EDIT.

package utils

import (
	"github.com/BetaGoRobot/go_utils/reflecting"
)

func init() {
	reflecting.GetFunctionName(AddTrace2DB)         // from /mnt/RapidPool/workspace/BetaGo_v2/pkg/utils/trace_msg.go:15
	reflecting.GetFunctionName(ResizeIMGFromReader) // from /mnt/RapidPool/workspace/BetaGo_v2/pkg/utils/img.go:14
}
