// Code generated by warmup; DO NOT EDIT.

package larkmsg

import (
	"github.com/BetaGoRobot/go_utils/reflecting"
)

func init() {
	reflecting.GetFunctionName(AddReaction)                   // from /mnt/RapidPool/workspace/BetaGo_v2/internal/infrastructure/lark_dal/larkmsg/reaction.go:19
	reflecting.GetFunctionName(AddReactionAsync)              // from /mnt/RapidPool/workspace/BetaGo_v2/internal/infrastructure/lark_dal/larkmsg/reaction.go:38
	reflecting.GetFunctionName(CreateMsgCard)                 // from /mnt/RapidPool/workspace/BetaGo_v2/internal/infrastructure/lark_dal/larkmsg/card.go:54
	reflecting.GetFunctionName(CreateMsgTextRaw)              // from /mnt/RapidPool/workspace/BetaGo_v2/internal/infrastructure/lark_dal/larkmsg/send.go:38
	reflecting.GetFunctionName(GetChatIDFromMsgID)            // from /mnt/RapidPool/workspace/BetaGo_v2/internal/infrastructure/lark_dal/larkmsg/parse.go:95
	reflecting.GetFunctionName(PatchCard)                     // from /mnt/RapidPool/workspace/BetaGo_v2/internal/infrastructure/lark_dal/larkmsg/patch.go:25
	reflecting.GetFunctionName(PreGetTextMsg)                 // from /mnt/RapidPool/workspace/BetaGo_v2/internal/infrastructure/lark_dal/larkmsg/parse.go:49
	reflecting.GetFunctionName(RecordCardAction2Opensearch)   // from /mnt/RapidPool/workspace/BetaGo_v2/internal/infrastructure/lark_dal/larkmsg/record.go:193
	reflecting.GetFunctionName(RecordMessage2Opensearch)      // from /mnt/RapidPool/workspace/BetaGo_v2/internal/infrastructure/lark_dal/larkmsg/record.go:102
	reflecting.GetFunctionName(RecordReplyMessage2Opensearch) // from /mnt/RapidPool/workspace/BetaGo_v2/internal/infrastructure/lark_dal/larkmsg/record.go:32
	reflecting.GetFunctionName(RemoveReactionAsync)           // from /mnt/RapidPool/workspace/BetaGo_v2/internal/infrastructure/lark_dal/larkmsg/reaction.go:60
	reflecting.GetFunctionName(ReplyCard)                     // from /mnt/RapidPool/workspace/BetaGo_v2/internal/infrastructure/lark_dal/larkmsg/reply.go:78
	reflecting.GetFunctionName(ReplyCardText)                 // from /mnt/RapidPool/workspace/BetaGo_v2/internal/infrastructure/lark_dal/larkmsg/card.go:18
	reflecting.GetFunctionName(ReplyMsgRawAsText)             // from /mnt/RapidPool/workspace/BetaGo_v2/internal/infrastructure/lark_dal/larkmsg/reply.go:52
	reflecting.GetFunctionName(ReplyMsgRawContentType)        // from /mnt/RapidPool/workspace/BetaGo_v2/internal/infrastructure/lark_dal/larkmsg/reply.go:18
	reflecting.GetFunctionName(ReplyMsgText)                  // from /mnt/RapidPool/workspace/BetaGo_v2/internal/infrastructure/lark_dal/larkmsg/reply.go:44
	reflecting.GetFunctionName(SendAndReplyStreamingCard)     // from /mnt/RapidPool/workspace/BetaGo_v2/internal/infrastructure/lark_dal/larkmsg/send.go:79
	reflecting.GetFunctionName(SendAndUpdateStreamingCard)    // from /mnt/RapidPool/workspace/BetaGo_v2/internal/infrastructure/lark_dal/larkmsg/send.go:277
	reflecting.GetFunctionName(TrimAtMsg)                     // from /mnt/RapidPool/workspace/BetaGo_v2/internal/infrastructure/lark_dal/larkmsg/content.go:31
	reflecting.GetFunctionName(updateCardFunc)                // from /mnt/RapidPool/workspace/BetaGo_v2/internal/infrastructure/lark_dal/larkmsg/send.go:149, /mnt/RapidPool/workspace/BetaGo_v2/internal/infrastructure/lark_dal/larkmsg/send.go:159, /mnt/RapidPool/workspace/BetaGo_v2/internal/infrastructure/lark_dal/larkmsg/send.go:185
}
