// Code generated by warmup; DO NOT EDIT.

package retriever

import (
	"github.com/BetaGoRobot/go_utils/reflecting"
)

func init() {
	reflecting.GetFunctionName((*RAGSystem).AddDocuments) // from /mnt/RapidPool/workspace/BetaGo_v2/internal/infrastructure/retriever/retriver.go:179
	reflecting.GetFunctionName(NewRAGSystem)              // from /mnt/RapidPool/workspace/BetaGo_v2/internal/infrastructure/retriever/retriver.go:124
}
