// Code generated by warmup; DO NOT EDIT.

package larkchunking

import (
	"github.com/BetaGoRobot/go_utils/reflecting"
)

func init() {
	reflecting.GetFunctionName(Init) // from /mnt/RapidPool/workspace/BetaGo_v2/internal/application/lark/chunking/chunking.go:29
}
