// Code generated by warmup; DO NOT EDIT.

package larktpl

import (
	xmodel "github.com/BetaGoRobot/BetaGo-Redefine/internal/xmodel"
	"github.com/BetaGoRobot/go_utils/reflecting"
)

func init() {
	reflecting.GetFunctionName(NewCardContent)                                                // from /mnt/RapidPool/workspace/BetaGo_v2/internal/infrastructure/lark_dal/larkmsg/larktpl/template.go:94
	reflecting.GetFunctionName(NewCardContentV2[ChunkMetaData])                               // from /mnt/RapidPool/workspace/BetaGo_v2/internal/application/lark/handlers/debug_handler.go:636
	reflecting.GetFunctionName(NewCardContentV2[WordCountCardVars[xmodel.MessageChunkLogV3]]) // from /mnt/RapidPool/workspace/BetaGo_v2/internal/application/lark/handlers/word_count_handler.go:228
}
