// Code generated by warmup; DO NOT EDIT.

package recording

import (
	"github.com/BetaGoRobot/go_utils/reflecting"
)

func init() {
	reflecting.GetFunctionName(CollectMessage) // from /mnt/RapidPool/workspace/BetaGo_v2/internal/application/lark/messages/recording/service.go:29
}
