// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameAdministrator = "administrators"

// Administrator mapped from table <administrators>
type Administrator struct {
	ID        int64          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	CreatedAt time.Time      `gorm:"column:created_at" json:"created_at"`
	UpdatedAt time.Time      `gorm:"column:updated_at" json:"updated_at"`
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
	UserID    int64          `gorm:"column:user_id;primaryKey" json:"user_id"`
	UserName  string         `gorm:"column:user_name" json:"user_name"`
	Level     int64          `gorm:"column:level" json:"level"`
}

// TableName Administrator's table name
func (*Administrator) TableName() string {
	return TableNameAdministrator
}
