// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameAgentCapabilityExecution = "agent_capability_executions"

// AgentCapabilityExecution mapped from table <agent_capability_executions>
type AgentCapabilityExecution struct {
	IdempotencyKey string    `gorm:"column:idempotency_key;primaryKey" json:"idempotency_key"`
	RunID          string    `gorm:"column:run_id;not null" json:"run_id"`
	StepID         string    `gorm:"column:step_id;not null" json:"step_id"`
	CapabilityName string    `gorm:"column:capability_name;not null" json:"capability_name"`
	Status         string    `gorm:"column:status;not null" json:"status"`
	InputJSON      string    `gorm:"column:input_json;not null;default:{}" json:"input_json"`
	OutputJSON     string    `gorm:"column:output_json;not null;default:{}" json:"output_json"`
	ErrorText      string    `gorm:"column:error_text;not null" json:"error_text"`
	StartedAt      time.Time `gorm:"column:started_at" json:"started_at"`
	FinishedAt     time.Time `gorm:"column:finished_at" json:"finished_at"`
	CreatedAt      time.Time `gorm:"column:created_at;not null;default:now()" json:"created_at"`
	UpdatedAt      time.Time `gorm:"column:updated_at;not null;default:now()" json:"updated_at"`
	TenantID       string    `gorm:"column:tenant_id;not null" json:"tenant_id"`
}

// TableName AgentCapabilityExecution's table name
func (*AgentCapabilityExecution) TableName() string {
	return TableNameAgentCapabilityExecution
}
