// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameAgentSession = "agent_sessions"

// AgentSession mapped from table <agent_sessions>
type AgentSession struct {
	ID              string    `gorm:"column:id;primaryKey" json:"id"`
	AppID           string    `gorm:"column:app_id;not null" json:"app_id"`
	BotOpenID       string    `gorm:"column:bot_open_id;not null" json:"bot_open_id"`
	ChatID          string    `gorm:"column:chat_id;not null" json:"chat_id"`
	ScopeType       string    `gorm:"column:scope_type;not null" json:"scope_type"`
	ScopeID         string    `gorm:"column:scope_id;not null" json:"scope_id"`
	Status          string    `gorm:"column:status;not null" json:"status"`
	ActiveRunID     string    `gorm:"column:active_run_id;not null" json:"active_run_id"`
	LastMessageID   string    `gorm:"column:last_message_id;not null" json:"last_message_id"`
	LastActorOpenID string    `gorm:"column:last_actor_open_id;not null" json:"last_actor_open_id"`
	MemoryVersion   int64     `gorm:"column:memory_version;not null" json:"memory_version"`
	CreatedAt       time.Time `gorm:"column:created_at;not null;default:now()" json:"created_at"`
	UpdatedAt       time.Time `gorm:"column:updated_at;not null;default:now()" json:"updated_at"`
}

// TableName AgentSession's table name
func (*AgentSession) TableName() string {
	return TableNameAgentSession
}
