// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameAgentRun = "agent_runs"

// AgentRun mapped from table <agent_runs>
type AgentRun struct {
	ID               string    `gorm:"column:id;primaryKey" json:"id"`
	SessionID        string    `gorm:"column:session_id;not null" json:"session_id"`
	TriggerType      string    `gorm:"column:trigger_type;not null" json:"trigger_type"`
	TriggerMessageID string    `gorm:"column:trigger_message_id;not null" json:"trigger_message_id"`
	TriggerEventID   string    `gorm:"column:trigger_event_id;not null" json:"trigger_event_id"`
	ActorOpenID      string    `gorm:"column:actor_open_id;not null" json:"actor_open_id"`
	ParentRunID      string    `gorm:"column:parent_run_id;not null" json:"parent_run_id"`
	Status           string    `gorm:"column:status;not null" json:"status"`
	Goal             string    `gorm:"column:goal;not null" json:"goal"`
	InputText        string    `gorm:"column:input_text;not null" json:"input_text"`
	CurrentStepIndex int32     `gorm:"column:current_step_index;not null" json:"current_step_index"`
	WaitingReason    string    `gorm:"column:waiting_reason;not null" json:"waiting_reason"`
	WaitingToken     string    `gorm:"column:waiting_token;not null" json:"waiting_token"`
	LastResponseID   string    `gorm:"column:last_response_id;not null" json:"last_response_id"`
	ResultSummary    string    `gorm:"column:result_summary;not null" json:"result_summary"`
	ErrorText        string    `gorm:"column:error_text;not null" json:"error_text"`
	Revision         int64     `gorm:"column:revision;not null" json:"revision"`
	StartedAt        time.Time `gorm:"column:started_at" json:"started_at"`
	FinishedAt       time.Time `gorm:"column:finished_at" json:"finished_at"`
	CreatedAt        time.Time `gorm:"column:created_at;not null;default:now()" json:"created_at"`
	UpdatedAt        time.Time `gorm:"column:updated_at;not null;default:now()" json:"updated_at"`
	WorkerID         string    `gorm:"column:worker_id;not null" json:"worker_id"`
	HeartbeatAt      time.Time `gorm:"column:heartbeat_at" json:"heartbeat_at"`
	LeaseExpiresAt   time.Time `gorm:"column:lease_expires_at" json:"lease_expires_at"`
	RepairAttempts   int64     `gorm:"column:repair_attempts;not null" json:"repair_attempts"`
}

// TableName AgentRun's table name
func (*AgentRun) TableName() string {
	return TableNameAgentRun
}
