// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameAgentStep = "agent_steps"

// AgentStep mapped from table <agent_steps>
type AgentStep struct {
	ID             string    `gorm:"column:id;primaryKey" json:"id"`
	RunID          string    `gorm:"column:run_id;not null" json:"run_id"`
	Index          int32     `gorm:"column:index;not null" json:"index"`
	Kind           string    `gorm:"column:kind;not null" json:"kind"`
	Status         string    `gorm:"column:status;not null" json:"status"`
	CapabilityName string    `gorm:"column:capability_name;not null" json:"capability_name"`
	InputJSON      string    `gorm:"column:input_json;not null;default:{}" json:"input_json"`
	OutputJSON     string    `gorm:"column:output_json;not null;default:{}" json:"output_json"`
	ErrorText      string    `gorm:"column:error_text;not null" json:"error_text"`
	ExternalRef    string    `gorm:"column:external_ref;not null" json:"external_ref"`
	StartedAt      time.Time `gorm:"column:started_at" json:"started_at"`
	FinishedAt     time.Time `gorm:"column:finished_at" json:"finished_at"`
	CreatedAt      time.Time `gorm:"column:created_at;not null;default:now()" json:"created_at"`
}

// TableName AgentStep's table name
func (*AgentStep) TableName() string {
	return TableNameAgentStep
}
