// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameAgentCardSurface = "agent_card_surfaces"

// AgentCardSurface mapped from table <agent_card_surfaces>
type AgentCardSurface struct {
	ID                   string    `gorm:"column:id;primaryKey" json:"id"`
	RunID                string    `gorm:"column:run_id;not null" json:"run_id"`
	WaitStepID           string    `gorm:"column:wait_step_id;not null" json:"wait_step_id"`
	InteractionID        string    `gorm:"column:interaction_id;not null" json:"interaction_id"`
	ChatID               string    `gorm:"column:chat_id;not null" json:"chat_id"`
	ReplyToMessageID     string    `gorm:"column:reply_to_message_id;not null" json:"reply_to_message_id"`
	MessageID            string    `gorm:"column:message_id;not null" json:"message_id"`
	SpecVersion          string    `gorm:"column:spec_version;not null" json:"spec_version"`
	SpecJSON             string    `gorm:"column:spec_json;not null" json:"spec_json"`
	CompiledJSONRedacted string    `gorm:"column:compiled_json_redacted;not null" json:"compiled_json_redacted"`
	Status               string    `gorm:"column:status;not null" json:"status"`
	Revision             int64     `gorm:"column:revision;not null" json:"revision"`
	ExpectedActorOpenID  string    `gorm:"column:expected_actor_open_id;not null" json:"expected_actor_open_id"`
	InteractionKind      string    `gorm:"column:interaction_kind;not null" json:"interaction_kind"`
	ExpiresAt            time.Time `gorm:"column:expires_at;not null" json:"expires_at"`
	SubmittedAt          time.Time `gorm:"column:submitted_at" json:"submitted_at"`
	ProcessingAt         time.Time `gorm:"column:processing_at" json:"processing_at"`
	ResolvedAt           time.Time `gorm:"column:resolved_at" json:"resolved_at"`
	CancelledAt          time.Time `gorm:"column:cancelled_at" json:"cancelled_at"`
	FailedAt             time.Time `gorm:"column:failed_at" json:"failed_at"`
	LastActionID         string    `gorm:"column:last_action_id;not null" json:"last_action_id"`
	LastSourceRef        string    `gorm:"column:last_source_ref;not null" json:"last_source_ref"`
	PatchStatus          string    `gorm:"column:patch_status;not null;default:idle" json:"patch_status"`
	PatchAttemptCount    int32     `gorm:"column:patch_attempt_count;not null" json:"patch_attempt_count"`
	NextPatchAt          time.Time `gorm:"column:next_patch_at;not null;default:now()" json:"next_patch_at"`
	PatchWorkerID        string    `gorm:"column:patch_worker_id;not null" json:"patch_worker_id"`
	PatchLeaseExpiresAt  time.Time `gorm:"column:patch_lease_expires_at" json:"patch_lease_expires_at"`
	LastError            string    `gorm:"column:last_error;not null" json:"last_error"`
	CreatedAt            time.Time `gorm:"column:created_at;not null;default:now()" json:"created_at"`
	UpdatedAt            time.Time `gorm:"column:updated_at;not null;default:now()" json:"updated_at"`
}

// TableName AgentCardSurface's table name
func (*AgentCardSurface) TableName() string {
	return TableNameAgentCardSurface
}
