// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameAgentProjectionOutbox = "agent_projection_outbox"

// AgentProjectionOutbox mapped from table <agent_projection_outbox>
type AgentProjectionOutbox struct {
	ID             string    `gorm:"column:id;primaryKey" json:"id"`
	StepID         string    `gorm:"column:step_id;not null" json:"step_id"`
	IndexAlias     string    `gorm:"column:index_alias;not null" json:"index_alias"`
	DocumentID     string    `gorm:"column:document_id;not null" json:"document_id"`
	PayloadJSON    string    `gorm:"column:payload_json;not null" json:"payload_json"`
	Status         string    `gorm:"column:status;not null;default:pending" json:"status"`
	AttemptCount   int32     `gorm:"column:attempt_count;not null" json:"attempt_count"`
	NextAttemptAt  time.Time `gorm:"column:next_attempt_at;not null;default:now()" json:"next_attempt_at"`
	WorkerID       string    `gorm:"column:worker_id;not null" json:"worker_id"`
	LeaseExpiresAt time.Time `gorm:"column:lease_expires_at" json:"lease_expires_at"`
	LastError      string    `gorm:"column:last_error;not null" json:"last_error"`
	CreatedAt      time.Time `gorm:"column:created_at;not null;default:now()" json:"created_at"`
	UpdatedAt      time.Time `gorm:"column:updated_at;not null;default:now()" json:"updated_at"`
}

// TableName AgentProjectionOutbox's table name
func (*AgentProjectionOutbox) TableName() string {
	return TableNameAgentProjectionOutbox
}
