// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameAlertList = "alert_lists"

// AlertList mapped from table <alert_lists>
type AlertList struct {
	EmailAddress string `gorm:"column:email_address" json:"email_address"`
}

// TableName AlertList's table name
func (*AlertList) TableName() string {
	return TableNameAlertList
}
