// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameCardActionRecordLog = "card_action_record_logs"

// CardActionRecordLog mapped from table <card_action_record_logs>
type CardActionRecordLog struct {
	UserID   string `gorm:"column:user_id;primaryKey" json:"user_id"`
	UserName string `gorm:"column:user_name" json:"user_name"`
	EventSrc string `gorm:"column:event_src" json:"event_src"`
}

// TableName CardActionRecordLog's table name
func (*CardActionRecordLog) TableName() string {
	return TableNameCardActionRecordLog
}
