// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameChannelLogExt = "channel_log_exts"

// ChannelLogExt mapped from table <channel_log_exts>
type ChannelLogExt struct {
	UserID      string `gorm:"column:user_id;primaryKey" json:"user_id"`
	UserName    string `gorm:"column:user_name" json:"user_name"`
	ChannelID   string `gorm:"column:channel_id;primaryKey" json:"channel_id"`
	ChannelName string `gorm:"column:channel_name" json:"channel_name"`
	JoinedTime  string `gorm:"column:joined_time;primaryKey" json:"joined_time"`
	LeftTime    string `gorm:"column:left_time" json:"left_time"`
	IsUpdate    bool   `gorm:"column:is_update" json:"is_update"`
	MsgID       string `gorm:"column:msg_id" json:"msg_id"`
	GuildID     string `gorm:"column:guild_id" json:"guild_id"`
}

// TableName ChannelLogExt's table name
func (*ChannelLogExt) TableName() string {
	return TableNameChannelLogExt
}
