// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameChannelLog = "channel_logs"

// ChannelLog mapped from table <channel_logs>
type ChannelLog struct {
	UserID      string    `gorm:"column:user_id" json:"user_id"`
	UserName    string    `gorm:"column:user_name" json:"user_name"`
	ChannelID   string    `gorm:"column:channel_id" json:"channel_id"`
	ChannelName string    `gorm:"column:channel_name" json:"channel_name"`
	JoinedTime  time.Time `gorm:"column:joined_time" json:"joined_time"`
	LeftTime    time.Time `gorm:"column:left_time" json:"left_time"`
	IsUpdate    bool      `gorm:"column:is_update" json:"is_update"`
	MsgID       string    `gorm:"column:msg_id" json:"msg_id"`
}

// TableName ChannelLog's table name
func (*ChannelLog) TableName() string {
	return TableNameChannelLog
}
