// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameChatRecordLog = "chat_record_logs"

// ChatRecordLog mapped from table <chat_record_logs>
type ChatRecordLog struct {
	AuthorID  string `gorm:"column:author_id;primaryKey" json:"author_id"`
	RecordStr string `gorm:"column:record_str" json:"record_str"`
}

// TableName ChatRecordLog's table name
func (*ChatRecordLog) TableName() string {
	return TableNameChatRecordLog
}
