// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameChatContextRecord = "chat_context_records"

// ChatContextRecord mapped from table <chat_context_records>
type ChatContextRecord struct {
	UserID    string `gorm:"column:user_id" json:"user_id"`
	SessionID string `gorm:"column:session_id" json:"session_id"`
}

// TableName ChatContextRecord's table name
func (*ChatContextRecord) TableName() string {
	return TableNameChatContextRecord
}
