// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameCommandInfo = "command_infos"

// CommandInfo mapped from table <command_infos>
type CommandInfo struct {
	CommandName     string    `gorm:"column:command_name;primaryKey" json:"command_name"`
	CommandDesc     string    `gorm:"column:command_desc" json:"command_desc"`
	CommandParamLen int64     `gorm:"column:command_param_len" json:"command_param_len"`
	CommandType     string    `gorm:"column:command_type" json:"command_type"`
	CreatedAt       time.Time `gorm:"column:created_at" json:"created_at"`
	UpdatedAt       time.Time `gorm:"column:updated_at" json:"updated_at"`
}

// TableName CommandInfo's table name
func (*CommandInfo) TableName() string {
	return TableNameCommandInfo
}
