// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameCopyWritingGeneral = "copy_writing_generals"

// CopyWritingGeneral mapped from table <copy_writing_generals>
type CopyWritingGeneral struct {
	Endpoint string `gorm:"column:endpoint;primaryKey" json:"endpoint"`
	Content  string `gorm:"column:content" json:"content"`
}

// TableName CopyWritingGeneral's table name
func (*CopyWritingGeneral) TableName() string {
	return TableNameCopyWritingGeneral
}
