// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameCronCmdTask = "cron_cmd_tasks"

// CronCmdTask mapped from table <cron_cmd_tasks>
type CronCmdTask struct {
	TaskName string `gorm:"column:task_name;primaryKey" json:"task_name"`
	TaskCron string `gorm:"column:task_cron" json:"task_cron"`
	TaskCmd  string `gorm:"column:task_cmd" json:"task_cmd"`
}

// TableName CronCmdTask's table name
func (*CronCmdTask) TableName() string {
	return TableNameCronCmdTask
}
