// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameDynamicConfig = "dynamic_configs"

// DynamicConfig mapped from table <dynamic_configs>
type DynamicConfig struct {
	Key   string `gorm:"column:key;primaryKey" json:"key"`
	Value string `gorm:"column:value;primaryKey" json:"value"`
}

// TableName DynamicConfig's table name
func (*DynamicConfig) TableName() string {
	return TableNameDynamicConfig
}
