// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameFunctionEnabling = "function_enablings"

// FunctionEnabling mapped from table <function_enablings>
type FunctionEnabling struct {
	GuildID  string `gorm:"column:guild_id;primaryKey" json:"guild_id"`
	Function string `gorm:"column:function;primaryKey" json:"function"`
}

// TableName FunctionEnabling's table name
func (*FunctionEnabling) TableName() string {
	return TableNameFunctionEnabling
}
