// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameImitateRateCustom = "imitate_rate_customs"

// ImitateRateCustom mapped from table <imitate_rate_customs>
type ImitateRateCustom struct {
	CreatedAt time.Time      `gorm:"column:created_at" json:"created_at"`
	UpdatedAt time.Time      `gorm:"column:updated_at" json:"updated_at"`
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
	GuildID   string         `gorm:"column:guild_id;primaryKey" json:"guild_id"`
	Rate      int64          `gorm:"column:rate" json:"rate"`
}

// TableName ImitateRateCustom's table name
func (*ImitateRateCustom) TableName() string {
	return TableNameImitateRateCustom
}
