// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameInsightLlmTokenUsage = "insight_llm_token_usage"

// InsightLlmTokenUsage mapped from table <insight_llm_token_usage>
type InsightLlmTokenUsage struct {
	ID                   int64     `gorm:"column:id;primaryKey" json:"id"`
	AccountID            string    `gorm:"column:account_id;not null" json:"account_id"`
	ProductName          string    `gorm:"column:product_name;not null" json:"product_name"`
	ModelNameArk         string    `gorm:"column:model_name_ark;not null" json:"model_name_ark"`
	ModelVersionArk      string    `gorm:"column:model_version_ark;not null" json:"model_version_ark"`
	ModelBillingIdentity string    `gorm:"column:model_billing_identity;not null" json:"model_billing_identity"`
	EndpointID           string    `gorm:"column:endpoint_id;not null" json:"endpoint_id"`
	LogID                string    `gorm:"column:log_id;not null" json:"log_id"`
	PromptTokens         int64     `gorm:"column:prompt_tokens;not null" json:"prompt_tokens"`
	CompletionTokens     int64     `gorm:"column:completion_tokens;not null" json:"completion_tokens"`
	RequestTime          time.Time `gorm:"column:request_time;default:CURRENT_TIMESTAMP" json:"request_time"`
}

// TableName InsightLlmTokenUsage's table name
func (*InsightLlmTokenUsage) TableName() string {
	return TableNameInsightLlmTokenUsage
}
