// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameInteractionStat = "interaction_stats"

// InteractionStat mapped from table <interaction_stats>
type InteractionStat struct {
	OpenID     string    `gorm:"column:open_id" json:"open_id"`
	GuildID    string    `gorm:"column:guild_id" json:"guild_id"`
	NickName   string    `gorm:"column:nick_name" json:"nick_name"`
	UserName   string    `gorm:"column:user_name" json:"user_name"`
	ActionType string    `gorm:"column:action_type" json:"action_type"`
	CreatedAt  time.Time `gorm:"column:created_at" json:"created_at"`
	MsgID      string    `gorm:"column:msg_id" json:"msg_id"`
}

// TableName InteractionStat's table name
func (*InteractionStat) TableName() string {
	return TableNameInteractionStat
}
