// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameLarkImg = "lark_imgs"

// LarkImg mapped from table <lark_imgs>
type LarkImg struct {
	ID        int64          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	CreatedAt time.Time      `gorm:"column:created_at" json:"created_at"`
	UpdatedAt time.Time      `gorm:"column:updated_at" json:"updated_at"`
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
	SongID    string         `gorm:"column:song_id;primaryKey" json:"song_id"`
	ImgKey    string         `gorm:"column:img_key;primaryKey" json:"img_key"`
}

// TableName LarkImg's table name
func (*LarkImg) TableName() string {
	return TableNameLarkImg
}
