// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import "time"

const TableNameLlmToolCallRecord = "llm_tool_call_records"

// LlmToolCallRecord mapped from table <llm_tool_call_records>
type LlmToolCallRecord struct {
	ID                int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	UsageRecordID     int64     `gorm:"column:usage_record_id;not null" json:"usage_record_id"`
	BotID             string    `gorm:"column:bot_id;not null" json:"bot_id"`
	ChatID            string    `gorm:"column:chat_id;not null" json:"chat_id"`
	BusinessScene     string    `gorm:"column:business_scene;not null" json:"business_scene"`
	BusinessOperation string    `gorm:"column:business_operation;not null" json:"business_operation"`
	ToolName          string    `gorm:"column:tool_name;not null" json:"tool_name"`
	Status            string    `gorm:"column:status;not null" json:"status"`
	DurationMs        int64     `gorm:"column:duration_ms;not null" json:"duration_ms"`
	ErrorKind         string    `gorm:"column:error_kind;not null" json:"error_kind"`
	TraceID           string    `gorm:"column:trace_id;not null" json:"trace_id"`
	CalledAt          time.Time `gorm:"column:called_at;not null" json:"called_at"`
	CreatedAt         time.Time `gorm:"column:created_at;not null;default:now()" json:"created_at"`
}

func (*LlmToolCallRecord) TableName() string { return TableNameLlmToolCallRecord }
