// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameLuckinOrder = "luckin_orders"

// LuckinOrder mapped from table <luckin_orders>
type LuckinOrder struct {
	ID                  int64      `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	OrderID             string     `gorm:"column:order_id;not null" json:"order_id"`
	AppID               string     `gorm:"column:app_id;not null" json:"app_id"`
	BotOpenID           string     `gorm:"column:bot_open_id;not null" json:"bot_open_id"`
	ChatID              string     `gorm:"column:chat_id;not null" json:"chat_id"`
	RequesterOpenID     string     `gorm:"column:requester_open_id;not null" json:"requester_open_id"`
	CredentialScopeType string     `gorm:"column:credential_scope_type;not null" json:"credential_scope_type"`
	CredentialScopeID   string     `gorm:"column:credential_scope_id;not null" json:"credential_scope_id"`
	MessageID           string     `gorm:"column:message_id;not null" json:"message_id"`
	Status              string     `gorm:"column:status;not null;default:active" json:"status"`
	LastRemoteStatus    int64      `gorm:"column:last_remote_status;not null" json:"last_remote_status"`
	NeedPay             bool       `gorm:"column:need_pay;not null" json:"need_pay"`
	PayURL              string     `gorm:"column:pay_url;not null" json:"pay_url"`
	QrURL               string     `gorm:"column:qr_url;not null" json:"qr_url"`
	DiscountPrice       float64    `gorm:"column:discount_price;not null" json:"discount_price"`
	UnpaidReminded      bool       `gorm:"column:unpaid_reminded;not null" json:"unpaid_reminded"`
	NextPollAt          time.Time  `gorm:"column:next_poll_at;not null;default:now()" json:"next_poll_at"`
	PollDeadline        time.Time  `gorm:"column:poll_deadline;not null" json:"poll_deadline"`
	FailCount           int64      `gorm:"column:fail_count;not null" json:"fail_count"`
	StoppedReason       string     `gorm:"column:stopped_reason;not null" json:"stopped_reason"`
	PlacedAt            *time.Time `gorm:"column:placed_at" json:"placed_at"`
	MakingAt            *time.Time `gorm:"column:making_at" json:"making_at"`
	ReadyAt             *time.Time `gorm:"column:ready_at" json:"ready_at"`
	CompletedAt         *time.Time `gorm:"column:completed_at" json:"completed_at"`
	CancelledAt         *time.Time `gorm:"column:cancelled_at" json:"cancelled_at"`
	CreatedAt           time.Time  `gorm:"column:created_at;not null;default:now()" json:"created_at"`
	UpdatedAt           time.Time  `gorm:"column:updated_at;not null;default:now()" json:"updated_at"`
}

// TableName LuckinOrder's table name
func (*LuckinOrder) TableName() string {
	return TableNameLuckinOrder
}
