// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameMcpCredential = "mcp_credentials"

// McpCredential mapped from table <mcp_credentials>
type McpCredential struct {
	ID              int64          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Provider        string         `gorm:"column:provider;not null" json:"provider"`
	AppID           string         `gorm:"column:app_id;not null" json:"app_id"`
	BotOpenID       string         `gorm:"column:bot_open_id;not null" json:"bot_open_id"`
	ScopeType       string         `gorm:"column:scope_type;not null" json:"scope_type"`
	ScopeID         string         `gorm:"column:scope_id;not null" json:"scope_id"`
	EncryptedToken  string         `gorm:"column:encrypted_token;not null" json:"encrypted_token"`
	TokenHint       string         `gorm:"column:token_hint;not null" json:"token_hint"`
	CreatedByOpenID string         `gorm:"column:created_by_open_id;not null" json:"created_by_open_id"`
	UpdatedByOpenID string         `gorm:"column:updated_by_open_id;not null" json:"updated_by_open_id"`
	CreatedAt       time.Time      `gorm:"column:created_at;not null;default:now()" json:"created_at"`
	UpdatedAt       time.Time      `gorm:"column:updated_at;not null;default:now()" json:"updated_at"`
	DeletedAt       gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
}

// TableName McpCredential's table name
func (*McpCredential) TableName() string {
	return TableNameMcpCredential
}
