// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameMessageLog = "message_logs"

// MessageLog mapped from table <message_logs>
type MessageLog struct {
	MessageID   string    `gorm:"column:message_id;not null" json:"message_id"`
	RootID      string    `gorm:"column:root_id" json:"root_id"`
	ParentID    string    `gorm:"column:parent_id" json:"parent_id"`
	ChatID      string    `gorm:"column:chat_id" json:"chat_id"`
	ThreadID    string    `gorm:"column:thread_id" json:"thread_id"`
	ChatType    string    `gorm:"column:chat_type" json:"chat_type"`
	MessageType string    `gorm:"column:message_type" json:"message_type"`
	UserAgent   string    `gorm:"column:user_agent" json:"user_agent"`
	Mentions    string    `gorm:"column:mentions" json:"mentions"`
	RawBody     string    `gorm:"column:raw_body" json:"raw_body"`
	Content     string    `gorm:"column:content" json:"content"`
	FileKey     string    `gorm:"column:file_key" json:"file_key"`
	CreatedAt   time.Time `gorm:"column:created_at" json:"created_at"`
	TraceID     string    `gorm:"column:trace_id" json:"trace_id"`
}

// TableName MessageLog's table name
func (*MessageLog) TableName() string {
	return TableNameMessageLog
}
