// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameMsgTraceLog = "msg_trace_logs"

// MsgTraceLog mapped from table <msg_trace_logs>
type MsgTraceLog struct {
	MsgID     string    `gorm:"column:msg_id" json:"msg_id"`
	TraceID   string    `gorm:"column:trace_id" json:"trace_id"`
	CreatedAt time.Time `gorm:"column:created_at" json:"created_at"`
}

// TableName MsgTraceLog's table name
func (*MsgTraceLog) TableName() string {
	return TableNameMsgTraceLog
}
