// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNamePermissionGrant = "permission_grants"

// PermissionGrant mapped from table <permission_grants>
type PermissionGrant struct {
	ID              int64          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	SubjectType     string         `gorm:"column:subject_type;not null;comment:授权主体类型，当前固定为 user" json:"subject_type"`            // 授权主体类型，当前固定为 user
	SubjectID       string         `gorm:"column:subject_id;not null;comment:授权主体标识，飞书侧优先使用 OpenID" json:"subject_id"`            // 授权主体标识，飞书侧优先使用 OpenID
	PermissionPoint string         `gorm:"column:permission_point;not null;comment:权限点，例如 config.write" json:"permission_point"`  // 权限点，例如 config.write
	Scope           string         `gorm:"column:scope;not null;comment:授权作用域，例如 global/chat/user" json:"scope"`                  // 授权作用域，例如 global/chat/user
	ResourceChatID  *string        `gorm:"column:resource_chat_id;comment:作用域资源 chat_id，global scope 为空" json:"resource_chat_id"` // 作用域资源 chat_id，global scope 为空
	ResourceUserID  *string        `gorm:"column:resource_user_id;comment:作用域资源 user_id，global scope 为空" json:"resource_user_id"` // 作用域资源 user_id，global scope 为空
	Remark          string         `gorm:"column:remark;comment:授权备注" json:"remark"`                                              // 授权备注
	CreatedAt       time.Time      `gorm:"column:created_at;not null;default:now()" json:"created_at"`
	UpdatedAt       time.Time      `gorm:"column:updated_at;not null;default:now()" json:"updated_at"`
	DeletedAt       gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
	AppID           string         `gorm:"column:app_id;not null;default:cli_a570c2871fe3500e;comment:授权所属的飞书应用 AppID" json:"app_id"`                          // 授权所属的飞书应用 AppID
	BotOpenID       string         `gorm:"column:bot_open_id;not null;default:ou_8817f540f718affd21718f415b81597f;comment:授权所属的机器人 OpenID" json:"bot_open_id"` // 授权所属的机器人 OpenID
}

// TableName PermissionGrant's table name
func (*PermissionGrant) TableName() string {
	return TableNamePermissionGrant
}
