// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNamePrivateMode = "private_modes"

// PrivateMode mapped from table <private_modes>
type PrivateMode struct {
	ChatID string `gorm:"column:chat_id;primaryKey" json:"chat_id"`
	Enable bool   `gorm:"column:enable" json:"enable"`
}

// TableName PrivateMode's table name
func (*PrivateMode) TableName() string {
	return TableNamePrivateMode
}
