// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNamePromptConf = "prompt_confs"

// PromptConf mapped from table <prompt_confs>
type PromptConf struct {
	CreatedAt       time.Time      `gorm:"column:created_at" json:"created_at"`
	UpdatedAt       time.Time      `gorm:"column:updated_at" json:"updated_at"`
	DeletedAt       gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
	PromptKey       string         `gorm:"column:prompt_key;primaryKey" json:"prompt_key"`
	SystemPromptTpl string         `gorm:"column:system_prompt_tpl" json:"system_prompt_tpl"`
	UserPromptTpl   string         `gorm:"column:user_prompt_tpl" json:"user_prompt_tpl"`
}

// TableName PromptConf's table name
func (*PromptConf) TableName() string {
	return TableNamePromptConf
}
