// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameQuoteReplyMsg = "quote_reply_msgs"

// QuoteReplyMsg mapped from table <quote_reply_msgs>
type QuoteReplyMsg struct {
	MatchType string `gorm:"column:match_type;primaryKey;default:substr" json:"match_type"`
	Keyword   string `gorm:"column:keyword;primaryKey" json:"keyword"`
	Reply     string `gorm:"column:reply;primaryKey" json:"reply"`
	ReplyType string `gorm:"column:reply_type;primaryKey;default:text" json:"reply_type"`
}

// TableName QuoteReplyMsg's table name
func (*QuoteReplyMsg) TableName() string {
	return TableNameQuoteReplyMsg
}
