// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameQuoteReplyMsgCustom = "quote_reply_msg_customs"

// QuoteReplyMsgCustom mapped from table <quote_reply_msg_customs>
type QuoteReplyMsgCustom struct {
	GuildID   string `gorm:"column:guild_id;primaryKey" json:"guild_id"`
	MatchType string `gorm:"column:match_type;primaryKey;default:substr" json:"match_type"`
	Keyword   string `gorm:"column:keyword;primaryKey" json:"keyword"`
	Reply     string `gorm:"column:reply;primaryKey" json:"reply"`
	ReplyType string `gorm:"column:reply_type;primaryKey;default:text" json:"reply_type"`
}

// TableName QuoteReplyMsgCustom's table name
func (*QuoteReplyMsgCustom) TableName() string {
	return TableNameQuoteReplyMsgCustom
}
