// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameReactImageMeterial = "react_image_meterials"

// ReactImageMeterial mapped from table <react_image_meterials>
type ReactImageMeterial struct {
	GuildID string `gorm:"column:guild_id;primaryKey" json:"guild_id"`
	FileID  string `gorm:"column:file_id;primaryKey" json:"file_id"`
	Type    string `gorm:"column:type" json:"type"`
	Md5Str  string `gorm:"column:md5_str" json:"md5_str"`
}

// TableName ReactImageMeterial's table name
func (*ReactImageMeterial) TableName() string {
	return TableNameReactImageMeterial
}
