// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameReactionWhitelist = "reaction_whitelists"

// ReactionWhitelist mapped from table <reaction_whitelists>
type ReactionWhitelist struct {
	GuildID string `gorm:"column:guild_id;primaryKey" json:"guild_id"`
}

// TableName ReactionWhitelist's table name
func (*ReactionWhitelist) TableName() string {
	return TableNameReactionWhitelist
}
