// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameRepeatWordsRate = "repeat_words_rates"

// RepeatWordsRate mapped from table <repeat_words_rates>
type RepeatWordsRate struct {
	Word      string         `gorm:"column:word;primaryKey" json:"word"`
	Rate      int64          `gorm:"column:rate" json:"rate"`
	ID        int64          `gorm:"column:id;not null" json:"id"`
	CreatedAt time.Time      `gorm:"column:created_at" json:"created_at"`
	UpdatedAt time.Time      `gorm:"column:updated_at" json:"updated_at"`
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
}

// TableName RepeatWordsRate's table name
func (*RepeatWordsRate) TableName() string {
	return TableNameRepeatWordsRate
}
