// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameRepeatWordsRateCustom = "repeat_words_rate_customs"

// RepeatWordsRateCustom mapped from table <repeat_words_rate_customs>
type RepeatWordsRateCustom struct {
	CreatedAt time.Time      `gorm:"column:created_at" json:"created_at"`
	UpdatedAt time.Time      `gorm:"column:updated_at" json:"updated_at"`
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
	GuildID   string         `gorm:"column:guild_id;primaryKey" json:"guild_id"`
	Word      string         `gorm:"column:word;primaryKey" json:"word"`
	Rate      int64          `gorm:"column:rate" json:"rate"`
}

// TableName RepeatWordsRateCustom's table name
func (*RepeatWordsRateCustom) TableName() string {
	return TableNameRepeatWordsRateCustom
}
