// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameRepeatWhitelist = "repeat_whitelists"

// RepeatWhitelist mapped from table <repeat_whitelists>
type RepeatWhitelist struct {
	GuildID string `gorm:"column:guild_id;primaryKey" json:"guild_id"`
}

// TableName RepeatWhitelist's table name
func (*RepeatWhitelist) TableName() string {
	return TableNameRepeatWhitelist
}
