// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameRuntimeSchemaMigration = "runtime_schema_migrations"

// RuntimeSchemaMigration mapped from table <runtime_schema_migrations>
type RuntimeSchemaMigration struct {
	Version        string    `gorm:"column:version;primaryKey" json:"version"`
	Checksum       string    `gorm:"column:checksum;not null" json:"checksum"`
	BinaryRevision string    `gorm:"column:binary_revision;not null" json:"binary_revision"`
	AppliedAt      time.Time `gorm:"column:applied_at;not null;default:now()" json:"applied_at"`
}

// TableName RuntimeSchemaMigration's table name
func (*RuntimeSchemaMigration) TableName() string {
	return TableNameRuntimeSchemaMigration
}
