// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameStickerMapping = "sticker_mappings"

// StickerMapping mapped from table <sticker_mappings>
type StickerMapping struct {
	CreatedAt  time.Time      `gorm:"column:created_at" json:"created_at"`
	UpdatedAt  time.Time      `gorm:"column:updated_at" json:"updated_at"`
	DeletedAt  gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
	StickerKey string         `gorm:"column:sticker_key;primaryKey" json:"sticker_key"`
	ImageKey   string         `gorm:"column:image_key" json:"image_key"`
}

// TableName StickerMapping's table name
func (*StickerMapping) TableName() string {
	return TableNameStickerMapping
}
