// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameTemplateVersion = "template_versions"

// TemplateVersion mapped from table <template_versions>
type TemplateVersion struct {
	TemplateID      string    `gorm:"column:template_id;primaryKey" json:"template_id"`
	TemplateVersion string    `gorm:"column:template_version" json:"template_version"`
	CreatedAt       time.Time `gorm:"column:created_at" json:"created_at"`
	UpdatedAt       time.Time `gorm:"column:updated_at" json:"updated_at"`
	TemplateSrc     string    `gorm:"column:template_src" json:"template_src"`
}

// TableName TemplateVersion's table name
func (*TemplateVersion) TableName() string {
	return TableNameTemplateVersion
}
