// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"github.com/lib/pq"
)

const TableNameTodoItem = "todo_items"

// TodoItem mapped from table <todo_items>
type TodoItem struct {
	ID          string         `gorm:"column:id;primaryKey" json:"id"`
	ChatID      string         `gorm:"column:chat_id;not null" json:"chat_id"`
	AppID       string         `gorm:"column:app_id;not null;default:''" json:"app_id"`
	BotOpenID   string         `gorm:"column:bot_open_id;not null;default:''" json:"bot_open_id"`
	CreatorID   string         `gorm:"column:creator_id;not null" json:"creator_id"`
	CreatorName string         `gorm:"column:creator_name" json:"creator_name"`
	AssigneeID  string         `gorm:"column:assignee_id" json:"assignee_id"`
	Title       string         `gorm:"column:title;not null" json:"title"`
	Description string         `gorm:"column:description" json:"description"`
	Status      string         `gorm:"column:status;not null;default:pending;comment:状态: pending, doing, done, cancelled" json:"status"` // 状态: pending, doing, done, cancelled
	Priority    string         `gorm:"column:priority;not null;default:medium;comment:优先级: low, medium, high, urgent" json:"priority"`   // 优先级: low, medium, high, urgent
	DueAt       *time.Time     `gorm:"column:due_at" json:"due_at"`
	CompletedAt *time.Time     `gorm:"column:completed_at" json:"completed_at"`
	Tags        pq.StringArray `gorm:"column:tags;type:text[]" json:"tags"`
	CreatedAt   time.Time      `gorm:"column:created_at;not null;default:now()" json:"created_at"`
	UpdatedAt   time.Time      `gorm:"column:updated_at;not null;default:now()" json:"updated_at"`
}

// TableName TodoItem's table name
func (*TodoItem) TableName() string {
	return TableNameTodoItem
}
