// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameTodoReminder = "todo_reminders"

// TodoReminder mapped from table <todo_reminders>
type TodoReminder struct {
	ID         string    `gorm:"column:id;primaryKey" json:"id"`
	TodoID     string    `gorm:"column:todo_id" json:"todo_id"`
	ChatID     string    `gorm:"column:chat_id;not null" json:"chat_id"`
	CreatorID  string    `gorm:"column:creator_id;not null" json:"creator_id"`
	Title      string    `gorm:"column:title;not null" json:"title"`
	Content    string    `gorm:"column:content" json:"content"`
	Type       string    `gorm:"column:type;not null;default:once;comment:提醒类型: once, daily, weekly, monthly, custom" json:"type"` // 提醒类型: once, daily, weekly, monthly, custom
	Status     string    `gorm:"column:status;not null;default:pending;comment:提醒状态: pending, triggered, cancelled" json:"status"` // 提醒状态: pending, triggered, cancelled
	TriggerAt  time.Time `gorm:"column:trigger_at;not null" json:"trigger_at"`
	RepeatRule string    `gorm:"column:repeat_rule" json:"repeat_rule"`
	CreatedAt  time.Time `gorm:"column:created_at;not null;default:now()" json:"created_at"`
	UpdatedAt  time.Time `gorm:"column:updated_at;not null;default:now()" json:"updated_at"`
}

// TableName TodoReminder's table name
func (*TodoReminder) TableName() string {
	return TableNameTodoReminder
}
