// Code generated by warmup; DO NOT EDIT.

package cardhandlers

import (
	"github.com/BetaGoRobot/go_utils/reflecting"
)

func init() {
	reflecting.GetFunctionName(GetCardMusicByPage) // from /mnt/RapidPool/workspace/BetaGo_v2/internal/application/lark/card_handlers/handler.go:75
	reflecting.GetFunctionName(HandleFullLyrics)   // from /mnt/RapidPool/workspace/BetaGo_v2/internal/application/lark/card_handlers/handler.go:221
	reflecting.GetFunctionName(HandleRefreshMusic) // from /mnt/RapidPool/workspace/BetaGo_v2/internal/application/lark/card_handlers/handler.go:277
	reflecting.GetFunctionName(SendAlbumCard)      // from /mnt/RapidPool/workspace/BetaGo_v2/internal/application/lark/card_handlers/handler.go:191
	reflecting.GetFunctionName(SendMusicCard)      // from /mnt/RapidPool/workspace/BetaGo_v2/internal/application/lark/card_handlers/handler.go:179
}
