// Code generated by warmup; DO NOT EDIT.

package history

import (
	"github.com/BetaGoRobot/go_utils/reflecting"
)

func init() {
	reflecting.GetFunctionName((*Helper).GetAll)   // from /mnt/RapidPool/workspace/BetaGo_v2/internal/application/lark/history/msg.go:160
	reflecting.GetFunctionName((*Helper).GetMsg)   // from /mnt/RapidPool/workspace/BetaGo_v2/internal/application/lark/history/msg.go:127
	reflecting.GetFunctionName((*Helper).GetRaw)   // from /mnt/RapidPool/workspace/BetaGo_v2/internal/application/lark/history/msg.go:140
	reflecting.GetFunctionName((*Helper).GetTrend) // from /mnt/RapidPool/workspace/BetaGo_v2/internal/application/lark/history/msg.go:214
	reflecting.GetFunctionName(HybridSearch)       // from /mnt/RapidPool/workspace/BetaGo_v2/internal/application/lark/history/search.go:50
}
