// Code generated by warmup; DO NOT EDIT.

package handlers

import (
	"github.com/BetaGoRobot/go_utils/reflecting"
)

func init() {
	reflecting.GetFunctionName((*trendInternalHelper).DrawTrendBar) // from /mnt/RapidPool/workspace/BetaGo_v2/internal/application/lark/handlers/trend_handler.go:232
	reflecting.GetFunctionName((*trendInternalHelper).DrawTrendPie) // from /mnt/RapidPool/workspace/BetaGo_v2/internal/application/lark/handlers/trend_handler.go:197
	reflecting.GetFunctionName((*trendInternalHelper).TrendByUser)  // from /mnt/RapidPool/workspace/BetaGo_v2/internal/application/lark/handlers/trend_handler.go:271
	reflecting.GetFunctionName((*trendInternalHelper).TrendRate)    // from /mnt/RapidPool/workspace/BetaGo_v2/internal/application/lark/handlers/trend_handler.go:293
	reflecting.GetFunctionName(ChatHandlerInner)                    // from /mnt/RapidPool/workspace/BetaGo_v2/internal/application/lark/handlers/chat_handler.go:96
	reflecting.GetFunctionName(GenerateChatSeq)                     // from /mnt/RapidPool/workspace/BetaGo_v2/internal/application/lark/handlers/chat_handler.go:178
	reflecting.GetFunctionName(GetHistoryGoldGraph)                 // from /mnt/RapidPool/workspace/BetaGo_v2/internal/application/lark/handlers/stock_handler.go:338
	reflecting.GetFunctionName(GetTraceFromMsgID)                   // from /mnt/RapidPool/workspace/BetaGo_v2/internal/application/lark/handlers/debug_handler.go:314
	reflecting.GetFunctionName(configDeleteHandler.Handle)          // from /mnt/RapidPool/workspace/BetaGo_v2/internal/application/lark/handlers/config_handler.go:351
	reflecting.GetFunctionName(configListHandler.Handle)            // from /mnt/RapidPool/workspace/BetaGo_v2/internal/application/lark/handlers/config_handler.go:156
	reflecting.GetFunctionName(configSetHandler.Handle)             // from /mnt/RapidPool/workspace/BetaGo_v2/internal/application/lark/handlers/config_handler.go:235
	reflecting.GetFunctionName(featureBlockHandler.Handle)          // from /mnt/RapidPool/workspace/BetaGo_v2/internal/application/lark/handlers/config_handler.go:498
	reflecting.GetFunctionName(featureListHandler.Handle)           // from /mnt/RapidPool/workspace/BetaGo_v2/internal/application/lark/handlers/config_handler.go:412
	reflecting.GetFunctionName(featureUnblockHandler.Handle)        // from /mnt/RapidPool/workspace/BetaGo_v2/internal/application/lark/handlers/config_handler.go:582
	reflecting.GetFunctionName(goldHandler.Handle)                  // from /mnt/RapidPool/workspace/BetaGo_v2/internal/application/lark/handlers/stock_handler.go:108
	reflecting.GetFunctionName(handleDebugConversation)             // from /mnt/RapidPool/workspace/BetaGo_v2/internal/application/lark/handlers/debug_handler.go:540
	reflecting.GetFunctionName(handleDebugGetGroupID)               // from /mnt/RapidPool/workspace/BetaGo_v2/internal/application/lark/handlers/debug_handler.go:269
	reflecting.GetFunctionName(handleDebugGetID)                    // from /mnt/RapidPool/workspace/BetaGo_v2/internal/application/lark/handlers/debug_handler.go:243
	reflecting.GetFunctionName(handleDebugImage)                    // from /mnt/RapidPool/workspace/BetaGo_v2/internal/application/lark/handlers/debug_handler.go:503
	reflecting.GetFunctionName(handleDebugRepeat)                   // from /mnt/RapidPool/workspace/BetaGo_v2/internal/application/lark/handlers/debug_handler.go:458
	reflecting.GetFunctionName(handleDebugRevert)                   // from /mnt/RapidPool/workspace/BetaGo_v2/internal/application/lark/handlers/debug_handler.go:411
	reflecting.GetFunctionName(handleDebugTrace)                    // from /mnt/RapidPool/workspace/BetaGo_v2/internal/application/lark/handlers/debug_handler.go:346
	reflecting.GetFunctionName(handleDebugTryPanic)                 // from /mnt/RapidPool/workspace/BetaGo_v2/internal/application/lark/handlers/debug_handler.go:294
	reflecting.GetFunctionName(imageAddHandler.Handle)              // from /mnt/RapidPool/workspace/BetaGo_v2/internal/application/lark/handlers/image_handler.go:81
	reflecting.GetFunctionName(imageDeleteHandler.Handle)           // from /mnt/RapidPool/workspace/BetaGo_v2/internal/application/lark/handlers/image_handler.go:225
	reflecting.GetFunctionName(imageGetHandler.Handle)              // from /mnt/RapidPool/workspace/BetaGo_v2/internal/application/lark/handlers/image_handler.go:172
	reflecting.GetFunctionName(musicSearchHandler.Handle)           // from /mnt/RapidPool/workspace/BetaGo_v2/internal/application/lark/handlers/music_handler.go:78
	reflecting.GetFunctionName(muteHandler.Handle)                  // from /mnt/RapidPool/workspace/BetaGo_v2/internal/application/lark/handlers/mute_handler.go:70
	reflecting.GetFunctionName(oneWordHandler.Handle)               // from /mnt/RapidPool/workspace/BetaGo_v2/internal/application/lark/handlers/oneword_handler.go:74
	reflecting.GetFunctionName(rateLimitListHandler.Handle)         // from /mnt/RapidPool/workspace/BetaGo_v2/internal/application/lark/handlers/ratelimit_handler.go:238
	reflecting.GetFunctionName(rateLimitStatsHandler.Handle)        // from /mnt/RapidPool/workspace/BetaGo_v2/internal/application/lark/handlers/ratelimit_handler.go:69
	reflecting.GetFunctionName(replyAddHandler.Handle)              // from /mnt/RapidPool/workspace/BetaGo_v2/internal/application/lark/handlers/reply_handler.go:111
	reflecting.GetFunctionName(replyGetHandler.Handle)              // from /mnt/RapidPool/workspace/BetaGo_v2/internal/application/lark/handlers/reply_handler.go:217
	reflecting.GetFunctionName(statsGetHandler.Handle)              // from /mnt/RapidPool/workspace/BetaGo_v2/internal/application/lark/handlers/stats_handler.go:27
	reflecting.GetFunctionName(trendHandler.Handle)                 // from /mnt/RapidPool/workspace/BetaGo_v2/internal/application/lark/handlers/trend_handler.go:123
	reflecting.GetFunctionName(wordAddHandler.Handle)               // from /mnt/RapidPool/workspace/BetaGo_v2/internal/application/lark/handlers/word_handler.go:90
	reflecting.GetFunctionName(wordCloudHandler.Handle)             // from /mnt/RapidPool/workspace/BetaGo_v2/internal/application/lark/handlers/word_count_handler.go:157
	reflecting.GetFunctionName(wordGetHandler.Handle)               // from /mnt/RapidPool/workspace/BetaGo_v2/internal/application/lark/handlers/word_handler.go:126
	reflecting.GetFunctionName(zhAStockHandler.Handle)              // from /mnt/RapidPool/workspace/BetaGo_v2/internal/application/lark/handlers/stock_handler.go:259
}
