// Code generated by warmup; DO NOT EDIT.

package handlers

import (
	"github.com/BetaGoRobot/go_utils/reflecting"
)

func init() {
	reflecting.GetFunctionName((*trendInternalHelper).DrawTrendBar) // from /mnt/RapidPool/workspace/BetaGo_v2/internal/application/lark/handlers/trend_handler.go:235
	reflecting.GetFunctionName((*trendInternalHelper).DrawTrendPie) // from /mnt/RapidPool/workspace/BetaGo_v2/internal/application/lark/handlers/trend_handler.go:197
	reflecting.GetFunctionName((*trendInternalHelper).TrendByUser)  // from /mnt/RapidPool/workspace/BetaGo_v2/internal/application/lark/handlers/trend_handler.go:277
	reflecting.GetFunctionName((*trendInternalHelper).TrendRate)    // from /mnt/RapidPool/workspace/BetaGo_v2/internal/application/lark/handlers/trend_handler.go:299
	reflecting.GetFunctionName(ChatHandlerInner)                    // from /mnt/RapidPool/workspace/BetaGo_v2/internal/application/lark/handlers/chat_handler.go:97
	reflecting.GetFunctionName(GenerateChatSeq)                     // from /mnt/RapidPool/workspace/BetaGo_v2/internal/application/lark/handlers/chat_handler.go:179
	reflecting.GetFunctionName(GetHistoryGoldGraph)                 // from /mnt/RapidPool/workspace/BetaGo_v2/internal/application/lark/handlers/stock_handler.go:324
	reflecting.GetFunctionName(GetTraceFromMsgID)                   // from /mnt/RapidPool/workspace/BetaGo_v2/internal/application/lark/handlers/debug_handler.go:320
	reflecting.GetFunctionName(configDeleteHandler.Handle)          // from /mnt/RapidPool/workspace/BetaGo_v2/internal/application/lark/handlers/config_handler.go:241
	reflecting.GetFunctionName(configListHandler.Handle)            // from /mnt/RapidPool/workspace/BetaGo_v2/internal/application/lark/handlers/config_handler.go:153
	reflecting.GetFunctionName(configSetHandler.Handle)             // from /mnt/RapidPool/workspace/BetaGo_v2/internal/application/lark/handlers/config_handler.go:170
	reflecting.GetFunctionName(featureBlockHandler.Handle)          // from /mnt/RapidPool/workspace/BetaGo_v2/internal/application/lark/handlers/config_handler.go:353
	reflecting.GetFunctionName(featureListHandler.Handle)           // from /mnt/RapidPool/workspace/BetaGo_v2/internal/application/lark/handlers/config_handler.go:288
	reflecting.GetFunctionName(featureUnblockHandler.Handle)        // from /mnt/RapidPool/workspace/BetaGo_v2/internal/application/lark/handlers/config_handler.go:419
	reflecting.GetFunctionName(goldHandler.Handle)                  // from /mnt/RapidPool/workspace/BetaGo_v2/internal/application/lark/handlers/stock_handler.go:111
	reflecting.GetFunctionName(handleDebugConversation)             // from /mnt/RapidPool/workspace/BetaGo_v2/internal/application/lark/handlers/debug_handler.go:537
	reflecting.GetFunctionName(handleDebugGetGroupID)               // from /mnt/RapidPool/workspace/BetaGo_v2/internal/application/lark/handlers/debug_handler.go:275
	reflecting.GetFunctionName(handleDebugGetID)                    // from /mnt/RapidPool/workspace/BetaGo_v2/internal/application/lark/handlers/debug_handler.go:249
	reflecting.GetFunctionName(handleDebugImage)                    // from /mnt/RapidPool/workspace/BetaGo_v2/internal/application/lark/handlers/debug_handler.go:500
	reflecting.GetFunctionName(handleDebugRepeat)                   // from /mnt/RapidPool/workspace/BetaGo_v2/internal/application/lark/handlers/debug_handler.go:464
	reflecting.GetFunctionName(handleDebugRevert)                   // from /mnt/RapidPool/workspace/BetaGo_v2/internal/application/lark/handlers/debug_handler.go:417
	reflecting.GetFunctionName(handleDebugTrace)                    // from /mnt/RapidPool/workspace/BetaGo_v2/internal/application/lark/handlers/debug_handler.go:352
	reflecting.GetFunctionName(handleDebugTryPanic)                 // from /mnt/RapidPool/workspace/BetaGo_v2/internal/application/lark/handlers/debug_handler.go:300
	reflecting.GetFunctionName(imageAddHandler.Handle)              // from /mnt/RapidPool/workspace/BetaGo_v2/internal/application/lark/handlers/image_handler.go:91
	reflecting.GetFunctionName(imageDeleteHandler.Handle)           // from /mnt/RapidPool/workspace/BetaGo_v2/internal/application/lark/handlers/image_handler.go:265
	reflecting.GetFunctionName(imageGetHandler.Handle)              // from /mnt/RapidPool/workspace/BetaGo_v2/internal/application/lark/handlers/image_handler.go:200
	reflecting.GetFunctionName(musicSearchHandler.Handle)           // from /mnt/RapidPool/workspace/BetaGo_v2/internal/application/lark/handlers/music_handler.go:77
	reflecting.GetFunctionName(muteHandler.Handle)                  // from /mnt/RapidPool/workspace/BetaGo_v2/internal/application/lark/handlers/mute_handler.go:69
	reflecting.GetFunctionName(oneWordHandler.Handle)               // from /mnt/RapidPool/workspace/BetaGo_v2/internal/application/lark/handlers/oneword_handler.go:73
	reflecting.GetFunctionName(rateLimitListHandler.Handle)         // from /mnt/RapidPool/workspace/BetaGo_v2/internal/application/lark/handlers/ratelimit_handler.go:103
	reflecting.GetFunctionName(rateLimitStatsHandler.Handle)        // from /mnt/RapidPool/workspace/BetaGo_v2/internal/application/lark/handlers/ratelimit_handler.go:67
	reflecting.GetFunctionName(replyAddHandler.Handle)              // from /mnt/RapidPool/workspace/BetaGo_v2/internal/application/lark/handlers/reply_handler.go:121
	reflecting.GetFunctionName(replyGetHandler.Handle)              // from /mnt/RapidPool/workspace/BetaGo_v2/internal/application/lark/handlers/reply_handler.go:236
	reflecting.GetFunctionName(statsGetHandler.Handle)              // from /mnt/RapidPool/workspace/BetaGo_v2/internal/application/lark/handlers/stats_handler.go:27
	reflecting.GetFunctionName(trendHandler.Handle)                 // from /mnt/RapidPool/workspace/BetaGo_v2/internal/application/lark/handlers/trend_handler.go:123
	reflecting.GetFunctionName(wordAddHandler.Handle)               // from /mnt/RapidPool/workspace/BetaGo_v2/internal/application/lark/handlers/word_handler.go:89
	reflecting.GetFunctionName(wordCloudHandler.Handle)             // from /mnt/RapidPool/workspace/BetaGo_v2/internal/application/lark/handlers/word_count_handler.go:157
	reflecting.GetFunctionName(wordGetHandler.Handle)               // from /mnt/RapidPool/workspace/BetaGo_v2/internal/application/lark/handlers/word_handler.go:125
	reflecting.GetFunctionName(zhAStockHandler.Handle)              // from /mnt/RapidPool/workspace/BetaGo_v2/internal/application/lark/handlers/stock_handler.go:254
}
