// Code generated by warmup; DO NOT EDIT.

package lark

import (
	"github.com/BetaGoRobot/go_utils/reflecting"
)

func init() {
	reflecting.GetFunctionName(CardActionHandler)      // from /mnt/RapidPool/workspace/BetaGo_v2/internal/interfaces/lark/handler.go:77
	reflecting.GetFunctionName(MessageReactionHandler) // from /mnt/RapidPool/workspace/BetaGo_v2/internal/interfaces/lark/handler.go:67
	reflecting.GetFunctionName(MessageV2Handler)       // from /mnt/RapidPool/workspace/BetaGo_v2/internal/interfaces/lark/handler.go:37
}
