// Code generated by warmup; DO NOT EDIT.

package aktool

import (
	"github.com/BetaGoRobot/go_utils/reflecting"
)

func init() {
	reflecting.GetFunctionName(httpProvider.GetHistoryGoldPrice)  // from /mnt/RapidPool/workspace/BetaGo_v2/internal/infrastructure/aktool/aktool.go:173
	reflecting.GetFunctionName(httpProvider.GetRealtimeGoldPrice) // from /mnt/RapidPool/workspace/BetaGo_v2/internal/infrastructure/aktool/aktool.go:147
	reflecting.GetFunctionName(httpProvider.GetStockPriceRT)      // from /mnt/RapidPool/workspace/BetaGo_v2/internal/infrastructure/aktool/aktool.go:199
	reflecting.GetFunctionName(httpProvider.GetStockSymbolInfo)   // from /mnt/RapidPool/workspace/BetaGo_v2/internal/infrastructure/aktool/aktool.go:227
}
