// Code generated by warmup; DO NOT EDIT.

package larkuser

import (
	"github.com/BetaGoRobot/go_utils/reflecting"
)

func init() {
	reflecting.GetFunctionName(GetUserInfo)           // from /mnt/RapidPool/workspace/BetaGo_v2/internal/infrastructure/lark_dal/larkuser/user.go:18
	reflecting.GetFunctionName(GetUserInfoCache)      // from /mnt/RapidPool/workspace/BetaGo_v2/internal/infrastructure/lark_dal/larkuser/user.go:33
	reflecting.GetFunctionName(GetUserMapFromChatID)  // from /mnt/RapidPool/workspace/BetaGo_v2/internal/infrastructure/lark_dal/larkuser/user.go:78
	reflecting.GetFunctionName(GetUserMemberFromChat) // from /mnt/RapidPool/workspace/BetaGo_v2/internal/infrastructure/lark_dal/larkuser/user.go:59
}
