// Code generated by warmup; DO NOT EDIT.

package larkimg

import (
	"github.com/BetaGoRobot/go_utils/reflecting"
)

func init() {
	reflecting.GetFunctionName(DownImgFromMsgAsync)      // from /mnt/RapidPool/workspace/BetaGo_v2/internal/infrastructure/lark_dal/larkimg/img.go:98
	reflecting.GetFunctionName(DownImgFromMsgSync)       // from /mnt/RapidPool/workspace/BetaGo_v2/internal/infrastructure/lark_dal/larkimg/img.go:44
	reflecting.GetFunctionName(GetAllImageFromMsgEvent)  // from /mnt/RapidPool/workspace/BetaGo_v2/internal/infrastructure/lark_dal/larkimg/img.go:252
	reflecting.GetFunctionName(GetAllImgTagFromMsg)      // from /mnt/RapidPool/workspace/BetaGo_v2/internal/infrastructure/lark_dal/larkimg/img.go:213
	reflecting.GetFunctionName(GetAllImgURLFromMsg)      // from /mnt/RapidPool/workspace/BetaGo_v2/internal/infrastructure/lark_dal/larkimg/img.go:313, /mnt/RapidPool/workspace/BetaGo_v2/internal/infrastructure/lark_dal/larkimg/img.go:336
	reflecting.GetFunctionName(GetAndResizePicFromURL)   // from /mnt/RapidPool/workspace/BetaGo_v2/internal/infrastructure/lark_dal/larkimg/img.go:401
	reflecting.GetFunctionName(Upload2Lark)              // from /mnt/RapidPool/workspace/BetaGo_v2/internal/infrastructure/lark_dal/larkimg/img.go:479
	reflecting.GetFunctionName(UploadPicAllinOne)        // from /mnt/RapidPool/workspace/BetaGo_v2/internal/infrastructure/lark_dal/larkimg/img.go:430
	reflecting.GetFunctionName(UploadPicture2Lark)       // from /mnt/RapidPool/workspace/BetaGo_v2/internal/infrastructure/lark_dal/larkimg/img.go:539
	reflecting.GetFunctionName(UploadPicture2LarkReader) // from /mnt/RapidPool/workspace/BetaGo_v2/internal/infrastructure/lark_dal/larkimg/img.go:513
	reflecting.GetFunctionName(getAllImage)              // from /mnt/RapidPool/workspace/BetaGo_v2/internal/infrastructure/lark_dal/larkimg/img.go:287
}
