// Code generated by warmup; DO NOT EDIT.

package vadvisor

import (
	"github.com/BetaGoRobot/go_utils/reflecting"
)

func init() {
	reflecting.GetFunctionName((*MultiSeriesLineGraph[string, float64]).AddData)      // from /mnt/RapidPool/workspace/BetaGo_v2/internal/application/lark/handlers/stock_handler.go:404
	reflecting.GetFunctionName((*MultiSeriesLineGraph[string, float64]).UpdateMinMax) // from /mnt/RapidPool/workspace/BetaGo_v2/internal/application/lark/handlers/stock_handler.go:405
}
