// Code generated by warmup; DO NOT EDIT.

package xcopywriting

import (
	"github.com/BetaGoRobot/go_utils/reflecting"
)

func init() {
	reflecting.GetFunctionName(GetCopyWritings)       // from /mnt/RapidPool/workspace/BetaGo_v2/pkg/xcopywriting/cw.go:28
	reflecting.GetFunctionName(GetSampleCopyWritings) // from /mnt/RapidPool/workspace/BetaGo_v2/pkg/xcopywriting/cw.go:65
}
