// Code generated by warmup; DO NOT EDIT.

package larkchat

import (
	"github.com/BetaGoRobot/go_utils/reflecting"
)

func init() {
	reflecting.GetFunctionName(GetChatInfo)      // from /mnt/RapidPool/workspace/BetaGo_v2/internal/infrastructure/lark_dal/larkchat/chat.go:33
	reflecting.GetFunctionName(GetChatInfoCache) // from /mnt/RapidPool/workspace/BetaGo_v2/internal/infrastructure/lark_dal/larkchat/chat.go:50
	reflecting.GetFunctionName(GetChatName)      // from /mnt/RapidPool/workspace/BetaGo_v2/internal/infrastructure/lark_dal/larkchat/chat.go:15
}
