// Code generated by warmup; DO NOT EDIT.

package reaction

import (
	"github.com/BetaGoRobot/go_utils/reflecting"
)

func init() {
	reflecting.GetFunctionName((*FollowReactionOperator).Run) // from /mnt/RapidPool/workspace/BetaGo_v2/internal/application/lark/reaction/follow_react.go:50
	reflecting.GetFunctionName((*RecordReactionOperator).Run) // from /mnt/RapidPool/workspace/BetaGo_v2/internal/application/lark/reaction/record_reaction.go:51
}
