// Code generated by warmup; DO NOT EDIT.

package opensearch

import (
	"github.com/BetaGoRobot/go_utils/reflecting"
)

func init() {
	reflecting.GetFunctionName(liveBackend.InsertData)    // from /mnt/RapidPool/workspace/BetaGo_v2/internal/infrastructure/opensearch/os.go:65
	reflecting.GetFunctionName(liveBackend.SearchData)    // from /mnt/RapidPool/workspace/BetaGo_v2/internal/infrastructure/opensearch/os.go:84
	reflecting.GetFunctionName(liveBackend.SearchDataStr) // from /mnt/RapidPool/workspace/BetaGo_v2/internal/infrastructure/opensearch/os.go:96
}
