// Code generated by warmup; DO NOT EDIT.

package larkcard

import (
	"github.com/BetaGoRobot/go_utils/reflecting"
)

func init() {
	reflecting.GetFunctionName((*CardBuilderBase).Build)  // from /mnt/RapidPool/workspace/BetaGo_v2/internal/infrastructure/lark_dal/larkmsg/larkcard/base.go:38
	reflecting.GetFunctionName((*CardBuilderGraph).Build) // from /mnt/RapidPool/workspace/BetaGo_v2/internal/infrastructure/lark_dal/larkmsg/larkcard/graph.go:55
}
